Fyrd/caniuse

features-json/flexbox.json

+flexbox: flexbugs repo list

---

features-json/css-masks.json

"but lacks support for othe parts of the spec"
missing r

Fixed a typo

---

features-json/datauri.json

Update Data URI Information Page link

---

features-json/online-status.json

in -> is typo

---

features-json/calc.json

currently the stackoverflow.com link isn't working

Fix Link on calc() known issues

---

features-json/x-doc-messaging.json

Cross domain postMessage now works in Project Spartan

---

features-json/ime.json

msGetInputMethodContext() should be msGetInputContext

---

features-json/xml-serializer.json

See https://connect.microsoft.com/IE/feedback/details/811408

Added IE Bug 811408 for innerText, innerHTML or outerHTML

---

features-json/css-media-interaction.json

See also: http://html5please.com/#interaction

Add link to polyfill for `hover` media feature

---

features-json/ime.json

Speculatively continued it. Alternatively, it can just be removed.

Fixed some truncated text.

---

features-json/html5semantic.json

html5semantic: Remove redundant non-numbered note

---

features-json/css-boxdecorationbreak.json
features-json/css-reflections.json
features-json/css3-tabsize.json
features-json/dragndrop.json
features-json/form-attribute.json
features-json/matchesselector.json
features-json/text-decoration.json
features-json/text-emphasis.json

Add more links to relevant MS Edge feature requests

---

validator/validate-jsons.js

This mistake has happened a couple times already:
* https://github.com/Fyrd/caniuse/pull/1684/files#diff-c7522777c6983b9fbc86c8d9274f7a59R226
* https://github.com/Fyrd/caniuse/pull/1685#discussion-diff-33322578R224

Validate that parent != "parentfeatureid"

---

validator/validate-jsons.js

Validate that feature files have `.json` file extension

---

features-json/getboundingclientrect.json

Happy 4th of July!
Fixes #991.
Testcase used to gather data: http://jsfiddle.net/cvrebert/yrspdqs1/show

Add support data for Element.getBoundingClientRect()

---

features-json/custom-elements.json

Maybe something else needs to be added?
https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement

Match Document.registerElement

---

features-json/history.json

I opened a bug report on the IE Feedback site.

Add bug report for IE popstate bug

---

features-json/contentsecuritypolicy2.json

I finished testing the remaining browsers. Please let me know if there's anything else needed to toggle "shown:true". The tests are run against http://csp.metaltoad.com/. Thanks!

More complete table for CSP 2.

---

features-json/speech-recognition.json
features-json/speech-synthesis.json

Separate Web Speech API in 2 parts:
- Speech Recognition API
- Speech Synthesis API

Web speach API reorganisation

---

features-json/pagevisibility.json

[WebPlatform Docs moved it](https://docs.webplatform.org/wiki/apis/timing/properties/visibilityState)

Update WebPlatform Docs visibilityState URL

---

features-json/classlist.json

"classList (DOMTokenList )" -> "classList (DOMTokenList)"
Very minor typo fix.

Change title to "classList (DOMTokenList)"

---

features-json/innertext.json

Fixes #1088.
Testcase: http://jsfiddle.net/cvrebert/eeL75Le6/show/

add Node.innerText

---

features-json/addeventlistener.json

Fixes #1085.
Supersedes #1897.

addEventListener: add capture phase of DOM event dispatch

---

features-json/innertext.json

https://bugzilla.mozilla.org/show_bug.cgi?id=264412

innerText: add link to Firefox bug

---

features-json/ogg-vorbis.json

http://dev.modern.ie/platform/status/vorbisaudiocodec/

ogg-vorbis: Add IE platform status ID

---

features-json/opus.json

http://dev.modern.ie/platform/status/opusaudiocodec/

opus: Add IE platform status ID

---

features-json/ogg-vorbis.json
features-json/ogv.json

https://dev.modern.ie/platform/status/oggcontainer/

ogv, ogg-vorbis: Add Ogg Container to relevant IE platform status IDs

---

features-json/rem.json

http://stackoverflow.com/a/20065150/1922144 and I just confirmed on device.

iOS Safari 5.1 issues

---

features-json/font-variant-alternates.json

Added specification link, corrected status metadata

font-variant-alternates is CR, not unofficial

---

features-json/ol-reversed.json

https://dev.modern.ie/platform/status/olreversedattribute/

ol-reversed: Add Edge platform status ID

---

features-json/menu.json

https://dev.modern.ie/platform/status/menuelement/

menu: Add Edge platform status ID

---

features-json/css-regions.json

https://bugzilla.mozilla.org/show_bug.cgi?id=674802

css-regions: Add link to relevant Firefox bug

---

features-json/internationalization.json

https://bugs.webkit.org/show_bug.cgi?id=90906

internationalization: Add relevant WebKit bug

---

features-json/maxlength.json

See https://github.com/Fyrd/caniuse/issues/1770#issuecomment-140523871

maxlength: Add info about @Serabe's iOS 8 bug

---

features-json/download.json

https://bugs.webkit.org/show_bug.cgi?id=102914

download: Add link to WebKit feature request

---

.travis.yml

Should slightly increase the speed of the build.
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/

Use container-based Travis infrastructure

---

features-json/keyboardevent-code.json

https://dev.modern.ie/platform/status/uieventskeyboardqueryapis/

keyboardevent-code: Add Edge platform status ID

---

features-json/keyboardevent-code.json

https://bugs.webkit.org/show_bug.cgi?id=149584

keyboardevent-code: Add relevant WebKit bug

---

features-json/keyboardevent-which.json

Clarify that KeyboardEvent.which is legacy/deprecated

---

features-json/css-media-resolution.json

https://bugs.webkit.org/show_bug.cgi?id=78087

css-media-resolution: Add link to relevant WebKit bug

---

features-json/input-minlength.json

https://bugs.webkit.org/show_bug.cgi?id=149832

input-minlength: Add link to relevant WebKit bug

---

features-json/css-touch-action.json

* https://bugs.webkit.org/show_bug.cgi?id=149854
* https://bugs.webkit.org/show_bug.cgi?id=133112

css-touch-action: Add links to relevant WebKit bugs

---

features-json/cors.json

Fixes a simple Markdown markup issue

cors: Fix notes

---

features-json/css-scroll-behavior.json

https://dev.modern.ie/platform/status/cssomviewsmoothscrollapi/

css-scroll-behavior: Add ie_id

---

features-json/proxy.json

https://bugs.webkit.org/show_bug.cgi?id=35731

ES6 Proxy: Add WebKit bug link

---

CONTRIBUTING.md

CONTRIBUTING.md: Add firefox_id and webkit_id

---

validator/validate-jsons.js

Add firefox_id and webkit_id to JSON validator

---

features-json/serviceworkers.json

New Webkit Website: new webkit id´s

update Webkit ID

---

features-json/css-first-letter.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1233271

css-first-letter: Link to Firefox bug report instead of StackOverflow

---

features-json/css-variables.json

https://code.google.com/p/chromium/issues/detail?id=568892#c1

Chrome 49 ships CSS variables

---

features-json/flexbox.json

Added - 10up Open Sources IE 8 and 9 Support for Flexbox

10up Open Sources IE 8 and 9 Support for Flexbox

---

features-json/innertext.json

See https://github.com/whatwg/compat/issues/5#issuecomment-168049752

innerText: Cite draft spec instead of MSDN

---

features-json/webvtt.json

https://bugzilla.mozilla.org/show_bug.cgi?id=865395

webvtt: Link to relevant Firefox bug

---

features-json/brotli.json

Per https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/JufzX024oy0/WEOGbN43AwAJ

Add Blink's support for Brotli

---

features-json/css-hyphens.json

https://code.google.com/p/chromium/issues/detail?id=47083

css-hyphens: Add link to relevant Chrome bug

---

features-json/css-revert-value.json

https://code.google.com/p/chromium/issues/detail?id=579788

css-revert-value: Link to relevant Chrome issue

---

features-json/notifications.json

Use the up to date upstream as spec reference instead of an out of date fork

Change notifications spec URL to whatwg

---

features-json/css-read-only-write.json

See https://github.com/whatwg/wattsi/issues/14

Change :read-only/:read-write spec URL to whatwg

---

features-json/rtcpeerconnection.json

It's more up to date and has the new stylesheet!

Update WebRTC spec URL to editor's draft

---

features-json/classlist.json

Use the up to date upstream spec reference

Change classList spec URL to whatwg

---

features-json/channel-messaging.json
features-json/classlist.json
features-json/cors.json
features-json/css-read-only-write.json
features-json/dom-range.json
features-json/eventsource.json
features-json/namevalue-storage.json
features-json/notifications.json
features-json/queryselector.json
features-json/requestanimationframe.json
features-json/websockets.json
features-json/xhtml.json

Refs #2234, #2236, #2237, #2238, #2239, #2242, #2243.

Correct status of WHATWG specs to Living Standard (LS)

---

validator/validate-jsons.js

Validate that WHATWG specs & W3C statuses aren't used together

---

features-json/indexeddb.json

Update indexeddb.json : add MDN

---

features-json/brotli.json

Newly added https://github.com/MicrosoftEdge/Status/pull/322

Add the Edge entry for brotli

---

features-json/css-sticky.json

Was redirecting and section identifier had changed

css-sticky: Update spec URL

---

features-json/woff2.json

credit: https://twitter.com/bram_stein/status/717034829355819008

WOFF2: removed old FFx flag info, + Edge In Dev

---

features-json/css-default-pseudo.json

https://bugs.webkit.org/show_bug.cgi?id=156230
Refs #2400

css-default-pseudo: Link to relevant WebKit bug

---

features-json/css-indeterminate-pseudo.json

Testcase: http://jsbin.com/zumoqu/edit?html,css,js,output
Refs #1058

Add data for the :indeterminate CSS pseudo-class

---

features-json/sharedworkers.json

* https://platform-status.mozilla.org/#shared-worker
* https://webkit.org/status/#feature-shared-web-workers

sharedworkers: Add Firefox & WebKit platform status IDs

---

features-json/css-media-interaction.json

https://webkit.org/status/#feature-interaction-media-features-(pointer,-hover,-any-pointer,-any-hover)

css-media-interaction: Add WebKit platform status ID

---

features-json/promises.json

https://webkit.org/status/#feature-promise-objects

promises: Add WebKit platform status ID

---

features-json/css-shapes.json

* https://platform-status.mozilla.org/#css-shapes
* https://webkit.org/status/#feature-css-shapes-level-1

css-shapes: Add Firefox & WebKit platform status IDs

---

features-json/css-variables.json

* https://platform-status.mozilla.org/#css-variables
* https://webkit.org/status/#specification-css-variables

css-variables: Add Firefox & WebKit platform status IDs

---

features-json/download.json

https://webkit.org/status/#feature-download-attribute

download: Add WebKit platform status ID

---

features-json/web-animation.json

https://webkit.org/status/#specification-web-animations

web-animation: Add WebKit platform status ID

---

features-json/css-grid.json

https://platform-status.mozilla.org/#grid-layout

grid-layout: Add Firefox platform status ID

---

features-json/pointer.json

https://platform-status.mozilla.org/#pointer-events

pointer: Add Firefox platform status ID

---

features-json/subresource-integrity.json

https://platform-status.mozilla.org/#subresource-integrity

subresource-integrity: Add Firefox platform status ID

---

features-json/speech-synthesis.json

https://platform-status.mozilla.org/#webspeech-synthesis

speech-synthesis: Add Firefox platform status ID

---

features-json/subresource-integrity.json

* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/subresourceintegrity
* https://bugs.webkit.org/show_bug.cgi?id=148363

subresource-integrity: Add Edge platform status ID & relevant WebKit bug

---

features-json/u2f.json

Microsoft tracks this feature in https://developer.microsoft.com/en-us/microsoft-edge/platform/status/fidou2f (Not currently planned).

Add ie_id for FIDO U2F

---

features-json/css-descendant-gtgt.json

* https://bugs.chromium.org/p/chromium/issues/detail?id=446050
* https://bugzilla.mozilla.org/show_bug.cgi?id=1266283

css-descendant-gtgt: Add links to Chrome & Firefox bugs

---

features-json/css-has.json

css-has: Copyediting

---

features-json/text-stroke.json

https://compat.spec.whatwg.org/#text-fill-and-stroking

text-stroke: Cite WHATWG Compat spec

---

features-json/css-media-resolution.json

https://compat.spec.whatwg.org/#css-media-queries-webkit-device-pixel-ratio

css-media-resolution: Link to -webkit-device-pixel-ratio spec

---

features-json/client-hints-dpr-width-viewport.json

* https://bugzilla.mozilla.org/show_bug.cgi?id=935216
* https://bugs.webkit.org/show_bug.cgi?id=145380
* https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261321-http-client-hints

client-hints-dpr-width-viewport: Link to Firefox, WebKit, Edge bugs/requests

---

features-json/client-hints-dpr-width-viewport.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/httpclienthints

client-hints-dpr-width-viewport: Add MS Edge platform status ID

---

features-json/contentsecuritypolicy2.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/contentsecuritypolicylevel2

Add id for IE status to CSP2

---

LICENSE

Just to make it completely clear that the repo is licensed under CC-BY-4.0.
(I wish to continue contributing, and having a `LICENSE` file will make it much easier to get approval from my new company's legal department.)
File content obtained via:
```bash
$ curl http://creativecommons.org/licenses/by/4.0/legalcode.txt > LICENSE
```

Add LICENSE file for CC-BY-4.0

---

features-json/css-dir-pseudo.json

Refs #1058.
Testcase: http://jsbin.com/celuye/edit?html,css,output

Add data for :dir() pseudo-class from Selectors Level 4

---

features-json/css-dir-pseudo.json

Refs https://www.chromestatus.com/feature/5751531651465216

css-dir-pseudo: Add Chrome feature ID

---

features-json/css-case-insensitive.json

Refs https://www.chromestatus.com/feature/5610936115134464

css-case-insensitive: Add Chrome feature ID

---

features-json/dom-manip-convenience.json

Refs https://bugs.chromium.org/p/chromium/issues/detail?id=255482#c33

dom-manip-convenience: These are in Chrome 52+ behind a flag

---

features-json/subresource-integrity.json

See https://www.w3.org/TR/SRI/.

Subresource Integrity is now a W3C Recommendation

---

features-json/dialog.json

Refs https://bugs.webkit.org/show_bug.cgi?id=84635

dialog: Add link to WebKit tracking bug

---

features-json/css-placeholder.json

Refs https://bugs.chromium.org/p/chromium/issues/detail?id=623345

css-placeholder: Add link to Chrome unprefixing bug

---

features-json/form-validation.json

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1285425
Refs #2384

form-validation: Link to relevant Firefox & Edge bugs

---

features-json/text-decoration.json

See this codepen in Safari 8, 9, 10 and Technology Preview to check support: http://codepen.io/nhoizey/pen/kXpyyw/

Add text-decoration-skip

---

features-json/css-placeholder-shown.json

https://www.chromestatus.com/feature/6404760559157248

css-placeholder-shown: Add Chrome feature ID

---

features-json/brotli.json

https://tools.ietf.org/html/rfc7932

Add link to RFC 7932

---

features-json/indeterminate-checkbox.json

https://bugs.webkit.org/show_bug.cgi?id=160484

indeterminate-checkbox: Add link to relevant WebKit bug

---

features-json/text-size-adjust.json

https://www.chromestatus.com/feature/5730156303876096

text-size-adjust: Add Chrome feature ID

---

features-json/web-bluetooth.json

Hello @Fyrd, here's an update to the Web Bluetooth API.

Add Origin Trials for Web Bluetooth

---

features-json/textencoder.json

https://bugs.webkit.org/show_bug.cgi?id=160653

textencoder: Add link to relevant WebKit bug

---

features-json/dom-manip-convenience.json

https://www.chromestatus.com/feature/5723067795898368

dom-manip-convenience: Add Chrome status ID

---

features-json/maxlength.json

https://connect.microsoft.com/IE/feedback/details/1776779
has been superseded by
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4678527/

maxlength: Update MS Edge bug link

---

features-json/css-in-out-of-range.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7190958/

css-in-out-of-range: Add Edge bug link to Note 3

---

features-json/css-placeholder-shown.json

See http://www.w3.org/TR/selectors4/#placeholder

:placeholder-shown is part of the Selectors 4 Working Draft

---

features-json/filereader.json

https://bugzilla.mozilla.org/show_bug.cgi?id=901097

FileReader is now exposed for web workers in FF

---

features-json/dataset.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15885483-support-dataset-and-data-attributes-on-svg-element

dataset: Add link to relevant UserVoice idea

---

features-json/css-nth-child-of.json

i.e. https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/15944476

css-nth-child-of: Add link to Edge UserVoice feature request

---

features-json/dom-manip-convenience.json

* https://developer.mozilla.org/en-US/docs/Web/API/ParentNode
* https://developer.mozilla.org/en-US/docs/Web/API/ChildNode

dom-manip-convenience: Add links to MDN articles

---

features-json/dom-manip-convenience.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16036408

dom-manip-convenience: Link to relevant UserVoice

---

features-json/css-variables.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/csscustompropertiesakacssvariables/
Fixes #2814

css-variables: Update ie_id

---

features-json/css-focus-within.json

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within

Add link to new MDN article about :focus-within

---

features-json/link-rel-preload.json

* https://webkit.org/status/#feature-preload
* https://www.chromestatus.com/feature/5757468554559488

link-rel-preload: Add WebKit & Chrome IDs

---

features-json/resource-timing.json

https://webkit.org/status/#specification-resource-timing

resource-timing: Add WebKit ID

---

features-json/subresource-integrity.json

* https://www.chromestatus.com/feature/6183089948590080
* https://webkit.org/status/#feature-subresource-integrity

subresource-integrity: Add Chrome & WebKit IDs

---

features-json/css-backdrop-filter.json

* https://www.chromestatus.com/feature/5679432723333120
* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/backdropfilter/

css-backdrop-filter: Add Chrome & Edge IDs

---

features-json/element-closest.json

* https://webkit.org/status/#feature-element.closest()

element-closest: Add WebKit feature ID

---

features-json/input-number.json

The linked resource is over a year old but still up to date today.

Add link explaining limited localization support

---

features-json/textencoder.json

See https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard/

textencoder: Add ie_id

---

features-json/css-grid.json

> W3C Candidate Recommendation, 29 September 2016
https://www.w3.org/TR/css3-grid-layout/

Update status of CSS Grid to CR

---

features-json/svg.json

See http://codepen.io/hexalys/pen/epErZj/ for insider details of tests and my polyfill methods.

Add/update to list of browsers not supporting <use xlink:href>

---

features-json/insertadjacenthtml.json

Refs https://bugs.webkit.org/show_bug.cgi?id=162479

insertadjacenthtml: Add entry for Safari<TP15 bug

---

features-json/mpeg4.json

Both bugs have been marked as fixed.

Chromium bugs have been fixed

---

features-json/menu.json

https://bugs.chromium.org/p/chromium/issues/detail?id=412945#c48

Context menu support was removed from "Experimental Web Platform" flag

---

.travis.yml

Since this is not supported/maintained by nodejs

Drop support for node v5

---

features-json/custom-elementsv1.json

https://webkit.org/blog/7027/introducing-custom-elements/

custom-elementsv1: Add WebKit blog link

---

features-json/text-size-adjust.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1226116

text-size-adjust: Add link to Firefox bug

---

features-json/calc.json

calc: Update Firefox bug note to reflect fix

---

features-json/flexbox.json

https://bugs.webkit.org/show_bug.cgi?id=136041 has been marked as fixed minutes ago.
(I also changed the working for the ff bug so it's more clear on first sight)

Fixed Safari flexbox bug #136041

---

features-json/css-grid.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1217086

css-grid: Remove outdated comment regarding Firefox

---

features-json/css-hyphens.json

https://developers.google.com/web/updates/2016/10/css-hyphens

Chrome hyphens update

---

features-json/flexbox.json

Remove misleading info about an IE10 flexbox bug

---

features-json/form-validation.json

Tweet: https://twitter.com/chris_dumez/status/806601644855074818
Mentioned in: https://webkit.org/blog/7093/release-notes-for-safari-technology-preview-19/
Ticket: https://bugs.webkit.org/show_bug.cgi?id=165123
Commit: https://trac.webkit.org/changeset/209060/trunk/Source

Safari TP enabled HTML interactive form validation

---

features-json/dommatrix.json

MDN article: https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix

dommatrix: Add MDN link and tweak title of WebKit link

---

features-json/css-animation.json

Hope it saves someone the enormous effort of Googling it themselves ;)

Add link to Bugzilla report

---

features-json/input-datetime.json

Source: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8810417/

Add bug regarding the time control in Edge

---

features-json/transforms2d.json

transforms2d: Add "skew" to search keywords

---

features-json/dragndrop.json

Add "draggable" keyword

---

features-json/once-event-listener.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17702248-implement-once-event-listener-option

once-event-listener: Link to Edge feature request

---

features-json/rtcpeerconnection.json

See https://blogs.windows.com/msedgedev/2017/01/31/introducing-webrtc-microsoft-edge/

WebRTC enabled by default in Edge 15

---

features-json/css-grid.json

https://webkit.org/blog/7434/css-grid-layout-a-new-layout-module-for-the-web/

WebKit Blog post for CSS grid

---

features-json/aux-click.json

Fix a typo in aux-click.json

---

features-json/es6-module.json

https://blog.hospodarets.com/native-ecmascript-modules-the-first-overview

Add Blog post about ES6 module

---

features-json/css-grid.json

Fixed in Chrome 58, will not be fixed in 57 per link

Chrome 57 grid bug

---

features-json/css-focus-within.json

https://www.chromestatus.com/feature/5363834508279808

css-focus-within: Add Chrome status ID

---

features-json/battery-status.json

https://webkit.org/status/#specification-battery-status-api

battery-status: Add WebKit status ID

---

features-json/css-font-rendering-controls.json

https://webkit.org/status/#specification-css-font-display

css-font-rendering-controls: Add WebKit status ID

---

features-json/deviceorientation.json

https://webkit.org/status/#specification-deviceorientation-events

deviceorientation: Add WebKit status ID

---

features-json/pointerlock.json

https://webkit.org/status/#specification-pointer-lock

pointerlock: Add WebKit status ID

---

features-json/midi.json

https://webkit.org/status/#feature-web-midi

midi: Add WebKit status ID

---

features-json/speech-recognition.json

https://platform-status.mozilla.org/#webspeech-recognition

speech-recognition: Add Firefox platform status ID

---

features-json/web-animation.json

https://platform-status.mozilla.org/#web-animations

web-animation: Add Firefox platform status ID

---

features-json/intersectionobserver.json

https://platform-status.mozilla.org/#intersection-observer

intersectionobserver: Add Firefox platform status ID

---

features-json/multicolumn.json

https://platform-status.mozilla.org/#css-multicol

multicolumn: Add Firefox platform status ID

---

features-json/css-motion-paths.json

https://platform-status.mozilla.org/#css-motion-path

css-motion-paths: Add Firefox platform status ID

---

features-json/css-initial-letter.json

* https://platform-status.mozilla.org/#css-initial-letter
* https://webkit.org/status/#feature-initial-letter

css-initial-letter: Add Firefox & WebKit IDs

---

features-json/flow-root.json

https://platform-status.mozilla.org/#css-display-flow-root

flow-root: Add Firefox platform status ID

---

features-json/css-backdrop-filter.json

https://platform-status.mozilla.org/#css-backdrop-filter

css-backdrop-filter: Add Firefox platform status ID

---

features-json/credential-management.json

https://platform-status.mozilla.org/#credential-management

credential-management: Add Mozilla platform status ID

---

features-json/css-resize.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssresize/

css-resize: Add Edge platform status ID

---

features-json/credential-management.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/credentialmanagementapi/

credential-management: Add Edge platform status ID

---

features-json/passive-event-listener.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/passiveeventlisteners/

passive-event-listener: Add Edge platform status ID

---

features-json/requestidlecallback.json

https://webkit.org/status/#feature-requestidlecallback

requestidlecallback: Add WebKit ID

---

features-json/once-event-listener.json

* https://www.chromestatus.com/feature/5630331130478592
* https://developer.microsoft.com/en-us/microsoft-edge/platform/status/eventlisteneronceoption/

once-event-listener: Add Chrome & Edge platform status IDs

---

features-json/payment-request.json

Apple has support for payments via apple pay.

Apple pay info

---

features-json/document-evaluate-xpath.json

https://wiki.whatwg.org/wiki/DOM_XPath

document-evaluate-xpath: Add WHATWG Wiki link

---

features-json/srcset.json

Add srcset bug in Edge 14 (issue #3262)

---

README.md

You might want to update this link too: ![](https://cloud.githubusercontent.com/assets/81942/24896541/b0655d86-1e95-11e7-8506-a8555af13ff7.png)

README: Use HTTPS where possible

---

features-json/calc.json

So I don’t have to jump back and forth between bullets when considering IE issues

Group IE bugs together

---

features-json/css-crisp-edges.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/imagerendering/

css-crisp-edges: Add Edge platform status ID

---

features-json/payment-request.json

Looks like you already had the info in notes. It wasn't labeled correctly

Apple's implementation already present in notes

---

features-json/battery-status.json

battery-status: Reflect removal from Firefox

---

features-json/css-case-insensitive.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/16910512-case-insensitive-attribute-selector-i-flag

css-case-insensitive: Add Edge UserVoice link

---

features-json/input-datetime.json

Fixed and released as per https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8810417/

Remove Edge bug which has since been fixed.

---

features-json/css-variables.json

Sorry, was annoying me a little :)

Correct Grammar

---

features-json/contentsecuritypolicy2.json

https://webkit.org/status/#specification-content-security-policy-level-2

contentsecuritypolicy2: Add WebKit ID

---

features-json/vibration.json

https://webkit.org/status/#feature-vibration-api

Vibration API: Add WebKit ID

---

features-json/css-clip-path.json

https://platform-status.mozilla.org/#css-clip-path

css-clip-path: Add Firefox ID

---

features-json/form-attribute.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/formattribute/

form-attribute: Add Edge ID

---

features-json/tls1-3.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/tls13/

tls1-3: Add MS Edge ID

---

features-json/css-deviceadaptation.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssdeviceadaptation/

css-deviceadaptation: Add Edge ID

---

features-json/ambient-light.json

See [Intent to Implement](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/TkfdVqYAYiE/xLGN2b1-AAAJ) and [Tracking Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=606766).

Ambient Light Sensor API is available in Chrome behind a flag

---

features-json/html5semantic.json

https://www.chromestatus.com/feature/5633937149788160

html5semantic: Add Chrome status for <time>

---

features-json/beforeafterprint.json

https://www.chromestatus.com/feature/5700595042222080

beforeafterprint: Add Chrome status ID

---

features-json/input-event.json

https://developer.microsoft.com/microsoft-edge/platform/issues/4660045/

input-event: Update Edge bug link to successor bug on successor tracker

---

features-json/css-grid.json

Includes Rachel Andrew's Grid by example site that has patterns, tutorials and more resources to understand this spec

Adds resource to css-grid entry

---

features-json/text-decoration.json

Fix Chrome incorrect full support of text-decoration-styling

---

features-json/text-decoration.json

Add status IDs for text-decoration-styling

---

features-json/link-rel-preload.json

https://developer.mozilla.org/en-US/Firefox/Releases/56

Firefox 56 will support preloading

---

features-json/css-grid.json

Added link to list of grid bugs from Rachel Andrew

Added link to Grid bugs

---

features-json/background-img-opts.json

There seemed to be other issues that are causing the laggy behaviour rather than this.
Previously I added this issue to the list based on my results on one of the projects, but it was not the case now.
Signed-off-by: Ru Chern Chong <me@ruchern.com>

Remove known issue for background-size property

---

features-json/web-share.json

* https://www.chromestatus.com/feature/5668769141620736
* https://webkit.org/status/#feature-web-share

web-share: Add platform statuses+bugs and update spec title & URL

---

features-json/unhandledrejection.json

https://www.chromestatus.com/feature/4805872211460096

unhandledrejection: Add Chrome platform status ID

---

features-json/css-placeholder.json

https://www.chromestatus.com/feature/6715780926275584

css-placeholder: Add Chrome platform status ID

---

features-json/xhr2.json

jUri is not a formdata polyfill at all

Fix the URL of the FormData polyfill

---

features-json/payment-request.json

https://webkit.org/status/#feature-payment-request

payment-request: Add WebKit feature status ID

---

features-json/dom-manip-convenience.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/domparentnodemethodsprependappendandchildnodemethodsbeforeafterandreplacewith

dom-manip-convenience: Add MS Edge platform status ID

---

features-json/media-fragments.json

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediafragments/

media-fragments: Add Edge platform status ID

---

features-json/input-file-directory.json

https://twitter.com/rmondello/status/915646869535121410

STP 41 enables webkitdirectory by default

---

features-json/beacon.json

Add bug description for sendBeacon

Bug with sendBeacon on Chrome

---

features-json/css-scrollbar.json

The user name has been changed.

Update the url of perfect-scrollbar

---

features-json/classlist.json

refs: https://github.com/Fyrd/caniuse/issues/3808
TODO:

WIP Add note for IE11 about assign to classList

---

features-json/viewport-units.json

Fixed small grammar mistake

---

features-json/streams.json

Changed the MDN link from a German version to an English one.

Update streams.json - MDN link

---

features-json/ac3-ec3.json
features-json/asmjs.json
features-json/aux-click.json
features-json/console-time.json
features-json/contentsecuritypolicy.json
features-json/css-appearance.json
features-json/css-canvas.json
features-json/css-grid.json
features-json/css-reflections.json
features-json/dommatrix.json
features-json/flow-root.json
features-json/font-smooth.json
features-json/hardwareconcurrency.json
features-json/let.json
features-json/proxy.json
features-json/rest-parameters.json
features-json/same-site-cookie-attribute.json
features-json/sql-storage.json
features-json/svg-filters.json
features-json/u2f.json
features-json/webgl.json

* Use English (US) spelling, just for the sake of consistency
* Adjust capitalisation of various words

Minor text fixes

---

features-json/video.json

Properly backtick item

---

features-json/css-any-link.json

* https://www.chromestatus.com/feature/5724922840088576
* https://webkit.org/status/#feature-css-selector-:any-link

css-any-link: Add Chrome & WebKit status IDs

---

features-json/hevc.json

Add h265 as Keyword

---

features-json/font-family-system-ui.json

https://www.chromestatus.com/feature/5640395337760768

font-family-system-ui: Add Chrome status ID

---

features-json/document-execcommand.json

https://w3c.github.io/editing/execCommand.html#execcommand()

document-execcommand: Update spec URL

---

features-json/css-logical-props.json

https://www.w3.org/TR/css-logical-1/
> W3C First Public Working Draft, 18 May 2017

CSS Logical Properties is a Working Draft

---

features-json/css-font-rendering-controls.json

https://www.w3.org/TR/css-fonts-4/#font-display-desc

font-display is part of CSS Fonts Module Level 4

---

features-json/http-live-streaming.json

https://tools.ietf.org/html/rfc8216
It has progressed beyond the Internet-Draft stage.

http-live-streaming is Informational RFC 8216

---

features-json/css-canvas.json

https://www.chromestatus.com/feature/5722125839106048

css-canvas: Add Chrome status ID for removal of feature

---

features-json/link-rel-preload.json

https://platform-status.mozilla.org/#link-rel-preload

link-rel-preload: Add Firefox Platform status ID

---

features-json/pointerlock.json

https://www.w3.org/TR/pointerlock/
> W3C Recommendation 27 October 2016

Pointer Lock 1 is a Recommendation

---

features-json/css-matches-pseudo.json

https://www.chromestatus.com/feature/5445716612743168

css-matches-pseudo: Add Chrome status ID

---

features-json/hevc.json

https://bugs.chromium.org/p/chromium/issues/detail?id=684382
> Feature request - HEVC support
> Status: WontFix

hevc: Add link to WontFix'd crbug

---

features-json/css-motion-paths.json

https://www.w3.org/TR/motion-1/
> W3C Working Draft, 11 July 2017

css-motion-paths is a Working Draft

---

features-json/link-rel-preload.json

as of 26 October 2017
https://www.w3.org/TR/preload/
(Also Edge 'in progress' but I guess you pull automatically from https://developer.microsoft.com/en-us/microsoft-edge/platform/status/preload/ )

Preload now a Candidate Recommendation

---

features-json/object-values.json

Fix spec link and status accordingly

Object.values is part of ES2017

---

features-json/intersectionobserver.json

"`isIntersecting` property of `IntersectionObserverEntry` was not implemented, returning `undefined`
test: https://codepen.io/anon/pen/qxrJgz

fixed intersectionobservet

---

features-json/css-shapes.json

1) add firefox support (partially and flagged)
2) fix description and keywords in accordance with spec level 1

css shapes fixes

---

features-json/css-focus-visible.json

Added Edge implementation suggestion for `:focus-visible`.

Added Edge implementation suggestion

---

features-json/netinfo.json

Hi there!
It looks like this is a typo.
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlinkMax

downlinkMax instead of downloadMax

---

features-json/datalist.json

Removed duplicate.
PS: what's a polypill? 😀

Removed duplicate link in "datalist element"

---

features-json/same-site-cookie-attribute.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17140412-support-samesite-cookie-option

Edge UserVoice link for SameSite cookie attribute

---

features-json/stream.json

Also, a link to a SO discussion about this.

Adding a bug for getUserMedia in iOS PWAs

---

features-json/feature-policy.json

Simplify search, people may specifically search for "`allow`"  + "attribute".

[Feature-Policy] Add "allow" to keywords

---

features-json/screen-orientation.json

See this that IE11 on Win7 do not support this

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/dn323733%28v%3dvs.85%29

---

features-json/feature-policy.json

Added link to the Firefox implementation ticket for 'Feature Policy'

Firefox implementation ticket for 'Feature Policy'

---

README.md

This reverts commit 2c541b1d2bf524033fd98ee24d63ad1a28952c48.

Revert "sd"

---

features-json/webvr.json

Might be good to rename webvr.json to webxr.json for search but unsure of the consequences.

Changes to WebXR

---

features-json/css-masks.json

As suggested in https://github.com/Fyrd/caniuse/issues/4474

[css-masks] Update resource blog post link

---

features-json/stream.json

This is VERY important for those who wants to create a PWA with camera access.
Sources: 
- https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app
- https://github.com/webrtc/samples/issues/933
Implementation: https://minhahavan.com

Added iOS notes about PWA and related

---

features-json/rtcpeerconnection.json

https://www.w3.org/blog/news/archives/7319

Update WebRTC status

---

CONTRIBUTING.md
package.json

Shorten command needed to validate JSON by moving to an npm script.

chore(npm-scripts): validate via npm script

---

features-json/es6-module-dynamic-import.json
features-json/es6-module.json

It's not dynamic import polyfill but static import polyfill

Move note about nomodule polyfill for Safari to the right place

---

features-json/css-nth-child-of.json

* add link to MS Edge platform status
* update spec to reflect published standard
Relates to #1058

update(css-nth-child-of): update spec status

---

features-json/bigint.json

Source: https://twitter.com/slsoftworks/status/1067455244144205824

Add link to firefox bug for BigInt

---

features-json/es6-module.json

Test page https://jg-testpage.github.io/es-modules/module-nomodule/simple.html
Result in Edge 17: 
Close #4662

es6-module: document issues with Edge

---

features-json/webauthn.json

source https://webkit.org/blog/8547/release-notes-for-safari-technology-preview-72/

Update STP web auth note.

---

features-json/css-scrollbar.json

Thank you soOoOoO much for this public utility ressource.

Fix #4752: typo in the word length

---

features-json/webp.json

Commit 4d4cd8aa3635aa70b22091bd4ce0b6c8f72a414f has duplicated several links, this commit removes them.

Removed duplicated links in data concerning WebP

---

features-json/webauthn.json

This guide is a good introduction to the feature

Add a link to webauthn.guide

---

features-json/fullscreen.json

Source: own experiments and
https://dev.to/delahoc/comment/7pfh
https://developer.apple.com/videos/play/wwdc2018/234/ at 33:35 min

fullscreen api working on ipad

---

features-json/input-search.json

https://stackoverflow.com/a/26287843/2074736

input-search: mention iOS not showing search button

---

CONTRIBUTING.md

HTTPS links in `CONTRIBUTING.md`

HTTPS relevant links to prevent redirects

---

features-json/mediasource.json

Source: https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_3_release_notes

Added note about support in iPadOS 13

---

features-json/picture-in-picture.json

Fix https://github.com/Fyrd/caniuse/issues/4855

Update picture-in-picture.json (Fix #4855)

---

features-json/css-animation.json
features-json/css-grid.json
features-json/css-snappoints.json
features-json/flexbox.json
features-json/html5semantic.json
features-json/media-fragments.json
features-json/multicolumn.json
features-json/svg.json
features-json/video.json
features-json/web-animation.json

Just went through and added keywords for the cases that didn't require too much thinking 😉
Closes #5057
Closes #5024
Closes #4896
Closes #4853
Closes #4588
Closes #4492
Closes #3942
Closes #3788
Closes #3701

Bulk add search results (keywords)

---

features-json/webauthn.json

WebAuthn has a flag available in iOS 13.2

---

features-json/fetch.json

"Bare minimum fetch polyfill in 500 bytes."
https://github.com/developit/unfetch

fetch: add unfetch polyfil

---

features-json/calc.json

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/59#CSS
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66#CSS

Update FF versions for CSS calc bugs

---

features-json/input-number.json

Previous wording of note 1 did not make it clear whether arrow up & down keys worked

Clarify note

---

features-json/loading-lazy-attr.json

The linked PR has been closed and has been integrated into the living standard.

Update loading attribute status

---

features-json/css-scrollbar.json

Dead links at: https://caniuse.com/#feat=css-scrollbar

Remove broken links from css-scrollbar.json

---

features-json/datauri.json

@Fyrd , what is the version used by the original author?
I have tested on Firefox 3.6 and Firefox 4, but I didn't try to find the bug in the https://bugzilla.mozilla.org ...

Some details about percent encoding in data URIs

---

features-json/publickeypinning.json

Some small updates to the notes now that the feature is pretty much completely unsuable.

Update notes on Public Key Pinning

---

features-json/contentsecuritypolicy2.json

https://www.w3.org/TR/CSP2/
Let's see if Travis fails on this one too 🙃

Content Policy Level 2 is now a W3C Recommendation

---

features-json/av1.json

Add Firefox & Chrome bug ID's to AV1 data

---

features-json/prefers-color-scheme.json

https://www.w3.org/TR/mediaqueries-5/#prefers-color-scheme

prefers-color-scheme is now a Working Draft

---

features-json/prefers-reduced-motion.json

https://www.w3.org/TR/mediaqueries-5/#prefers-reduced-motion

prefers-reduced-motion is now a Working Draft

---

features-json/wai-aria.json

CanIARIA? 😮 https://a11ysupport.io/

[WAI-ARIA] Add resource: https://a11ysupport.io/

---

features-json/feature-policy.json

Fix typo in feature-policy

---

features-json/viewport-units.json

Replacing CodePen link that doesn't work.

Added new CodePen link cause the current one won't load.

---

features-json/css-line-clamp.json

Not sure what to do with this strange property.  :-)
But deleting the old note seems to be best.
Feel free to edit to a better solution.

Adding spec to CSS line-clamp

---

features-json/page-transition-events.json

Added a note, resources, and tags regarding Back/Forward Cache on PageTransitionEvent.

Add more information on PageTransitionEvent

---

features-json/speech-recognition.json

STP 119 provides support for the SpeechRecognition API.

Adds SpeechRecognition API data for STP

---

features-json/css-image-set.json

CSS image-set: make link clickable

---

features-json/dialog.json

Dialog element: Inline code for note 1

---

features-json/import-maps.json

- https://bugzilla.mozilla.org/show_bug.cgi?id=1688879
- https://bugs.webkit.org/show_bug.cgi?id=220823
0:-)

Import maps: Add Firefox & WebKit feature request bugs + some backticks

---

features-json/css-cross-fade.json

- https://developer.mozilla.org/en-US/docs/Web/CSS/cross-fade()
- https://bugs.chromium.org/p/chromium/issues/detail?id=614906

CSS `cross-fade()`: Add links

---

features-json/speech-recognition.json

Fixes #5879.
… or do you want me to split the note, because it's getting lengthy?

Speech Recognition API: More info for Safari

---

features-json/http-live-streaming.json
features-json/mpeg-dash.json

Fixes #5905.
Per your comment there. Also improved the link for DASH to skip the redirect.

Add note to HLS

---

features-json/css-has.json

<https://chromestatus.com/feature/5794378545102848>
Via "Intent to Prototype" https://groups.google.com/a/chromium.org/g/blink-dev/c/hqkcKdDrhXE/m/qzEVzxbfAwAJ 🎉

`:has()` pseudo class: Add chrome_id

---

features-json/css-featurequeries.json
features-json/css-supports-api.json

Update links to new pattern for css-supports-api <> css-featurequeries

---

features-json/js-regexp-lookbehind.json

Link to " Implement RegExp lookbehind assertions " ticket

Add Safari ticket link

---

features-json/meta-theme-color.json

See https://twitter.com/quicksave2k/status/1376830182473015296 and https://chromiumdash.appspot.com/commit/eacbb32d64cb2c3e23e7a27c00ed969c942a84da

Update native `dark-mode` note in meta theme color

---

features-json/meta-theme-color.json

This CL adds some details to the `meta[name='theme-color']` feature following https://github.com/Fyrd/caniuse/pull/5939/

Added details

---

features-json/object-fit.json

Tx!
```
$ node validator/validate-jsons.js
✨  Done in 0.66s.
```

Object-fit: Remove duplicate link to MDN

---

features-json/extended-system-fonts.json

<https://bugs.chromium.org/p/chromium/issues/detail?id=1029069>
:)

Add Chromium support bug to extended-system-fonts

---

features-json/variable-fonts.json

HTTP was being redirected to HTTPS already, but even better this way.
Fixes #6021 :)

variable-fonts: Fix typo and upgrade to HTTPS

---

features-json/http3.json

Small adjustment to note regarding HTTP/3 in Safari

---

features-json/sharedarraybuffer.json

Updating two links in sharedarraybuffer.json

---

features-json/webvr.json

Add WebXR link to WebVR

---

features-json/ttf.json

- Fix TTF specification broken link
- Includes OTF specification link

Update specification links for TTF/OTF

---

features-json/css-scroll-timeline.json

- https://css-tricks.com/scroll-linked-animations-with-the-web-animations-api-waapi-and-scrolltimeline/
- https://bugzilla.mozilla.org/show_bug.cgi?id=1676780
- https://bugs.webkit.org/show_bug.cgi?id=222295
- https://github.com/flackr/scroll-timeline
:)

Add links to css-scroll-timeline

---

features-json/css-container-queries.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1744221
:)

Add Firefox support bug to CSS Container Queries

---

features-json/css-container-queries.json

CSS Containment Level 3 went to First Public Working Draft on 21 December 2021.

Container Queries is in Working Draft

---

features-json/meter.json

* Added links to segment boundary interoperability bug.
* Purged dead links.

[meter element] Interoperability issues

---

features-json/es6-module-dynamic-import.json

JavaScript modules: dynamic import() blog link update

---

features-json/webxr.json

https://www.w3.org/TR/webxr/
Became CR on March 31

Update WebXR status to CR

---

features-json/css-container-queries.json

Title, but for convenience: https://github.com/GoogleChromeLabs/container-query-polyfill :)

Add link to polyfill to Container Queries

---

features-json/colr-v1.json

:)
[https://mozilla.github.io/standards-positions/#font-colrv1](https://mozilla.github.io/standards-positions/#font-colrv1)

COLRv1: make mozilla position link clickable

---

features-json/css-overscroll-behavior.json

https://www.w3.org/TR/css-overscroll-1/

Overscroll behavior is in Working Draft

---

features-json/css3-tabsize.json

https://www.w3.org/TR/css-text-3

tab-size is in Text 3, which is in CR

---

features-json/css-container-query-units.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1744231
:)

Add Firefox support bug to Container Query Units

---

features-json/avif.json

Link to AV1 from AVIF

---

features-json/av1.json

Link to HEVC from AV1

---

features-json/css-lch-lab.json
features-json/css-rebeccapurple.json

- https://twitter.com/JoshTumath/status/1544235858592686081
- https://twitter.com/w3c/status/1544214340303216640
- https://www.w3.org/blog/news/archives/9603

CSS Color Module Level 4 is CR 🎉 

---

features-json/css-subgrid.json

https://chromestatus.com/feature/5663795354533888

Add `chrome_id` to Subgrid

---

features-json/variable-fonts.json

https://evilmartians.com/chronicles/the-joy-of-variable-fonts-getting-started-on-the-frontend

Add post to Variable fonts

---

features-json/css-content-visibility.json

https://bugs.webkit.org/show_bug.cgi?id=236238
:)

Add WebKit support bug to `content-visibility`

---

features-json/sql-storage.json

Basically everything via https://chromestatus.com/feature/5175124599767040 0:-)

Updates to Web SQL

---

features-json/heif.json

- https://bugs.webkit.org/show_bug.cgi?id=230035
- https://bugzilla.mozilla.org/show_bug.cgi?id=HEIF
:)

Add support bugs to HEIF and tiny touch up

---

features-json/css-snappoints.json

add scroll-snap-stop
[https://caniuse.com/?search=scroll-snap-stop](url)

property added

---

features-json/lazyload.json

Update link for Lazyload

---

features-json/font-size-adjust.json

https://bugs.webkit.org/show_bug.cgi?id=15257
:)

Add WebKit support bug to CSS font-size-adjust

---

features-json/declarative-shadow-dom.json

That’s pretty much it :octocat:

Add ponyfill link to Declarative Shadow DOM

---

features-json/url-scroll-to-text-fragment.json

- https://bugzilla.mozilla.org/show_bug.cgi?id=1753933
- https://twitter.com/jimniels/status/1585288076217442304 => https://blog.jim-nielsen.com/2022/scroll-to-text-fragments/

Add two links to Scroll-To-Text

---

features-json/loading-lazy-attr.json

https://bugs.webkit.org/show_bug.cgi?id=243601
https://twitter.com/styfle/status/1588612644961128448

Update lazy-loading-attr with Safari bug

---

features-json/native-filesystem-api.json

Add tags to File System Access API

---

features-json/css-nesting.json

Change CSS Nesting category to CSS

---

features-json/webtransport.json

https://github.com/WebKit/standards-positions/issues/18

Add link to WebKit position thread to WebTransport

---

features-json/css-media-range-syntax.json

Fixes https://github.com/Fyrd/caniuse/issues/6650.

Add tags to css-media-range-syntax for better findability

---

features-json/css-content-visibility.json

Courtesy of https://bugzilla.mozilla.org/show_bug.cgi?id=1791759.

Add Firefox support for content-visibility

---

features-json/alternate-stylesheet.json
features-json/async-functions.json
features-json/atob-btoa.json
features-json/css-element-function.json
features-json/css-filters.json
features-json/css-scrollbar.json
features-json/css-supports-api.json
features-json/css-text-justify.json
features-json/css-when-else.json
features-json/css3-boxsizing.json
features-json/fullscreen.json
features-json/html-media-capture.json
features-json/import-maps.json
features-json/pdf-viewer.json
features-json/pointer.json
features-json/spellcheck-attribute.json
features-json/sql-storage.json
features-json/svg-img.json
features-json/sxg.json
features-json/variable-fonts.json
features-json/x-doc-messaging.json

1. Get all the text
2. Put text into Grammarly
3. Keep the most obvious suggestions

fix grammar

---

features-json/selection-api.json

<https://caniuse.com/#feat=dom-range> => <https://caniuse.com/dom-range> 0:-)

Update URL in selection-api.json to new pattern

---

features-json/css-nesting.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1648037

Add experimental support for nesting in Firefox

---

features-json/pointer.json

Pointer Events also includes the `touch-action` CSS property
https://www.w3.org/TR/pointerevents/#the-touch-action-css-property

pointer: add CSS category

---

features-json/css-cascade-scope.json

From https://github.com/Fyrd/caniuse/issues/6056
- https://github.com/WebKit/standards-positions/issues/13
- https://fullystacked.net/posts/scope-in-css/

Add links to @scope

---

features-json/css-overflow-anchor.json

<https://bugs.webkit.org/show_bug.cgi?id=171099>

CSS overflow-anchor: Add WebKit support bug

---

features-json/css-media-interaction.json

Added chrome support bug to css-media-interaction section

---

features-json/av1.json

#6839
Updated only with known information

Edge has stopped supporting AV1 completely

---

features-json/srcset.json

as explained in https://github.com/vuejs/core/issues/6391.
Safari bug tracker: https://bugs.webkit.org/show_bug.cgi?id=190031

Indicate buggy Safari behaviour for srcset

---

features-json/indexeddb.json

I was struck today when looking up IndexDB that some of the language in the footnotes is quite emotional. This PR contains updates to simply make them a bit more factual and consistent. (No change to the information itself.)

Updating footnotes for indexeddb.json

---

features-json/css-overscroll-behavior.json

- Fixed link to draft spec — old link 404s
- Add link to MDN

Update links for css-overscroll-behavior

---

features-json/intersectionobserver-v2.json

- https://github.com/mozilla/standards-positions/issues/109
- https://bugs.webkit.org/show_bug.cgi?id=251586

Add two links to IntersectionObserver V2

---

features-json/css-hanging-punctuation.json

https://issues.chromium.org/issues/41491716
0:-)

Add Chrome support bug to hanging-punctuation

---

features-json/jpegxl.json

- https://github.com/mozilla/standards-positions/issues/522
- https://github.com/mozilla/standards-positions/pull/1064 🎉🤞🤞🤞

Add 2024 update and initial request for Mozilla Position on JPEG XL

---

features-json/link-icon-svg.json

Via https://github.com/web-platform-tests/interop/issues/745:
https://github.com/WebKit/standards-positions/issues/367

Add WebKit position 2024 to SVG favicons

---

features-json/eventsource.json

Firefox 133 supports EventSource in service workers

---

features-json/css-animation.json
features-json/css-masks.json
features-json/css-opacity.json
features-json/css-reflections.json
features-json/css-resize.json
features-json/css-transitions.json
features-json/pointer-events.json

I found 7 more CSS features that had missing MDN links, so I added them.
I thought it would be better to do this all as one pull request, rather than one pull for each small change.

Adding 7 more MDN links to CSS features

---

README.md

I was trying to programmatically use some data available on caniuse.com, but could not find it in the data.
Providing this link should help people find the data they need.

Mention that some data on caniuse.com is from browser-compat-data
