features-json/css-text-align-last.json

By [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last) data and @yisibl 
[investigation](https://github.com/postcss/autoprefixer/issues/372#issue-53359465).

Add text-align-last feature

---

features-json/xhr2.json

http://www.w3.org/TR/XMLHttpRequest2/:
>Work on this document has been discontinued and it should not be referenced or used as a basis for implementation. However, the Web Applications Working Group continues to work on XMLHttpRequest Level 1 and the WHATWG continues to work on XMLHttprequest.

Link to whatwg for the xhr spec

---

features-json/datalist.json
features-json/input-number.json

See [demo on codepen](http://codepen.io/graste/pen/bNoVKW) in Firefox and latest Opera/Chrome to see the difference. Firefox is missing autocomplete support or a dropdown select list.

add hint about missing datalist support for input type number in FF

---

features-json/border-radius.json

Prior to v5.1: Bug is probably present, but I don't have such old versions handy to test against.
Bug definitely present in: v5.1.9, v6.0.5
Bug probably present in v6.1, based on SO question's creation date.
Bug definitely absent as of: v7.0.6

Safari <img> border-radius bug fixed as of v7.0

---

features-json/css-hyphens.json
features-json/datalist.json
features-json/input-number.json

To make hyphenation work it is advisable to set the `lang` attribute on the HTML element as suggested [on quirksmode.org](http://www.quirksmode.org/blog/archives/2012/11/hyphenation_wor.html) and [adrianroselli.com](http://blog.adrianroselli.com/2015/01/on-use-of-lang-attribute.html).
```html
<html lang="en">
…
</html>
```

Note about the need for the lang attribute to make CSS hyphenation work

---

features-json/css-sticky.json

Spec published yesterday: http://www.w3.org/TR/2015/WD-css3-positioning-20150203/

Position:sticky is now "official", in WD

---

features-json/ruby.json

Ruby is enabled by default in Firefox 38.0:
https://bugzilla.mozilla.org/show_bug.cgi?id=1039006

Ruby enabled in Firefox 38.0

---

features-json/websockets.json

Firefox 37 beta can host WebSockets in a WebWorker context.

Updated Firefox compatibility note

---

features-json/webp.json

WebP is unofficial and not on any standards track. It is controlled by Google.

Make WebP unofficial

---

features-json/flexbox.json

IE11 will not apply flexbox on pseudo-elements
https://connect.microsoft.com/IE/feedbackdetail/view/1058330/ie11-will-not-apply-flexbox-on-pseudo-elements

Added an IE11 flexbox bug

---

features-json/calc.json

https://connect.microsoft.com/IE/feedback/details/814380/

IE10/11 don't support calc() in transform

---

features-json/mathml.json

I am not sure if this warrants downgrading support to partial as well. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math), firefox does not support the html5 notation for mathml until v 4

add notes for mathml on firefox

---

features-json/high-resolution-time.json

The High Resolution Time API has been found to enable a "Spy in the Sandbox" class of security vulnerability. Full PDF of security research paper is at http://arxiv.org/pdf/1502.07373v2.pdf
Also found an old Temp2 fork created last year by Fyrd containing Chrome and Opera about older versions of Chrome and Opera on Windows. Copied and pasted into this proposed update, then revised to "Some versions of ..."

Update bugs section of high-resolution-time.json

---

features-json/border-image.json

bug report - https://bugzilla.mozilla.org/show_bug.cgi?id=619500

firefox border-image bug

---

features-json/stream.json

There is site compat issues due to Blink supporting old version of spec that devs are coding to. Calling out difference here.
Not sure about older phones like Blackberry, but suspect they use old version of spec too.

Add note about Chrome using old version of spec

---

features-json/css-snappoints.json

In Firefox 39+, CSS Scroll Snap Points are enabled by default.

Scroll Snap Points enabled by default in Fx39+

---

features-json/dataset.json

(For more related links/history, see https://github.com/validator/validator/issues/98)

SVG2 will require support for data-* attrs on SVG elements

---

features-json/css-clip-path.json

The `clip-path` property is part of the CSS Masking Module Level 1.

css-clip-path is a subfeature of css-masks

---

features-json/css-variables.json

Hi!
I often looking for "custom properties" instead of "variables".
Perhaps we could add it to the keywords?
Cheers,
Thomas.

Add "custom properties" as keyword for CSS variables

---

features-json/calc.json

A number of CSS properties in Firefox do not support using the CSS
`calc()` inside of them. This commit adds the exceptions to the list of
known bugs for `calc()`. The related bug report can be found
[here](https://bugzilla.mozilla.org/show_bug.cgi?id=594933).

Added a list of unsupported `calc()` properties for Firefox

---

.editorconfig

Added an .editorconfig file to ensure editors adhere to the standards
used for JSON files. This is mostly to prevent contributors from
accidentally adding JSON indented with tabs or adding newlines to the
end of a file.

Added an .editorconfig file for consistent code style

---

features-json/link-icon-svg.json

(as long as the mime-type is correct)
[Bug 366324 - Resolved Fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=366324)
[HG Changeset](https://hg.mozilla.org/mozilla-central/rev/ed791601d8e7)

Firefox 41 supports SVG favicons better

---

features-json/cors.json

Early testing of iOS 9 is not hopeful either:
https://bugs.webkit.org/show_bug.cgi?id=135379

Safari still does not support CORS for <video> in <canvas>

---

features-json/contentsecuritypolicy.json

Opposite of commit 861c59c11b95aac856f7, since this was a bug rather than a case of partial support it seems like it should be removed now.
See https://code.google.com/p/chromium/issues/detail?id=396076 for more information.

Remove note about Chrome for iOS bug now that it has been resolved.

---

features-json/getboundingclientrect.json

According to https://twitter.com/jonathansampson/status/618943054746005504

getBoundingClientRect no longer throws in Edge

---

features-json/inline-block.json

I tried both of the obvious ways to interpret the note (http://jsfiddle.net/cvrebert/s4r6wo46/, http://jsfiddle.net/cvrebert/zps0oov9/), but neither of the testcases rendered unusually in OS X Safari 8.0.7. Otherwise, the note seems too unclear to be understood.

inline-block: Remove bunk Safari bug note

---

features-json/web-animation.json

It's linked to via the related blogposts, but this brings it front and center.

Add direct link to Web Animations polyfill

---

features-json/css-media-resolution.json

dpcm is supported, as per a previous pull request I made. The feature test fails as there is a bug (listed here) where values <1 don't fire. But in reality, as screens with less than 1dpcm don't exist, this isn't a bug you'd hit in the wild except for feature detects like this.

Changing dpcm back to yes again

---

features-json/link-icon-svg.json

Apple dropped non-standard `mask` attribute and now provide support for more issueless, non-standard `rel="mask-icon"`, so description and link update.

Update link-icon-svg.json to new Safari 9 note

---

features-json/pointer.json

touch can be enabled with flags, but only on Windows. https://hacks.mozilla.org/2015/08/pointer-events-now-in-firefox-nightly/ , https://wiki.mozilla.org/Gecko/Touch

Firefox only supports mouse input with pointer events.

---

features-json/input-email-tel-url.json

Everywhere else the data files use "(type=...)" and using percent-encoding actually breaks the HTML Standard. See https://github.com/whatwg/html-build/issues/6.

Correct URL of `<input type=tel>`

---

features-json/input-minlength.json

https://bugzilla.mozilla.org/show_bug.cgi?id=932755

input-minlength: Add link to Firefox bug

---

features-json/webm.json

http://dev.modern.ie/platform/status/webmcontainer/
Technically https://dev.modern.ie/platform/status/vp9videocodec/ is also relevant, but I don't think having multiple `ie_id`s is allowed.

webm: Add IE platform status ID

---

features-json/css-shapes.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1040714

css-shapes: Add link to Firefox tracking bug

---

features-json/css-snappoints.json

See failed tests on css3test (ignoring the properties no longer in the spec). Also failing tests on test.caniuse.com (but it isn't 100% clear to me if one value should be accepted for those properties or has to be two, so not left a note about those. Firefox passes the tests though.)

Safari should be partial for scrolling snap points

---

features-json/css-hyphens.json

https://www.fxsitecompat.com/en-US/docs/2015/hyphens-property-has-been-unprefixed/

Hyphens property unprefixed in Firefox 43

---

features-json/viewport-units.json

The [viewport-units](http://caniuse.com/#feat=viewport-units) page links to a [workaround](https://gist.github.com/pburtchaell/e702f441ba9b3f76f587) by Patrick Burtchaell for iOS issues.
I've created SCSS [mixins](https://gist.github.com/BenMorel/e9e34c08360ebbbd0634) based on his idea, that include a comprehensive list of iOS devices.
This basically allow you to support iOS 7 devices by just replacing:
height: 50vh;
with:
@include vh(50);
I thought it could be useful to link it on caniuse!

Add SCSS workaround for iOS issue in viewport-units

---

features-json/svg-fragment.json

Item could not be found by the terms `svg`, which is even in the title, or `use`, which is an important part of this functionality.
Added these terms in keywords.
Cheers!

Add more keywords to SVG fragment data

---

features-json/css-first-letter.json

Added this bug: [https://bugs.webkit.org/show_bug.cgi?id=6185](https://bugs.webkit.org/show_bug.cgi?id=6185)

Added bug description about selecting the text, styled with css ::first-letter pseudo-element

---

features-json/object-observe.json

https://bugzilla.mozilla.org/show_bug.cgi?id=800355

object-observe: Add link to relevant Firefox bug

---

features-json/fullscreen.json

Just ran into this today when trying to set a video full screen inside an already – fullscreen element.  God dammit, Safari, as if your full screen stretching animation isn't bad enough!
(╯°□°)╯︵ ┻━┻

Mention Safari's lack of fullscreen stacking in Full Screen API known issues

---

features-json/css-touch-action.json

WebPlatform Docs is much less active than MDN and has fizzled out, imho.

css-touch-action: WPD => MDN

---

features-json/upgradeinsecurerequests.json

https://bugs.webkit.org/show_bug.cgi?id=143653

upgradeinsecurerequests: Add link to WebKit bug

---

features-json/matchesselector.json

The links should point to the doc for the new feature.
The previous MDN link is redirecting to the new one, but the WebPlatform page shows a page describing the legacy feature.

Update the links for the matches() feature

---

features-json/details.json

When using the common box-sizing fix using "box-sizing: inherit;" on
details elements, children of the details element inherit a value of
"box-sizing: content-box;" even if the box-sizing value is explicitly
set to "box-sizing: border-box"

Added bug with details element and box-sizing in Chrome

---

features-json/input-number.json

Firefox 39 in Mac OSX by default does not prevent input alpha characters and Firefox 42 validates only but It doesn't disable alpha keys input.
https://jsfiddle.net/fht19Loe/1/

Firefox 39 and 42 don't prevent alpha chars input

---

features-json/multicolumn.json

``` html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
.wrap {
-webkit-column-count: 4;
-moz-column-count: 4;
column-count: 4;
width: 1000px;
}
.col {
break-inside: avoid;
page-break-inside: avoid;
-webkit-column-break-inside: avoid;
break-after: always;
page-break-after: always;
-webkit-column-break-after: always;
}
</style>
<title></title>
</head>
<body>
<div class="wrap">
<div class="col">
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa aaa</p>
<p>aaa aaa …
```

Firefox does not support break-* for column layout

---

features-json/css-media-interaction.json

The old one was marked as a duplicate.

css-media-interaction: Update to correct Firefox bug tracking link

---

features-json/text-size-adjust.json

The oldest Chrome I have access to is v26, which is affected by the bug. So I don't know how far further back the bug goes.
The bug was fixed in Chrome v27.
The oldest Safari I have access to is v5.1.7, which is affected by the bug. So I don't know how far further back the bug goes.
The bug is gone as of Safari v6.2.7. I don't have access to v6.0 or v6.1.
Testcase: https://bug-56543-attachments.webkit.org/attachment.cgi?id=86034
Bug: https://bugs.webkit.org/show_bug.cgi?id=56543

text-size-adjust: More details on old desktop WebKit bug

---

features-json/input-datetime.json

See https://github.com/whatwg/html/issues/336

Reflect the removal of <input type="datetime"> from HTML5

---

features-json/channel-messaging.json

https://www.w3.org/TR/webmessaging/ says
> Please look at http://w3c.github.io/webmessaging/ for the latest changes.
...which says
> No one in the Web Platform Working Group is actively working on the Web Messaging specification. For the latest version of the specification use the WHATWG Living Standard: Cross-document messaging and Channel messaging.

Change channel messaging to spec URL to whatwg

---

features-json/namevalue-storage.json

https://www.w3.org/TR/webstorage/
> Latest Editor's Draft:
> https://w3c.github.io/webstorage/
> The latest edits to Web Storage are maintained in https://html.spec.whatwg.org/multipage/webstorage.html.

Change storage spec URL to whatwg

---

features-json/websockets.json

> No one in the Web Platform Working Group is actively working on this specification. For the latest version of The WebSocket API use the WHATWG Living Standard.

Change websockets spec URL to whatwg

---

features-json/xhtml.json

Use a *somewhat* more up to date spec reference for XHTML.

Change xhtml spec URL to whatwg

---

features-json/eventsource.json

> No one in the Web Platform Working Group is actively working on this specification. For the latest version of Server-sent Events use the WHATWG's Living Standard.

Change server-sent events spec URL to whatwg

---

features-json/dom-range.json

Use a *somewhat* more up to date spec reference for DOM ranges.

Change DOM Range spec URL to whatwg

---

features-json/requestanimationframe.json

> Beware. This specification is no longer in active maintenance and the Web Performance Working Group does not intend to maintain it further. See HTML instead.

Change requestAnimationFrame spec URL to whatwg

---

features-json/queryselector.json

The W3C spec is not maintained.

Change querySelector spec URL to whatwg

---

features-json/cors.json

The W3C spec is not maintained.

Change CORS spec URL to whatwg

---

features-json/eventsource.json

I accidentally left in a slash in https://github.com/Fyrd/caniuse/pull/2239/files 

Fix typo in spec URL for eventsource

---

features-json/indexeddb.json

Looks like the URL may have changed.  The old one was a 404.

Fix reference link for IndexedDB

---

features-json/css-placeholder-shown.json

Refs #2259.
Testcase: https://jsfiddle.net/38t99yg3/1/
It seems likely that it should work in some version of iOS Safari too (probably 9.3), but I don't have the beta or time to test more.

css-placeholder-shown: Supported in OS X Safari 9

---

features-json/css-gradients.json

Hi.
I added an issue for linear-gradient and IE10.
Here is a [bug demonstration](https://jsfiddle.net/tzi/1xmjdwmj/)
Cheers,
Thomas.

Add issue for IE10: viewport unit for color-stop position

---

features-json/contentsecuritypolicy2.json

This is on the IE roadmap now: https://dev.windows.com/en-us/microsoft-edge/platform/status/contentsecuritypolicylevel2
Thanks!

Link platform status for CSP2.

---

features-json/link-rel-preconnect.json

This feature is now tracked by Microsoft on https://dev.windows.com/en-us/microsoft-edge/platform/status/preconnectresourcehints (Under Consideration)

Add ie_id for Resource Hints Preconnect

---

features-json/arrow-functions.json
features-json/es5.json
features-json/es6-number.json
features-json/json.json
features-json/promises.json
features-json/use-strict.json

Some of "spec" urls of ECMAScript entries are inconsistent or outdated.
This PR normalises "spec" urls of ECMAScript entries.
More specifically, it makes all "spec" urls reference official spec either
- http://www.ecma-international.org/ecma-262/5.1/
- http://www.ecma-international.org/ecma-262/6.0/

Normalize ECMAScript "spec" url

---

features-json/client-hints-dpr-width-viewport.json
features-json/datauri.json
features-json/opus.json
features-json/sni.json
features-json/stricttransportsecurity.json

Some of "spec" urls of IETF entries are inconsistent.
This PR normalises "spec" urls of IETF entries.
More specifically, it makes all "spec" urls reference html version
- https://tools.ietf.org/html/

Normalise IETF "spec" url 

---

features-json/console-basic.json

This PR also adds Edge/Internet Explorer console reference to links

Make console-basic reference Console Standard

---

features-json/input-file-accept.json

As developers.whatwg.org provides a subset of HTML Standard, caniuse should refer full version of HTML Standard.

Use canonical spec url for input[accept]

---

features-json/menu.json

[About popup type in Chrome](http://stackoverflow.com/a/28858365/1267803)
About nested menus in Firefox for Android:
1. go to http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_menuitem
2. hold pressed inside the yellow box <-- the context menu appears
3. press "Share on..." <-- the sub menu does not appear

menu: +popup type in Chrome 41 to 47, +partial support in Firefox for Android

---

features-json/xhr2.json

In Internet Explorer the `timeout` property may only be set after calling `open` and before calling `send`. Chrome and Firefox each support setting `timeout` before `open` and after `send`.

XHR: add issue about setting timeout in IE

---

features-json/dragndrop.json

See https://bugs.webkit.org/show_bug.cgi?id=103423

dragndrop: Safari doesn't implement the DragEvent interface

---

features-json/css-matches-pseudo.json

https://bugs.chromium.org/p/chromium/issues/detail?id=568705

css-matches-pseudo: Add link to Chrome bug

---

features-json/pointer-events.json

Extended known bug  for link elements.

Updated known bugs

---

features-json/background-position-x-y.json

Many people don't realise that background-position-x/y is achievable in Firefox, so I thought I'd add a note and some self-promotion by linking to one of my Stack Overflow answers from a while ago.  If that's an issue, feel free to remove it but I think it's helpful in any case.

Firefox workaround for no background-position-x/y

---

CONTRIBUTING.md

The name of the repo has been changed to `platform-status` and the new home is https://platform-status.mozilla.org/.

Update Mozilla Platform Status URLs

---

features-json/proxy.json

https://webkit.org/status/#feature-proxy-objects

proxy: Add WebKit platform status ID

---

features-json/woff2.json

https://webkit.org/status/#specification-woff-file-format-2.0

woff2: Add WebKit platform status ID

---

features-json/http2.json

https://platform-status.mozilla.org/#http2

http2: Add Firefox platform status ID

---

features-json/css-read-only-write.json

https://bugzilla.mozilla.org/show_bug.cgi?id=312971

css-read-only-write: Add link to relevant Firefox bug

---

features-json/css-optional-pseudo.json

Make :optional a subfeature of form-validation since form-validation includes :required

---

features-json/css-masks.json

The current one is about implementing only, the new one about implementing and shipping (Meta bug)

Use correct Firefox bug for CSS masks

---

features-json/history.json

The known issue with the popstate event not being fired when the hash changes affects Edge as well as IE. The official public-facing bug report has a new URL.

Update "known issue"

---

features-json/background-position-x-y.json

The [issue on Firefox Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=550426) just got marked as resolved.

Firefox 49 supports background-position-x/y

---

features-json/notifications.json

In Windows 10 Preview Build 14342, Web Notifications API is enabled by default in Edge 14.
https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/14342/

Web notifications is enabled by default by Edge 14

---

features-json/fetch.json

See https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/14342/

Fetch is enabled by default by Edge 14

---

features-json/style-scoped.json

See https://github.com/whatwg/html/issues/552.

<style scoped> was removed from WHATWG HTML

---

features-json/upgradeinsecurerequests.json

Upgrade Insecure Requests is now a W3C Candidate Recommendation.
https://www.w3.org/TR/upgrade-insecure-requests/

upgrade insecure requests status to cr

---

features-json/contentsecuritypolicy2.json

taken from here: https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Browser_compatibility

child-src support was added in FF 45

---

features-json/flexbox.json

IE11 requires a unit to be added to the 'flex-basis' attribute and to the third argument to the 'flex' attribute.

Added note about IE11 flex-basis bug.

---

features-json/input-event.json

Both of Firefox's `input` event bugs are fixed in Firefox 49:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1024350
* https://bugzilla.mozilla.org/show_bug.cgi?id=1206616

Firefox 49 fixes Firefox's input event bugs

---

features-json/http2.json

Chrome 51 only supports HTTP/2 over ALPN. There are many sources that state that, even nginx blogged about it: https://www.nginx.com/blog/supporting-http2-google-chrome-users/

Added not for HTTP2 ALPN requirement

---

features-json/flexbox.json

`Initial` value in the latest [spec definition](https://www.w3.org/TR/css-flexbox-1/#flex-property) for `flex` property is `1 0 auto` not `0 1 auto`.

Flexbox: fixed spec definition of `flex` property

---

features-json/flexbox.json

**Before** (broken link)
- IE 11 requires a unit to be added to the third argument, the flex-basis property [see MSFT documentation](https://msdn.microsoft.com/en-us/library/dn254946\(v=vs.85).aspx)
**After**
- IE 11 requires a unit to be added to the third argument, the flex-basis property [see MSFT documentation](https://msdn.microsoft.com/en-us/library/dn254946\(v=vs.85\).aspx)

Fix flex-basis MSFT documentation URL

---

features-json/link-icon-svg.json

For some reason the link to pinned tabs on Apple's developer website resulted in a 404. I corrected the link to pinned tabs so that it goes to the corresponding category on Apple's website

Fix link to pinned tabs

---

features-json/flexbox.json

* Removes child element focusing, testcase appears the same across all browsers.
* Removes pseudo-element as linked bug claims a fix.
* Removes long paragraph wrapping as test case renders like .top "flex-direction: row" and that works.
* Moves two height elements together as they appear to be the same issue.

IE11 review

---

features-json/css3-cursors.json

All versions of Edge support cursor: url() just like IE did http://samples.msdn.microsoft.com/workshop/samples/author/dhtml/refs/cursor_a.htm (second format has been dropped, presumably because other browsers don't support it.)

Edge 14 has added `none` back. cursor: url() never went away

---

features-json/css-placeholder.json

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1069012

css-placeholder: Add link to Firefox unprefixing bug

---

features-json/chacha20-poly1305.json

ChaCha20-Poly1305 is now [RFC7905](https://tools.ietf.org/html/rfc7905). Also when will this feature be displayed on the website?

[ChaCha20-Poly1305.json] Update spec link

---

features-json/css-clip-path.json

It has been fixed 9 months ago https://code.google.com/p/chromium/issues/detail?id=350724

css-clip-path: Removed fixed bug in chrome

---

features-json/flexbox.json

Initial value of `flex` is `0 1 auto` as per [Flexbox Spec](https://www.w3.org/TR/css-flexbox/#flex-initial).

Corrected IE10 issue description

---

features-json/css-animation.json

Narrower definition of IE10/11 css animations in media query bug

---

features-json/custom-elements.json

Custom Elements v0 [was](https://github.com/w3c/webcomponents/pull/405#issuecomment-191698136) superseded by [Custom Elements v1](https://developers.google.com/web/fundamentals/primers/customelements/#historysupport).

v0 -> v1 update

---

features-json/form-validation.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1285425

form-validation: Firefox's form:valid bug is fixed in version 51

---

features-json/calc.json

The original issue at [connect.microsoft.com](https://connect.microsoft.com/IE/feedback/details/814380/) provided a dead link in the comments, and I'm unable to post clarification at that url. The updated issue is at [developer.microsoft.com](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/104773).
I specified `Edge < 14` in the notes as well, as I was able to reproduce up to v13 but not in v14.
For anyone happening across this PR looking for a fix for those older versions, [here's a fix for simple cases](https://stackoverflow.com/questions/21142923/ie-10-11-css-transitions-with-calc-do-not-work/21381301#21381301).

Update calc bug link on IE / Edge

---

features-json/css-touch-action.json

The `touch-action` support in Safari is limited to one out of four properties (not counting the default `auto`). The other properties are just as relevant such that I would recommend treating the support for touch-action as partial.

touch-action property support is limited in Safari

---

features-json/css-placeholder-shown.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/12435951--placeholder-shown-css-pseudo-class

css-placeholder-shown: Add MS Edge UserVoice link

---

features-json/svg-html.json

This fixes the JSON syntax error in #2515 and uses a numbered note.

#2515 with fixups applied

---

features-json/innertext.json
features-json/textcontent.json

See https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute

Node.innerText has been standardized in HTML

---

features-json/text-stroke.json

-webkit-text-stroke is in development by Edge. https://github.com/MicrosoftEdge/Status/pull/461

Add ie_id for CSS text-stroke

---

features-json/user-timing.json

https://webkit.org/status/#specification-user-timing

user-timing: Add WebKit ID

---

features-json/css-case-insensitive.json

* https://webkit.org/status/#feature-case-insensitive-attribute-selectors

css-case-insensitive: Add WebKit ID

---

features-json/currentcolor.json

The previous link points to a page marking the bug as closed because of the migration of Edge issues to their new dedicated issue tracker. This updates the link to point to the new issue tracker instead.

Update the link to the Edge bug for currentColor

---

features-json/custom-elements.json
features-json/custom-elementsv1.json

The following link is currently broken: https://github.com/webcomponents/webcomponentsjs/tree/v1/src/CustomElements/v1
I found it when searching for Custom elements on [CanIUse](http://caniuse.com/#search=custom%20elements) (`Resources`: "customElements.define polyfill (supersedes document.registerElement)")
I replaced it with a new link to the current folder of the polyfill: https://github.com/webcomponents/webcomponentsjs/tree/v1/src/WebComponents
It might be a good idea to remove this link altogether though or just link to the Github repository itself instead of a folder in the tree (or a branch) as this is most likely going to break again in the future.
Let me know if I should remove the link from the list

Fixed link for customElements github polyfill

---

features-json/xml-serializer.json

There is no `.adjacentHTML` property/method. Presumably `.insertAdjacentHTML()` was intended.
Also retitle link to Resig's article, which deletes an "insertAdjucentHTML" [sic] typo.

xml-serializer: Fix typos

---

features-json/css-grid.json
features-json/custom-elementsv1.json
features-json/gamepad.json
features-json/webgl2.json

As discussed in #2851.
With the addition of <http://caniuse.com/#feat=gamepad>, which I missed there.

Adjust "Experimental Features" in Safari TP

---

features-json/upgradeinsecurerequests.json

Allow searching for `upgradeinsecurerequests` as `upgrade-insecure-requests` since that's the name that's actually used in the CSP header.

upgradeinsecurerequests: add upgrade-insecure-requests alias

---

features-json/input-file-accept.json

^
Clickable link: <https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13661175-full-spec-support-for-accept-in-input-type-file>

Add Edge request for input type file accept attr

---

features-json/selection-api.json

There a was a typo on the selectionchange event.
It's selectionchange and not selectionchanged.
[see mdn documentation for the selectionchange event here](https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange)

data update for selection API

---

features-json/css-fixed.json

CSS transforms and margin:auto are ignored on position:fixed elements in Android 4.0-4.3.
Example: https://codepen.io/mattiacci/pen/mPRKZY
Note: Couldn't find a way to test Android 3, so not sure about compatibility there.

position:fixed partially supported in Android 4.0-4.3

---

features-json/multicolumn.json

Prefixed CSS3 multi-column properties will be removed:
https://www.fxsitecompat.com/en-CA/docs/2016/prefixed-css3-multi-column-properties-will-be-removed/
It is implemented as of October 12 Nightlies.

Fx49 supports Multiple column without prefix

---

features-json/speech-recognition.json

It's kind of disappointing when after enabling the flag, it still doesn't work. For reference see the FF footnote to the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

Clarify speech recognition support in FF

---

features-json/css-animation.json

When animating a pseudo element, IE10 and IE11 will not fire the relevant Animation Events

Added animation event bug for IE10/IE11

---

features-json/svg-html.json

Due to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6618695/
Fixes #2333

Mark svg-html as partially supported on IE and Edge.

---

features-json/font-loading.json

Safari 10 reportedly shipped the feature

font-loading.json: removed webkit's "in progress"

---

features-json/canvas.json

http://www.canvasdemos.com/ appears to be a dead URL, not sure if it has moved or not

Remove dead URL

---

.travis.yml

This is related to issue #2981 , I think it's good practice to test multiple Node versions, not just `0.6`. The issue could have been avoided. I've added Node versions 4, 5, and 6 to the Travis build file.

Add multiple Node versions to Travis CI build

---

features-json/css-font-rendering-controls.json

Support for `font-rendering` was added to Firefox 46, available by enabling a flag. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1157064. 
(Future full support is being worked on at this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1317445)

correct information about `font-rendering` in Firefox

---

features-json/custom-elementsv1.json

The ie_id already generates the same link, just with a different title.

custom-elementsv1: Remove duplicate Edge status link

---

features-json/flexbox.json

https://bugzilla.mozilla.org/show_bug.cgi?id=984869 got fixed :smile: 
I checked with Firefox Aurora (v52) and the demo page http://codepen.io/philipwalton/pen/ByZgpW.
I can confirm this definitely got fixed.

Flexbox bug in Firefox got fixed

---

features-json/intersectionobserver.json

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1243846#c90
Refs https://hg.mozilla.org/releases/mozilla-aurora/rev/6ae9b39276fa#l3.32

IntersectionObserver disabled behind a pref in Firefox

---

features-json/nav-timing.json

According to https://www.w3.org/TR/navigation-timing/#sec-navigation-timing the NavigationTiming values are all longs -- MDN says these are "number of milliseconds since the Unix epoch." So unlike the High Resolution Time API (`window.performance.now()`), these are _supposed_ to be integer numbers of milliseconds. This bug description implies that Chrome on Windows is not following the spec, but millisecond resolution would seem to be correct.

Remove confusing bug text from nav-timing.json

---

features-json/css-initial-letter.json

I included two links to the Bugzilla ticket for implementing Initial Letter in Firefox — only one of them points to CSS Shapes. Wooops! This commit should fix that.

Initial Letter page — Fixing broken link to Bugzilla

---

features-json/css-logical-props.json

These properties are defined by the spec: https://drafts.csswg.org/css-logical-props/#index-defined-here
Refs #3051

Add block-size & inline-size to search keywords

---

features-json/css-grid.json

Safari Technical Preview now ships with CSS Grid on by default. So the box should be green. I'm not sure whether you want to leave the note about how to toggle it on and off (since those folks who installed Safari TP in the past will need to toggle it on) or not. I've included two pull requests — commit both to keep the note. Or just the first to remove the note.

Update CSS Grid with Safari TP support

---

features-json/transforms2d.json

No version of IE/Edge supports CSS transforms on SVG elements. Moved notice from "Known issues" to "Notes" in the same way it's done on http://caniuse.com/#feat=svg-html5
Resources:
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8713749/

IE/Edge: No CSS transforms on SVG elements

---

features-json/payment-request.json

It currently links to the Credential Management API page

Fix mdn link in payment request api

---

features-json/css-sticky.json

adds a resource that shows examples of the kinds of things you can build with `position:sticky`, as well as gotchas you need to watch out for (like sticky sibling elements, `position: absolute` children, etc)

css-sticky.json: add examples & gotchas article

---

features-json/xhr2.json

`FormData` are not working properly on IE10/11, when there is unchecked
checkbox at the end of form.

XHR2 - FormData corrupted IE10/11

---

features-json/wasm.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/11423808-add-support-for-web-assembly-as-early-as-possible

wasm is available behind a flag in Edge 15

---

features-json/wasm.json

wasm [was disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1342440) in ESR build of Firefox 52

add note about wasm in Firefox 52 ESR

---

features-json/css-masks.json

Android webkit-based stock browsers do not support the `mask-box-image` longhand properties like `-webkit-mask-box-image-outset`.
Tested via browserstack and Genymotion VM using feature detection.
See CI log: https://travis-ci.org/cssinjs/css-vendor/builds/205736604#L388

Android browser lack mask-box-image longhand props

---

features-json/flexbox.json

Old firefox versions do not support the align-content property.
See our CI log: https://travis-ci.org/cssinjs/css-vendor/builds/205736604#L462

Former firefox does not support align-content

---

features-json/css-snappoints.json

Document IE & Edge versions not supporting the `scroll-snap-coordinate` and `scroll-snap-destination` from the old spec.

IE & Edge don't fully implement old snappoints spec

---

features-json/speech-synthesis.json

Chrome stops playback after about 15 seconds since version 55 on some platforms, including at least: Windows 7 & 10, Ubuntu 14.04.

Adding bug/note for Chrome 55+ not fully working

---

features-json/css-regions.json

Document the fact that IE & Edge do not support `region-fragment`.

IE & Edge do not support region-fragment

---

features-json/addeventlistener.json

See the commit in the related repo:
https://github.com/Financial-Times/polyfill-service/commit/991ee5503da4a16fb13e53c32be7f4dc407b76fd

Update links for addeventlistener

---

features-json/es6-module.json

Ref: https://blog.hospodarets.com/native-ecmascript-modules-the-first-overview#enabling-es-modules-in-firefox

Firefox 54+ supports ES6 Modules behind a flag

---

features-json/multicolumn.json

Safari 5.1-10+ has a bug where setting `min-height` on an element with css columns will clip the contents to that min-height.
[test case](https://codepen.io/herrschuessler/pen/LNVWJE)
[bug report](https://bugs.webkit.org/show_bug.cgi?id=65691)

Add note for Safari bug to multicolumn.json

---

features-json/web-app-manifest.json

Webkit currently has this listed as "Under Consideration"

Web manifest: link to Webkit status page

---

features-json/beacon.json

https://webkit.org/status/#specification-beacon-api

beacon: Add WebKit status ID

---

features-json/css-focus-within.json

https://webkit.org/status/#feature-css-selector-:focus-within

css-focus-within: Add WebKit status ID

---

features-json/textencoder.json

https://webkit.org/status/#specification-encoding

textencoder: Add WebKit status ID

---

features-json/nav-timing.json

https://webkit.org/status/#specification-navigation-timing-level-1

nav-timing: Add WebKit status ID

---

features-json/upgradeinsecurerequests.json

https://webkit.org/status/#feature-upgrade-insecure-requests

upgradeinsecurerequests: Add WebKit status ID

---

features-json/audio-api.json

https://webkit.org/status/#feature-web-audio

audio-api: Add WebKit status ID

---

features-json/web-bluetooth.json

https://webkit.org/status/#feature-web-bluetooth

web-bluetooth: Add WebKit feature ID

---

features-json/css-touch-action-2.json

Two changes:
- Chrome 56 for Android has full support like Chrome 56 for desktop (see [chrome status](https://www.chromestatus.com/feature/5670200775016448))
- Chrome 59 dev resolves the outstanding bug for Chrome (see https://github.com/w3c/pointerevents/issues/166#issuecomment-286482230)

Update touch-action level 2 compatibility data for Chrome

---

features-json/push-api.json

https://developer.apple.com/notifications/safari-push-notifications/
https://appadvice.com/appnn/2013/09/apple-to-enable-ios-inspired-safari-push-notifications-for-developers-in-os-x-mavericks

Safari Custom Push notification support

---

features-json/iframe-seamless.json

- restore link to spec that actually contained a reference to this attribute (changed in 719ee06c3)
- add link to the removal from the W3C version of the HTML5 spec
- include status for Firefox bug
- add Edge UserVoice official response (updated 2017-04-04)

iframe-seamless: various link fixes

---

features-json/css-touch-action.json

Added a note about not all Firefox platforms supporting pointer events or touch events, rendering touch-action support moot (eg Windows without APZ, Mac OS).

touch-action note for Firefox 52+

---

features-json/intersectionobserver.json

Updates Edge15 to full support (from partial). This was added in 14986 (Edge15 is 15063)
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/intersectionobserver/

Update intersectionobserver.json for Edge15 capability

---

features-json/css-focus-within.json

Per https://www.chromestatus.com/feature/5363834508279808, :focus-within is behind a flag in upcoming Chrome/Opera.

Update Chrome and Opera support of :focus-within

---

features-json/css-text-justify.json

Firefox supports text-justify property with values: auto | none | inter-word | inter-character | distribute (with the exact same meaning and behavior as "inter-character" for legacy reasons) from Firefox 54 (under layout.css.text-justify.enabled pref off) [1]. text-justify will be pref-on from  Firefox 55 [2]. 
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=276079
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1343512

Update Firefox support for text-justify

---

features-json/background-repeat-round-space.json

This feature refers to the 'round' and 'space' keyword values of the 'background-repeat' property,
but the spec link was for the 'background-position' property instead.
(Found when checking the data for https://github.com/w3c/csswg-drafts/issues/1219)

background-repeat-round-space: Fix spec link

---

features-json/css-image-set.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1107646

css-image-set: Add Firefox bug link

---

features-json/css-crisp-edges.json

https://bugzilla.mozilla.org/show_bug.cgi?id=856337

css-crisp-edges: Add link to Firefox & Chrome bugs

---

features-json/css-cross-fade.json

https://bugzilla.mozilla.org/show_bug.cgi?id=546052

css-cross-fade: Add link to Firefox bug

---

features-json/css-hyphens.json

https://www.w3.org/TR/css-text-3/#hyphenation does not define any CSS properties itself, but contains 2 subsections that do:
* https://www.w3.org/TR/css-text-3/#hyphens-property
* https://www.w3.org/TR/css-text-3/#overflow-wrap-property
The latter is already covered separately as http://caniuse.com/#feat=wordwrap
So switch to the specific subsection for the "hyphens" property for precision.

css-hyphens: Fix spec link

---

features-json/rem.json

The original link was for the entire font-relative lengths section (which also includes the em, ex, and ch units, some of which even have their own caniuse entries).
The new link is for the rem unit specifically, for precision.

rem: Use more precise spec link

---

features-json/css-initial-value.json

A. The original link was to a general "common keywords" section which also covers 'inherit' and 'unset'.
B. As you'll find if you click the hyperlinked mentions of 'initial' in the section from the original link, CSS technically considers CSS Cascade rather than CSS Values & Units to the be spec that defines 'initial'.
(The `status` field remains unchanged since Cascade Level 4 is also a Candidate Recommendation.)

css-initial-value: Fix spec link

---

features-json/css-grid.json

I didn't add the note to all previous versions, but the bugs are probably there too.

css-grid: mention Firefox bugs fixed in 54

---

features-json/websockets.json

Support for hosting WebSockets in WebWorkers did indeed arrive in Firefox 38, so unneeded wording can be removed.

Remove unnecessary "guess"

---

features-json/aux-click.json

auxclick is now on a standards track, see https://github.com/w3c/uievents/issues/107

Update auxclick spec location

---

features-json/template-literals.json

Seems to make more sense there than in JS APIs.

Move ES6 Template Literals to the JS category.

---

features-json/css-variables.json

I've just tried to implement `css variables` but looks like in Edge it's still not ready to be used. There are critical bugs. So I made correction to partial support - it's my first contrib to this repo so please check if it's everything in correct format.
Edge bugs: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=css%20variables

Updated Edge15 "css variables" - bugs

---

features-json/srcset.json

Unfortunately, the srcset bug (discussed in PR #3263) is also present in Edge 15. Confirmed by Microsoft, amending the original [bug report](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7778808/). (I have also personally verified the bug's existence.)

Extend srcset bug to Edge 15

---

features-json/push-api.json
features-json/serviceworkers.json

https://www.fxsitecompat.com/en-CA/docs/2016/service-workers-have-been-disabled-in-firefox-45-esr/
https://www.fxsitecompat.com/en-CA/docs/2017/service-workers-and-push-notifications-are-disabled-on-firefox-52-esr/

Document disabled Service Workers/Push API on Firefox 45/52 ESR

---

features-json/keyboardevent-key.json

Fixed #3468.
I don't know how to test these modifications (except running `validate-jsons.js`), but hopefully this is the correct syntax. :)

IE and Edge don't follow the KeyboardEvent.key specification

---

features-json/background-img-opts.json

Check here for current browser support:
https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip

Background-clip: text support

---

features-json/payment-request.json

Payment Request is supported and on by default in Edge 15+. The "preliminary implementation" note here appears to come from an Edge changelog note which was specifically referring to an Edge 15 preview build. The stable release has a complete implementation. See https://aka.ms/devguide_edgehtml_15 for details.

Correcting Edge status for Payment Request

---

features-json/style-scoped.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1291515

style-scoped: Disabled in Firefox 56+

---

features-json/datauri.json

IE Edge 14 doesn't support SVGs with XML declarations in data-uris.
Works in IE 11 and in Edge 15. I am unable to test Edge 12 and 13.
Screenshots:
https://www.browserstack.com/screenshots/1ec164d16c5fffe93b88699b21158d1f618fff02
Codepen:
https://codepen.io/malthejorgensen/full/MooKQe/

data-uri: Edge 14 doesn't support SVGs with XML declarations

---

features-json/resizeobserver.json

https://bugs.webkit.org/show_bug.cgi?id=157743

resizeobserver: Add WebKit feature bug

---

features-json/internationalization.json

The current tracking bug is resolved fixed, but the Intl API is currently disabled for the release build. The bug to enable it on release builds it 1344625

Update FF Android tracking bug

---

features-json/css-image-set.json

It's been punted from Level 3 to Level 4 per
https://github.com/w3c/csswg-drafts/commit/af2c881a88920c9f83b90ebda5b36688440c6c18

css-image-set: Update spec link

---

features-json/brotli.json

Per <https://developer.apple.com/library/content/releasenotes/Foundation/RN-Foundation/index.html>
> For binary compatibility reasons, URLSession brotli support is enabled only for apps linked against the macOS 10.13 / iOS 11 SDKs and later.
and Safari Technology Preview was missing from the initial PR.
---
I didn't add the note to iOS Safari 11, like at <https://caniuse.com/#feat=heif>, because I don't think that makes sense, as iOS Safari 11 is only available on iOS 11 unlike  macOS Safari which is available for multiple versions of macOS.
Should I change the note from HEIF?
Also I don't think marking partial support for macOS Safari makes sense, like at <https://caniuse.com/#feat=woff2>. I could change that too, keeping the note of course, if you like?
But what do you think in general? …

Brotli in STP too & add note about from macOS High Sierra

---

features-json/namevalue-storage.json

Per <https://webkit.org/blog/7532/release-notes-for-safari-technology-preview-29/>
> Fixed QuotaExceededError when saving to localStorage in private browsing mode or WebDriver sessions
or more precise <https://bugs.webkit.org/show_bug.cgi?id=157010#c18>
> Per discussion with Brady, the fix will be to make localStorage in-memory for ephemeral sessions. This means that in private browsing and automation (i.e., WebDriver), we'll allow read/write and the contents do not persist.
EDIT: I also compared the behavior using <http://dev-test.nemikor.com/web-storage/support-test/> with iOS 10.3.2 vs iOS 11 beta 2, or rather the corresponding Safari.
---
Additionally 
1. I highly doubt that 
>  do not support setting sessionStorage
was ever correct for Safari, or at least isn't anymore since multiple …

Safari 11+ supports localStorage in private mode

---

features-json/css-grid.json

Per <https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16237/>
> Unprefixed CSS Grid is now enabled by default
🎉

CSS Grid is now enabled by default in Edge

---

features-json/hardwareconcurrency.json
features-json/xhtml.json

These IDs also appear in the developer's edition of HTML (https://html.spec.whatwg.org/dev), and so including these allows caniuse integration with the dev edition (whatwg/html#2794).

Tweak some spec IDs for HTML

---

features-json/es6-module-dynamic-import.json
features-json/es6-module-nomodule.json

* Turns the existing "ES6 module" entry into "JavaScript modules: <script type="module">", and cleans up its data a bit
* Adds new module-related entries for dynamic import() and the nomodule attribute
Test for nomodule: https://cdn.rawgit.com/jakearchibald/6110fb6df717ebca44c2e40814cc12af/raw/7fc79ed89199c2512a4579c9a3ba19f72c219bd8/
Test for dynamic import(): https://plnkr.co/edit/pgsxdd6hE7uzQY9dHCwz?p=preview
---
Partially solves https://github.com/Fyrd/caniuse/issues/2300, although I refrained from adding module workers as no browser seems to have started work on them yet.

Expand and add JavaScript modules entries

---

features-json/flexbox.json

Currently, searching for `CSS` will not show this feature. 
Prefix with CSS like (most?) other CSS features.
According to the CR, the full name of this feature is `CSS Flexible Box Layout Module Level 1`.

Add CSS prefix to flexbox

---

features-json/css-paged-media.json

htmluse.com is actually a parked domain, I guess it no longer works. I checked https://web.archive.org/web/20150324033405/http://www.htmluse.com/css-paged-media-page-rule/ and https://www.tutorialspoint.com/css/css_paged_media.htm they are identical. As Tutorials point is a well known resource, I'd suggest to use it as replacement.

Replace outdated link to htmluse.com

---

features-json/arrow-functions.json
features-json/const.json
features-json/es5.json
features-json/es6-class.json
features-json/es6-number.json
features-json/internationalization.json
features-json/json.json
features-json/let.json
features-json/localecompare.json
features-json/promises.json
features-json/proxy.json
features-json/rest-parameters.json
features-json/template-literals.json
features-json/typedarrays.json
features-json/use-strict.json

ecma-international.org now supports [HTTPS](https://www.ecma-international.org/ecma-262/6.0/), so let's use it.

Use HTTPS links for ecma-international.org

---

features-json/css-sticky.json

The polyfill https://github.com/filamentgroup/fixed-sticky has been abandoned/deprecated. The developers recommend the newly released https://github.com/dollarshaveclub/stickybits instead.

Replace abandoned polyfill with newer one.

---

features-json/flexbox.json

Adds the info about Firefox being the only browser that supports `justify-content: space-evenly` into the list of bugs for the Flexible Box Layout Module.

:memo: `justify-content: space-evenly` is only supported by Firefox

---

features-json/constraint-validation.json

Since a value is only `tooShort` if its `<input>` has a `minlength`.

constraint-validation: Link to minlength support in tooShort note

---

features-json/background-attachment.json

The issue referenced notes that it is `background-attachment: fixed` not `background-positon: fixed` that causes the issue. (`background-position: fixed` is an invalid property.)

Corrected `background-attachment:fixed` Known Issue

---

features-json/css-variables.json

Related to a current and verified bug with Edge 15 that IMHO makes css-variables unusable in large projects. 
Microsoft bug link https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12143022/

css-variables: Added Edge 15 bug

---

features-json/css-rrggbbaa.json

<https://www.chromestatus.com/feature/5685348285808640>, Android WebView remains off due to <https://bugs.chromium.org/p/chromium/issues/detail?id=618472>, though.

#RRGGBBAA in Chrome 62+

---

features-json/flexbox.json

The sentence found in the description for the flex property sounds awkward,
and is most-likely incorrect and confusing. Reword it to make it clearer.

Correct grammar in flex property description

---

features-json/word-break.json

There is `word-break: break-word` so this is no longer unofficial. -> https://www.w3.org/TR/css-text-3/#word-break-property

word-break: break-word exists in W3C text module

---

features-json/css-fixed.json

Safari 9.1 doesn't draw elements with `position: fixed` that have an
animated parent. The element will show up on redraws (e.g. resizing the
window).
Works in Safari 5.1, 6.2, 7.1, 8, and 10.1. I have not been able to test
Safari 9.0.
Screenshots:
https://www.browserstack.com/screenshots/05a0ae8ea84eab952eb13de45e1de4108fe8822e
jsbin:
https://output.jsbin.com/fuxipax

css-fixed: Safari 9.1 doesn't draw element with `position: fixed` that has animated parent

---

features-json/css-mixblendmode.json

Chrome (including current Chromium) and Opera render mix-blend-mode differently in SVG when non-SVG elements are present.
- [Incorrect rendering](https://codepen.io/lumio/pen/YxoPWo)
- [Correct rendering](https://codepen.io/lumio/pen/vJqExB)

css-mixblendmode: Add known issues for Chrome and Opera

---

features-json/filereader.json

added info about polyfill for `readAsBinaryString` in IE10, IE11

added info about polyfill of readAsBinaryString

---

features-json/input-file-directory.json
features-json/link-rel-preload.json
features-json/push-api.json
features-json/serviceworkers.json
features-json/subresource-integrity.json
features-json/web-animation.json

Catches up featuresets to TP 39 and iOS 11 experimental features that are disabled by default but can be enabled.

Fixes typo; adds various Safari experimental features that can be enabled

---

features-json/indexeddb.json

Microsoft Edge does not support IndexedDB inside blob web workers. [See issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5942817/).

Microsoft Edge does not support IndexedDB inside blob web workers

---

features-json/tls1-3.json

Chrome on Android 61 supports TLS 1.3 behind a flag, as verified by visiting https://www.ssllabs.com/ssltest/viewMyClient.html with the flag enabled.
Removed unreferenced notes so that the first note is #1.

Update TLS 1.3 support for Chrome on Android

---

features-json/path2d.json

This makes https://html.spec.whatwg.org/multipage/canvas.html#path2d-objects the
spec URL for https://caniuse.com/#feat=path2d. That lets a (caniuse-based)
support annotation for the Path2D feature also appear in the developer edition
at https://html.spec.whatwg.org/dev/canvas.html#path2d-objects.
(The spec URL was https://html.spec.whatwg.org/multipage/canvas.html#dom-path2d
previously — which is the part of the spec about the Path2D() constructor — but
that isn’t present in the developer edition, so no Path2D support annotation
could appear in the developer edition.)

Use “Path2D objects” heading for Path2D spec URL

---

features-json/input-selection.json

This makes #dom-textarea/input-setselectionrange the spec URL for
https://caniuse.com/#feat=input-selection. That form of the URL — with an actual
U+002F slash character rather than with that URL-encoded at %2F — matches the
formatting of the actual ID in the spec and so prevents an error that otherwise
occurs when building the spec output, with the caniuse-based support annotations,
from the HTML spec source.

Don’t encode slash in input-selection spec URL

---

features-json/css-font-rendering-controls.json

Via <https://www.chromestatus.com/feature/4799947908055040>:
> Chrome for desktop release 60
Chrome for Android release 60
Android WebView release 60
=> +~30% support in the table B-)
(Android WebView is probably at least at v60 currently, which needs to be updated, and then changed to `y` 0:-))
Added the Edge feature request, too.

CSS font-display: Supported in Chrome for Android 60+; Add Edge feature request

---

features-json/link-rel-preconnect.json

Edge 15+ supports preconnect as an HTTP header, but not yet as a `<link rel>` tag.

Preconnect is partially supported in Edge 15+

---

features-json/dragndrop.json

The bug text includes a link to a codepen containing a test case for this (as well as the FF can't-drag-a-button bug).
https://codepen.io/michai/pen/NwORqO

Add FF undraggable-unless-dataTransfer-is-set bug.

---

features-json/css-selection.json

The existing url <https://webplatform.github.io/docs/css/selectors/pseudo-elements/::selection> is returning 404 and the site itself has been [discontinued](https://github.com/webplatform/webplatform.github.io/).

Replace broken resource link for CSS ::selection

---

features-json/font-loading.json

https://drafts.csswg.org/css-font-loading/
The spec is not a W3C Candidate Recommendation but an editors’ draft

Reduced status of font-loading to unoff

---

features-json/css-sticky.json

See https://bugs.chromium.org/p/chromium/issues/detail?id=702927#c16
Also added a missing 5th note because some older Safari versions were refering to it but it didn't exist...

Chrome supports sticky on thead & tr with v64

---

features-json/svg-css.json

Edge does not currently support data URIs for SVG backgrounds.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6274479/

Update for SVG Backgrounds in Edge

---

features-json/input-datetime.json

This feature works as intended as of Chrome for Android 62. It was probably fixed in an earlier version.
I'm not sure in which version the bug was found, but the note was added in da91eb4b2fc5dad27bebd1e22e26ae20b211e5f3 (when Chrome 42 was stable).

Date input with min/max works fine

---

features-json/serviceworkers.json

<https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/>
> Made Service Workers enabled by default 
Though
> **While work continues**, we’re excited to enable Service Workers by default in this release.
I was optimistic and chose `y`, but one could maybe(?) argue for partial, too.

Safari TP 46: Service Workers enabled by default

---

features-json/battery-status.json

Previous demo site only supports the outdated spec version.
New demo site supports both current and outdated spec version, and therefore works with Chrome.

Change demo page for battery status API

---

features-json/css-sticky.json

https://bugzilla.mozilla.org/show_bug.cgi?id=975644 was marked as resolved targeting Firefox 59 :tada:

Firefox 59 fixes sticky bug

---

features-json/opus.json

Opera should be fine as it inherits Chrome's support. Firefox support is mentioned [here](https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox):
> Vorbis audio, Opus audio (...) can be viewed in Firefox if they are embedded in the following container formats: Ogg (.ogg, .oga, .ogv, .ogx, .spx, .opus file types) or WebM (.webm file type).
Verify by playing [this file](https://sebbro.nl/opus_test.webm) (thanks to https://freepd.com/), or by running the following:
```javascript
MediaSource.isTypeSupported('audio/webm; codecs=opus')
```

Opus: Opera and Firefox support Opus in WebM

---

features-json/geolocation.json

- Improve wording so that the issue doesn't come across as some random bug.
- The issue has also been fixed in Firefox 53 and above with the new permission prompt which cannot be dismissed without a permission decision.

Clarify Firefox geolocation callback issue

---

features-json/pad-start-end.json

This links to `padEnd` rather than `padStart` because the spec sorts them alphabetically, thus causing `padEnd` to be presented before `padStart`.

padStart & padEnd are part of ES2017

---

features-json/css-containment.json

https://www.w3.org/TR/css-contain-1/
W3C Candidate Recommendation, 8 August 2017

css-containment is a Candidate Recommendation

---

features-json/intersectionobserver.json

https://www.w3.org/TR/intersection-observer/
> W3C First Public Working Draft, 14 September 2017

IntersectionObserver is now a Working Draft

---

features-json/calc.json
features-json/rem.json
features-json/viewport-units.json

Changes: Add bug about IE/Edge truncating values to 2 decimals place, in `rem`, `viewport-units` and `calc()`. I think these are the 3 places were this bug can have big impacts.
Note: I tested `px`, `em`, `rem`, `%`, `vh`, `ex`, `ch` in IE 9-10 and Edge 14-15-16.
Closes https://github.com/Fyrd/caniuse/issues/3946
See: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/961517/

docs: add bug about IE/Edge truncating values #3946

---

features-json/datalist.json

* R.I.P. WebPlatform.org
* Remove "polypill" [sic] misspelled duplicate

datalist: Cleanup links

---

features-json/font-loading.json

https://www.w3.org/TR/css-font-loading-3/
> W3C Last Call Working Draft, 22 May 2014

font-loading is a Working Draft

---

features-json/css-display-contents.json

I wrote up [my notes](https://snook.ca/archives/html_and_css/safari-display-contents-bug) on this particular Safari bug and wanted to include it on Caniuse. I didn't link up my article so as not to be self-promotional but you can link up the article if you'd like.

Add Safari bug information on display:contents

---

features-json/css-focus-visible.json

This was changed in draft: https://github.com/WICG/focus-visible/pull/90

Rename :focus-ring to :focus-visible

---

features-json/css-masks.json

The article on `thenittygritty.co` seems to be a spam link, i just get banners for some betting site instead of a CSS tutorial.

Removing spam link from css-masks links

---

features-json/css-image-set.json

image-set was unprefixed in Safari Technical Preview 9 (https://webkit.org/blog/6800/release-notes-for-safari-technology-preview-release-9), which was shipped in Safari 10 (I believe). Add a note that this is not completely spec-compliant.

Update Safari data for image-set

---

features-json/intersectionobserver.json

Not sure if it was better to link to GitHub or NPM. Here's the NPM link just in case:
https://www.npmjs.com/package/intersection-observer

Updating dead link in Intersection Observer

---

features-json/auxclick.json

https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17997901-auxclick-event-for-non-primary-buttons

aux-click: Add Edge UserVoice link

---

features-json/contentsecuritypolicy2.json

The https://www.w3.org/TR/CSP link without version now redirects to the CSP3 spec, therefore for CSP2 the version must now be specified in the link.

update csp2 link to spec

---

features-json/innertext.json
features-json/input-placeholder.json
features-json/xml-serializer.json

MS Connect is dead.
The bug was moved from https://connect.microsoft.com/IE/feedback/details/811408/ie10-11-a-textareas-placeholder-text-becomes-its-actual-value-when-using-innertext-innerhtml-or-outerhtml to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/101525/
I also mention the bug at the innertext features because it is effected as well.

Update dead MS connect link

---

features-json/let.json

Hello!
- Here's the WebKit thread: https://bugs.webkit.org/show_bug.cgi?id=171041
- And the uglify-es thread: https://github.com/mishoo/UglifyJS2/issues/1753
I tried to word this as best as I could but it's tricky to explain: basically `let` bindings in for loops are broken in Safari 10: they act like `var` bindings in terms of scoping, but `let` bindings in terms of allowing a single initialization. This causes crashing bugs in typical code.

Warn others of Safari 10's let bug

---

features-json/flow-root.json

The statement "The result [of display:flow-root] is the same as the "clearfix" hack" is misleading. The classic "clearfix" hack doesn't establish the new BFC. These two approaches result in the fundamentally different behavior regarding floats going _before_ the "clearfixed" container in the flow and margin collapsing of the descendants of that container ([demo of this difference](https://codepen.io/SelenIT/details/qrORXm)). I suggest different wording saying that it is the better (and standard) solution to the same problem, but not the full equivalent of "clearfix".

Better description for `display:flow-root`

---

features-json/input-placeholder.json

I am 100% sure that has been fixed in Edge - because I was the one who added that notice but on an other feature, someone copied over wrong.
Also see [here](https://github.com/Fyrd/caniuse/pull/4066/files) - it's mentioned three times but once wrong.

Bug has been fixed in Edge

---

features-json/multicolumn.json

Add to note that `page-break-*` properties in Firefox can accomplish the same result as `break-` properties, as noted in https://bugzilla.mozilla.org/show_bug.cgi?id=549114 and tested in latest Firefox. Not sure how long this support has been available.

multicolumn.json - Add helpful workaround details to note about Firefox support

---

features-json/variable-fonts.json

format("*-variations") supported from M66, font-stretch and font-weight
in @font-face working, compare https://codepen.io/anon/pen/bvdOgV

Clarify Chrome Variable Fonts Support

---

features-json/download.json

Chrome no longer supports cross-origin download links.

Add known issue for a[download] in Chrome 65+

---

features-json/html5semantic.json

This is just a bit of housekeeping work. I noticed that `html5semantic.json` didn't have any keywords associated with it, so I added some. I also changed the title since "new" is a relative term that will grow less and less correct over time.
Comments welcome.

Change title of html5semantic.json; add relevant keywords

---

features-json/custom-elements.json
features-json/custom-elementsv1.json
features-json/shadowdom.json
features-json/shadowdomv1.json

Firefox 59 removed the `dom.webcomponents.enabled` preference and split it into `dom.webcomponents.shadowdom.enabled` and `dom.webcomponents.customelements.enabled`.
Also, custom elements are not yet enabled in Firefox 59 stable.
- mdn/browser-compat-data#1294
- [https://bugzil.la/1400762](https://bugzil.la/1400762 "1400762 - Deprecate dom.webcomponents.enabled and only use dom.webcomponents.customelements.enabled for Custom Elements")
- [https://bugzil.la/1428685](https://bugzil.la/1428685 "1428685 - Consider renaming pref dom.webcomponents.enabled to dom.webcomponents.shadowdom.enabled")

Correct Firefox flag information for WebComponents

---

features-json/opus.json

Revert #3731
As noted in https://caniuse.com/#feat=opus : "Support refers to this format's use in the audio element, not other conditions."
Safari simply does not support Opus in the audio element. Test for instance with the file under "Example of use in a web page" on http://opus-codec.org/examples/ or with the Opus Audio file from https://hpr.dogphilosophy.net/test/ .
More details in https://github.com/Fyrd/caniuse/pull/3731#issuecomment-354119681

Opus in the <audio> element is NOT supported in Safari

---

features-json/let.json

The `let` data indicates that `let` is fully supported in IE11, but `let` variables are not correctly bound in `for` loops. This seems similar to Note #4, but the variables are in fact scoped to the `for` block and not the function so it seems like a separate issue.
This behavior can be observed with the following:
```js
for (let i = 0; i < 10; i += 1) {
setTimeout(function () { console.log(i); }, 200);
}
```
In Chrome, this correctly logs the numbers 0-9. In IE, this logs the number 10, 10 times.

Fix incorrect data on let in IE11

---

features-json/payment-request.json

As of 20 March 2018, this is now CR.
Ref: www.w3.org/TR/payment-request/

Payment Request API to Candidate Recommendation

---

features-json/css-sticky.json

This is a follow up to #4166
We have had Microsoft confirm its a bug on Edge 16 and Edge 17.
I also added linked to the bug.

Position Sticky fails in Edge on <thead> or <tr>

---

features-json/rellist.json

Edge supports it now (see #4001) but with the same limitations as Chrome/Chromium, so it's specific to this browser (or rather engine) any more.

Remove relList note mention of Chrome/Chromium

---

features-json/css-masks.json

Edge 17 also has some support, but I've not tested that yet (mask-size, and mask-image I believe)

Edge 18 has partial CSS Mask support

---

features-json/same-site-cookie-attribute.json

Firefox 59 does not support this yet. The relevant changes to Firefox's core [just landed][bug1286821] and won't ship until Firefox 60.
re: #4013
[bug1286821]: https://bugzilla.mozilla.org/show_bug.cgi?id=1286861

Fix SameSite cookie support for Firefox 59

---

features-json/css-sel3.json

nth-of-type should be with bracktes, because it takes number as a parameter.

typo with "nth-of-type"

---

features-json/ambient-light.json

- Reflect spec redesign and rename to 'Ambient Light Sensor'
- Update Chrome, Firefox, and Edge implementation status
- Update Demo and Article accordingly
- Update Notes
Fix #4191

Update Ambient Light Sensor support

---

features-json/wasm.json

> Starting with version 7.x, Samsung Internet supports Web Assembly. Web Assembly allows client-side web code to be written in multiple languages and execute at near native speed.
http://developer.samsung.com/internet
I'm not sure where to add Samsung Internet 7 browser beta though

Samsung browser 7 supports WebAssembly

---

features-json/requestanimationframe.json

This PR fixes a missing backtick in the description for `requestAnimationFrame`

requestAnimationFrame: Fix typo

---

features-json/upgradeinsecurerequests.json

Edge Status now tracks this feature under a [new feature id](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cspupgradeinsecurerequestsdirective/). The old entry was deleted in MicrosoftEdge/Status#597.

[upgradeinsecurerequests.json] Update ie_id

---

features-json/link-rel-preload.json

Similar to preconnect (https://github.com/Fyrd/caniuse/pull/3829), Edge 17 only has partial support for this feature.

Preload is partially supported in Edge 17+

---

features-json/css-masks.json

I found a flag in Edge 17 that enables CCS masks, Proof: https://aka.ms/devguide_edgehtml_17

CCS Masks on Edge 17 are partially supported behind a flag

---

features-json/shadowdom.json

The mapped platform status entries talk about v1, not v0.
Hopefully, it will also fix the lack of WebKit status on the v1 entry...

Removed incorrect platform status mapping

---

features-json/bloburls.json

Blob URL as iframe "src" does work in Edge since v15 and did never work in IE.
Can try this pen: https://codepen.io/grimen/pen/lBuiG
The issue for Edge concerns PDF blob urls only (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5411066/)

Fix data for IE & Edge

---

features-json/queryselector.json

The redirect is case sensitive.

Fix MDN querySelectorAll link

---

features-json/css3-boxsizing.json

The most up to date spec for box-sizing is no longer css-ui, but css-sizing.

Update spec for box-sizing

---

features-json/av1.json

Title :)
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/34544281-support-aomedia-video-1-av1
Meta: That feature request is probably unnecessary, as Edge is already listed at https://aomedia.org and Microsoft is a member, but since they don't have it listed at https://developer.microsoft.com/en-us/microsoft-edge/platform/status/ maybe at least the request will lead to that…

Add Edge feature request to AV1

---

features-json/stream.json

Facebook, Instagram, Twitter, Snapchat they all have the same problem.

Webviews don't support getUserMedia

---

features-json/css-gradients.json

I tested this using: https://jsfiddle.net/hqcgq1dm/
Here is a potential polyfill https://github.com/gilmoreorless/postcss-gradient-transparency-fix
This is my first time adding something to this repo.
Is this here really that much manual labor? I would have expected some kind of automatic testing environment.

safari partial gradient support (fixes #4243)

---

features-json/same-site-cookie-attribute.json

Rolled out already via Windows 10 June Security update - to Windows 10 RS3+ builds (16299+) (which is 2017 Fall Creators Update an newer).
See
https://github.com/MicrosoftEdge/Status/issues/616
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/samesitecookies/

SameSite cookie attribute for Edge/IE11 on Win10 RS3+

---

features-json/wasm.json

Since https://github.com/Fyrd/caniuse/commit/b602c73c0a7d651520edc727add6ed2c1fd061d4#diff-fd2aa9257c26edb4eb860eb561dcb9f9

[wasm] Samsung Internet 7 beta note is not needed anymore

---

features-json/high-resolution-time.json

* High-resolution timestamps can be rounded
* Firefox has multiple settings that have a major affect on High-resolution timestamps

Added notes on high-resolution timestamps

---

features-json/css-snappoints.json

The currently linked polyfill implements some of the older spec's features.
This PR adds a link to a more current polyfill, and mentions the difference in specifications followed between the two.
Disclaimer: I have not personally tested that the currently linked polyfill by @ckrack is not conform to today's spec. However, the last "development/feature" commit (i.e. that's not a `package.json` update) is from 2016, *before* the current revision of the snap points (dated at [14 December 2017](https://www.w3.org/TR/css-scroll-snap-1/)). Furthermore, the "more current" polyfill I've added to the links asserts on its [npm page](https://www.npmjs.com/package/css-scroll-snap-polyfill#limitations) this difference in implemented spec.

Update CSS Scroll snap points polyfills

---

features-json/rtcpeerconnection.json

Edge's support for WebRTC is only partial: it does not support data channels, and there is no similar functionality provided by ORTC. Data-only transfer p2p with Edge is still NOT possible using WebRTC. Reference: https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Awebrtc

Edge has no support for RTCDataChannel

---

features-json/feature-policy.json

My [first PR for `allow` keywords](https://github.com/Fyrd/caniuse/pull/4389) was not sufficient:
Currently, searching for "allow" gives 92 search results while "allow attribute" gives 0, this commit enables search for "allow attribute" or "attribute allow".

[Feature-Policy] Improve keywords for 'allow' attribute

---

features-json/queryselector.json

The blog post does not exist anymore (the whole blog does not seem to exist anymore).

Remove dead link for querySelector

---

features-json/tls1-3.json

Opera does not yet support TLS1.3 by default.
41.0.2323.0 possible with command line switch https://forums.opera.com/topic/16519/new-opera-developer-41/13
54.0.2920.0 has added a flag: https://blogs.opera.com/desktop/changelog-for-54/

Correct TLS support for Opera

---

features-json/cors.json

CORS is broken for resources which redirect. I don't know every version affected so I added it to my version and all newer versions as the bug is still open.

Added note about firefox bug

---

features-json/indeterminate-checkbox.json

https://bugs.webkit.org/show_bug.cgi?id=160484 was marked as fixed a couple of hours ago.

iOS 12 supports indeterminate checkboxes

---

features-json/payment-request.json

The W3C spec was updated to add a `.retry()` method, but no one has implemented it yet. It's part of the spec, hence no one completely passes the test suite anymore.

Implementations lack .retry() support

---

features-json/audio.json

* Changing playbackRate is now fixed on Chrome for Android: https://bugs.chromium.org/p/chromium/issues/detail?id=263654
I manually tested it on my phone (Android 8.1, Chrome 68) and it works. Here is a quick demo: https://html5-audio-playbackrate.glitch.me/
* Include that iOS also does not support autoplay as advised by the spec
* Include that iOS does not fire the `ended` event when the screen is off or the browser is in background: https://bugs.webkit.org/show_bug.cgi?id=173332

Update known issues of HTML5 audio

---

features-json/tls1-2.json
features-json/tls1-3.json

Update TLS 1.3 spec link to https://tools.ietf.org/html/rfc8446

TLS 1.3 is now the latest TLS version

---

features-json/css-hyphens.json

The domain name does not resolve anymore.

Remove dead link to blog post for css-hyphens

---

features-json/prefers-reduced-motion.json

Previously, the note said Firefox 63 would support `prefers-reduced-motion` but only on Windows.
According to this bug, it's implemented on Linux too:
https://bugzilla.mozilla.org/show_bug.cgi?id=1478519
I tested it and it seems to work as expected.

Update note that Firefox on Linux will support prefers-reduced-motion

---

features-json/contentsecuritypolicy2.json

Unfortunately Edge has a broken implementation of CSP nonces that can lead to severe breakages for developers using a CSP based on nonces instead of whitelists.
Since Edge ignores nonces on sourced scripts they'll get blocked and likely break the site. Developers have to resort to useragent sniffing.
Bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13246371/
Demo: https://arturjanc.com/cgi-bin/edge-nonce.py

Update Edge CSP2 support

---

features-json/audio-api.json

Safari fully supports `AudioContext.createMediaElementSource()` [since version 6](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource#Browser_compatibility).

AudioContext.createMediaElementSource(): Remove mentioned Safari bug

---

features-json/constraint-validation.json

I created a [ponyfill](https://ponyfill.com/) that adds the `reportValidity` functionality in non-supporting browsers.
For more information, check the GitHub and demo page: https://github.com/jelmerdemaat/report-validity.
I added it to the `constraint-validation.json` file.

Add a ponyfill for the reportValidity function in constraint validation

---

features-json/av1.json

Hi, and thanks for making caniuse.com!
**Reason for update:**
- The old spec repo has silently stopped receiving updates, since 10 months ago.
- (https://aomedia.googlesource.com/av1-spec/)
- Meanwhile, the new repo is active. (Fairly quiet now that v1.0.0 is out, but still. It's active.)
- (https://github.com/AOMediaCodec/av1-spec)
**Note about canonical PDF vs. repo:** The specification gets rendered out to a PDF that serves as the canonical and stable spec: https://aomediacodec.github.io/av1-spec/av1-spec.pdf
- The rest of the repo gets occasional updates, but it's unclear how/when these will be made official parts of the spec.
Let me know if you'd rather link to the PDF and I'll `git commit --amend` and force push to update this pull request.

AV1: Updated specification URL

---

features-json/tls1-1.json

Links to all sources are included in the links section of the JSON.

TLS 1.0 and 1.1 deprecated in all modern browsers

---

features-json/viewport-units.json

The note related to the vw/vh issue has been generalized for somewhat better understanding.
References
- [Benjamin Poulain](https://bugs.webkit.org/show_bug.cgi?id=141832#c5)
- [David Bokan](https://developers.google.com/web/updates/2016/12/url-bar-resizing)

viewport-units: Added specifics on vw/vh resize issue

---

features-json/av1.json

Update av1.json for Edge 18 support when the [AV1 Video Extension (Beta)](https://www.microsoft.com/nl-nl/p/av1-video-extension-beta/9mvzqvxjbq9v) is installed.

Update av1.json for Edge 18 support

---

features-json/payment-request.json

Firefox introduced a new pref "dom.payments.request.supportedRegions", which takes a list of country codes. Only CA and US are supported right now.

Added new payments pref in Firefox

---

features-json/svg-fragment.json

IE can't load SVG fragments from external resources, which means it only provides partial support for them.

 Downgrade SVG fragments support for IE

---

features-json/transforms3d.json

In Safari, version 12.0 (14606.1.36.1.9), this line of code has no effect, and you can still see the "backface".
`backface-visibility: hidden;`
However, when I use the prefix for Safari, as seen below, the "backface" is now hidden.
`-webkit-backface-visibility: hidden;`
Safari, version 12, still requires the prefix.

Safari 12 requires prefix for backface-visibility

---

features-json/audio.json
features-json/video.json

Affects Safari 11 and 12 for iOS 11 and 12 and macOS.

Default media playback controls blocked in Safari with strict CSP

---

features-json/abortcontroller.json

NOTE: window.AbortController exists in Safari but it's just a
non-functional stub. See also:
https://bugs.webkit.org/show_bug.cgi?id=174980

Mark AbortController as unimplemented in all versions of Safari

---

features-json/indexeddb.json

It's a known bug for years. 
https://bugzilla.mozilla.org/show_bug.cgi?id=781982

Issues with Firefox in Private Browsingmode.

---

features-json/css-focus-visible.json

The old link always forced you to login, the fixed link works anonymously.

Fix bugzilla link for :focus-visible

---

features-json/netinfo.json

Old broken url: https://www.davidbcalhoun.com/2010/using-navigator-connection-android/
New working url: https://www.davidbcalhoun.com/2010/optimizing-based-on-connection-speed-using-navigator.connection-on-android-2.2-/

Broken URL updated to working URL

---

features-json/css-clip-path.json
features-json/css-masks.json

Found that properties recognized by Edge 18 in Masking are a bit different. And also a pic is given to proven that `polygon()` in Clip Path for HTML/SVG **is** supported

Update Mask and Clip Path support for Edge 18

---

features-json/readonly-attr.json

The spec link for the `readonly` attribute was pointing to the wrong place. This commit fixes the link.

Correct URL for readonly spec

---

features-json/publickeypinning.json

Changed and added reference to Chrome HPKP support.
Chrome officially announced they will no longer support the HPKP header in version 72.

Update publickeypinning.json with Chrome 72 info

---

features-json/css-masks.json

The website is not working anymore, it sends you to domain parking pages or even worse scammy "Install ad blocker on Chrome now!" pages.

[css-masks]: Remove link to defunct website

---

features-json/dragndrop.json

In Firefox, drag and drop does not work when the page is served as `application/xhtml+xml` [Mozilla Bug #751778](https://bugzilla.mozilla.org/show_bug.cgi?id=751778), [Mozilla Bug #1106160](https://bugzilla.mozilla.org/show_bug.cgi?id=1106160)

Drag and drop on XHTML page does not work in Firefox

---

features-json/av1.json

As the title says, I updated the information about AV1 support in Firefox version 65.0 and 66.0.
I'm not sure, whether the support for AV1 will "ride the trains" into release channel, or maybe it will stay in beta for a longer time, but since #4713 was merged, these information should be specified ASAP that AV1 is enabled by default ONLY for Windows users (for now).
Reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1452146

Updated info about AV1 support in Firefox 65.0 and 66.0

---

features-json/flexbox.json

Microsoft moved the documentation for IE10, 11 to `previous-versions`.

Update Bug link

---

features-json/css-display-contents.json

Safari support is buggy, see
* Toggling `display: contents` to `display: none` fails to hide the element https://bugs.webkit.org/show_bug.cgi?id=188259
* `::before`/`::after` elements not filling their grid cell when container has display: contents  https://bugs.webkit.org/show_bug.cgi?id=193567

Add info about Safari display: contents bugs

---

features-json/css-rrggbbaa.json

Source: https://bugs.chromium.org/p/chromium/issues/detail?id=618472

Android Pie web views support rrggbbaa hex color notation

---

features-json/calc.json

IE has a ton of known issues with `calc` which will cause it to not work properly and as such it should be classified as partially supported.

Marking IE support as partial

---

features-json/classlist.json

I found out that IE11 does not support `classList.replace()`, so I figured I'd let others know 😄. I don't have IE10 available to test on.
Not sure if this relates to #3326 specifically.

Add note about `replace()` on classList for IE11

---

features-json/css-logical-props.json

Added missing keywords from https://www.w3.org/TR/css-logical/#index-defined-here
Resolves #4746.
Also took the liberty to update the MDN links to a more introductory resource.

[css-logical-props] Add missing keywords

---

features-json/css-display-contents.json

I understand Markdown links are supported based on https://github.com/Fyrd/caniuse/blob/master/features-json/css-snappoints.json

css-display-contents: make links clickable

---

features-json/details.json

Resolves #4785.
A review of affected Safari versions would be appreciated. But I think I've got it close enough unless I'm mistaken.
[The webkit bug](https://bugs.webkit.org/show_bug.cgi?id=173876) only mentions macOS 10.13.
However, this blog post: https://colloq.io/blog/safaris-detailssummary-rem-font-size-issue mentions Safari 10.1/11.1.
If anyone have more details on the affected versions of Safari that'd be helpful. I personally tested [this](https://csswizardry.net/demos/safari-details-text/) on iphone Safari 12.1.2 and a tablet w/ Safari 9.3, with no issues regarding the font-sizes.

[details.json] Add note on Safari font-size bug

---

features-json/input-color.json

The `http://www.html5tutorial.info/html5-color.php` link existed twice.

Remove duplicate html5tutorial.info link

---

features-json/webauthn.json

Updated status and URL after W3C released Webauthn as a standard ("W3C Recommendation")

W3C released Webauthn on March 4th, 2019

---

features-json/webgl2.json

Someone at Apple 4 years ago added a flag for WebGL2 but they didn't actually implement anything except a stub that returns a WebGL1 context when WebGL2 is requested and allowed GLSL ES 3.0 shaders. You can look in the WebKit source code and see there is no actual implementation. 99% of the added WebGL2 functionality is missing. You can try to run the [conformance tests](https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html?version=2.0.1) and see that except for a few WebGL1 tests they pass almost nothing.
Here's the results of running the WebGL2 conformance tests on Safari Tech Preview 76 (12.2)
```
Passed 624/2733 tests (22.83%), 83619/275358 subtests (30.37%) 
Failed 1857/2733 tests (67.95%), 191184/275358 subtests (69.43%) 
Timeout 252/2733 tests (9.22%)
``` …

Mention that WebGL2 in Safari is far from usable

---

features-json/dragndrop.json

Removes the statement about dragging not causing scrolling.
The [linked bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=41708) has been marked as resolved and fixed. I have tested that it works with scrolling the window. However, I haven't tested scrollable regions embedded in the window.

Remove fixed Firefox scroll bug

---

features-json/css-overflow-anchor.json

According to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1305957
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/66

Firefox 66 has scroll anchoring

---

features-json/av1.json

- Added a **note for Firefox 66+** that reflects being AV1 being enabled by default on **macOS & Windows**
- Updated the **note for Firefox 65** to clarify AV1 was enabled by default **only on Windows 64-bit** in that release
For AV1 being enabled by default on **macOS in Firefox 66**:
- [Bug 1521181 - Pref on RDD/AV1 for OSX](https://bugzilla.mozilla.org/show_bug.cgi?id=1521181)
- Status: `RESOLVED FIXED in Firefox 66`
- Corresponding revision in the mozilla "release" (as opposed to "central" aka nightly) source repo: https://hg.mozilla.org/releases/mozilla-release/rev/35418acc5dc7
For support in **Firefox 65** being **Windows 64-bit** only:
- Firefox 65 release notes https://www.mozilla.org/en-US/firefox/65.0/releasenotes/
- > A better video streaming experience for 64-bit Windows …

av1.json: Update Firefox notes for 66

---

features-json/shadowdomv1.json

I removed info that Shadow DOM v0 is being implemented by Chrome and Opera, unlike other browsers, since it is no longer true.

Updated notes section in Shadow DOM v1

---

features-json/custom-elementsv1.json

I removed info that Custom Elements v0 is being implemented by Chrome and Opera, unlike other browsers, since it is no longer true.

Updated notes section in Custom Elements v1

---

features-json/tls1-3.json

macOS 10.14.4 has TLS 1.3 support by default

---

features-json/calc.json

Just like Firefox, IE doesn't support the use of calc inside color functions. Firefix says to have fixed this, but I haven't tested it

Added issue for IE

---

features-json/cryptography.json

Fix for issue #4846, added a note to indicate that in Edge, WebCrypto is not available in Service Workers or Web Workers.

Edge: No Web Crypto in Service Workers or Web Workers

---

features-json/webm.json

Safari 12.1 / iOS 12.2 introduced support for [VP8 but only when used in WebRTC.](https://webkit.org/blog/8672/) 
Couldn't come up with a better phrasing than this. Edits are welcomed.

WebM: Safari's WebRTC-only VP8 support

---

features-json/picture-in-picture.json

**In this commit I did the following:**
* corrected and improved information about Picture in Picture support in web browsers
* changed links in "Links" section.
**Sources:**
* [Picture in Picture in Firefox Nightly](https://www.bleepingcomputer.com/news/software/mozilla-adding-a-picture-in-picture-mode-to-firefox/)
* [Picture in Picture in Chrome 69](https://techdows.com/2018/09/chrome-picture-in-picture-mode-vs-opera-video-pop-out.html)
* [Video Pop Out in Opera 37](https://blogs.opera.com/desktop/2016/05/ad-blocker-opera-for-windows-mac-free)
* [iOS 9 multitasking features](https://wccftech.com/ios-9-multitasking-features)
* [Picture in Picture on macOS 10.12 Sierra](https://support.apple.com/en-us/HT206997)

Improved info about Picture in Picture support

---

features-json/http2.json

**In this commit I did the following:**
* updated link and changed link title
* changed "HTTP2" to "HTTP/2"
* removed doubled note.

Improved page about HTTP/2 support

---

features-json/picture-in-picture.json

As the title says, in this commit I brought back the links that were probably accidentally removed.

Brought back accidentally removed links

---

features-json/http2.json

As the title says, in this commit I removed the doubled note in support table concerning HTTP/2.

Removed doubled note in support table concerning HTTP/2

---

features-json/beacon.json

As described extensively in the [link](https://bugs.webkit.org/show_bug.cgi?id=188329): Desktop Safari 11.1 - 12 and iOS Safari 11.3 - 12.1 have bug with sendBeacon which throws error when it is used in a pagehide event callback. This issue has been fixed in iOS 12.2 and macOS 10.14.4.
This change proposes adding this bug information under bugs array in beacon.json

Added Safari bug description for Beacon API

---

features-json/bloburls.json

- the blob url can still be referenced inside the iframed document, just not as the iframe src (apparently)

Clarify IE limitation for blob urls

---

features-json/webvr.json

Reworded to remove product names, as more than one manufacturer of VR HMDs exist.

Fix typos in webvr notes by rewording

---

features-json/indexeddb.json

The "not being supported" link which is found in the notes about IE10 / IE11 points to codepen. Codepen does not support IE11, therefore this link isn't useful to see what is supported by IE11. This commit replaces that link with one that points to glitch.com (I have copied the test script from codepen to glitch.) Glitch's 'view' feature loads the source as is, and will work in IE11. The glitch version can be used to see support in IE11.
and when accepting the warning:
And when trying to view it in 'full' mode:

Replace IE10 / IE11 testing link

---

features-json/css-focus-visible.json

The current link leads to a bug for missing _developer documentation_ on `:focus-visible`, and has been closed since MDN added docs.
This change updates the URL and tile to match the implementation bug instead.

Fix correct link to Mozilla/Bugzilla bug for :focus-visible

---

features-json/lazyload.json

The [legacy `lazyload`](https://caniuse.com/#feat=lazyload) attribute has poor implementations amongst browsers and I don't think there are any good reasons for developers to use it.
To avoid confusion I have updated the feature description with a link to the new [`loading`](https://caniuse.com/#feat=loading-lazy-attr) attribute.
Is it clear enough?...

Update lazyload.json w/ link to the new standard

---

features-json/background-img-opts.json

All versions of Safari doesn't support `-webkit-background-clip: text` for buttons. But you can put a span inside button to achieve the same result. Codepen example https://codepen.io/guoyunhe/pen/byjOeN

Safari `-webkit-background-clip: text`

---

.github/FUNDING.yml

Add Sponsor badge to the GitHub Repo with link to https://www.patreon.com/join/caniuse
REF: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

Add Sponsor badge to the GitHub Repo

---

features-json/tls1-3.json

Minor update on the note about Safari TLS 1.3 support being limited to Mojave and later.

Mojave and later support TLS 1.3

---

features-json/css-media-interaction.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1035774 fixed in 2018-09-13 for Firefox 64
https://bugs.chromium.org/p/chromium/issues/detail?id=442418 fixed in July 2017

Remove fixed bugs from css-media-interaction.json

---

features-json/resizeobserver.json

As the original polyfill does not support the latest version of the specification and doesn't seem to be maintained as much recently. I'd like to propose this additional polyfill, which adds support for `box-size` options.

ResizeObserver: Add additional polyfill for latest specification.

---

features-json/css-filters.json

Removed broken links.
Added explanation about missing drop-shadow parameter spread-radius.

Broken links, missing spread param for drop-shadow

---

features-json/svg-filters.json
features-json/svg-fonts.json
features-json/svg-fragment.json
features-json/svg-smil.json
features-json/svg.json

At Can I use, some entries reference SVG 2 and others reference SVG 1.1. This may confuse readers.
This PR makes entries references SVG 2 as much as possible though number or entries which references SVG 1.1 increased.

Tweak SVG `spec` urls and `status`

---

features-json/netinfo.json

RE: https://caniuse.com/#feat=netinfo
> In Chrome the API is enabled on Android only
This is a bit misleading as the API is available on desktop too and supports the **downlink**, **effectiveType** & **rtt** values (as point 4 in the notes mentions). You can see the output from the API here here: https://googlechrome.github.io/samples/network-information/. I think it's better to remove this statement.
> Support is also available on Firefox OS.
No longer relevant, so safe to remove.

Updates notes for Network Information API

---

features-json/async-functions.json

A few months ago, it was discovered that async arrow functions aren't supported in Safari 10.1 to 10.3: https://github.com/kangax/compat-table/pull/1420

Safari 10.3 doesn't fully support async functions

---

features-json/css3-boxsizing.json

This is not necessarily an issue with `box-sizing` but it is an issue which occurs when this snippet is used:
```css
html {
box-sizing: border-box;
}
*,
::before,
::after {
box-sizing: inherit;
}
```
Because that technique is used quite a lot, it might be worth mentioning this in the bugs section?

inherit issue with `<details>` in Chrome

---

features-json/loading-lazy-attr.json

Adding link to new informational article: https://web.dev/native-lazy-loading
&plus; `#enable-lazy-frame-loading` flag and some relevant keywords.

Lazy-load: new blog post, keywords and Chrome flag

---

features-json/css-line-clamp.json

now fairly well supported across modern browsers, so the phrasing seems outdated

Update cautionary note on CSS line-clamp

---

features-json/const.json

As you can see on http://kangax.github.io/compat-table/es6/#test-RegExp.prototype_properties, IE11 doesn't support using `const` in `for-in` and `for-of` loops (replicated on my IE11 - it fails with a script error)

IE11 doesn't upport const in for-in and for-of loops

---

features-json/matchmedia.json

MediaQueryList.addEventListener [doesn't work in Safari and IE](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#Browser_compatibility)
Related discussions: https://github.com/microsoft/TypeScript/issues/32210, https://github.com/ReactTraining/react-media/pull/135, https://github.com/mdn/browser-compat-data/pull/3674

MediaQueryList.addEventListener Safari and IE bug

---

features-json/webxr.json

**Chrome 79** has removed support for **WebVR**.
Without this, it’s impossible to display this in the “Can I use…” data.
---
Reverts: #4456
See also: #3948
/cc @jpmedley

feat: Split WebXR and WebVR

---

features-json/loading-lazy-attr.json

this entry got (most likely by accident) deleted via commit 6ead43a5e4821cf12c04572b9f768928eec44acf, so I'm readding it

(re)added polyfill entry to loading attribute feature

---

features-json/css-filters.json

CSS Filters (css-filters.json) -> Resources: 
1. Changed dead link in Resources to archived Wayback link 
2. Changed dead link in Resources to archived Wayback link
**Link 1:** 
Title: Filter editor
URL: http://dl.dropbox.com/u/3260327/angular/CSS3ImageManipulation.html
Issue: 404 error 
This article is archived here: http://web.archive.org/web/20160219005748/https://dl.dropboxusercontent.com/u/3260327/angular/CSS3ImageManipulation.html
I have written to the author and queried if he will ever make the original page available again.
**Link 2:**
Title: Filter Playground
URL: http://bennettfeely.com/filters/
Issue: 404 error
This article is archived here:
http://web.archive.org/web/20160310041612/http://bennettfeely.com/filters/
This link is also linked internally on  Mr Bennet Feely's own …

Wayback archives for broken links in CSS filters (css-filters.json)

---

features-json/webvr.json
features-json/webxr.json

Historical documentation on these features is pretty bad, but this update should improve the results greatly. If anyone wants to spend even more time fine-tuning the results, feel free.
All the information is collected from official sources, but many of the sources have vague or conflicting information.
Links used for research:
https://chromestatus.com/feature/4532810371039232
https://chromestatus.com/feature/5680169905815552
https://chromestatus.com/feature/4755348300759040
https://chromestatus.com/feature/5732397976911872
https://bugs.chromium.org/p/chromium/issues/detail?id=833633
https://bugs.chromium.org/p/chromium/issues/detail?id=954531
https://bugs.chromium.org/p/chromium/issues/detail?id=948921
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/0fCZESiIY0Y …

Improve accuracy of WebXR/VR information

---

features-json/download.json

This PR adds a polyfill for the a[download] functionality for IE11. More info:
https://github.com/jelmerdemaat/dwnld-attr-polyfill

Add a polyfill for the download attribute in IE11

---

features-json/same-site-cookie-attribute.json

This rabbit hole has kept me quite occupied for several weeks now. The changes are:
- Chrome 80 will follow [Incrementally Better Cookie](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00) by default
- Changed many of the Safari support statuses to partial
- Refer to the commit messages for the detailed rationale
- Should be revisited when a new macOS version is released
- Added more Safari bugs and useful links

SameSite: Chrome 80+ changes, Safari support statuses

---

features-json/innertext.json
features-json/textcontent.json

Hi developers!
I'm very new to contribute to caniuse. I modified `Node.innerText` to `HTMLElement.innerText` because the following reason. According to <https://html.spec.whatwg.org>, `HTMLElement` has `innerText` not `Node`.
- `interface HTMLElement`: <https://html.spec.whatwg.org/multipage/dom.html#htmlelement>)
- `interface Node`: <https://dom.spec.whatwg.org/#interface-node>
In MDN, <https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText> redirects to <https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText> too.

Node.innerText => HTMLElement.innerText

---

features-json/template.json

Firefox seems to have a fairly significant bug in the way it handles `template` elements: it may preload images inside a `template`.  This behavior is inconsistent with the specification, most existing documentation on the template element (see https://www.html5rocks.com/en/tutorials/webcomponents/template/ for example), and other browsers; it seems like it would be a good idea to note it here.

Mention Firefox bug 1441044 for template elements

---

features-json/input-color.json

Just something I noticed while looking up browser support.

Remove duplicate `input type="color"` tutorial

---

features-json/css-math-functions.json

Previous bug was closed as `INVALID`.

Update Firefox support link for CSS math functions

---

features-json/css-masks.json

Thankfully there's already a link to an archived version of this article.

Remove reference to non-existing article

---

features-json/webp.json

- http://antimatter15.github.io/weppy/demo.html redirects to http://antimatter15.com/weppy/demo.html, which is already listed
- https://libwebpjs.appspot.com is listed twice
- https://webpjs.appspot.com is listed twice

Remove duplicate links in webp.json

---

features-json/css-snappoints.json

- Updated a few terms to no longer use "points" but "positions" instead to cut down on any confusion  between the newest spec and the previous version.
- Corrected the MDN link to point to the current spec description.
- Rearranged the polyfills to put the tool based on the latest spec higher up.

Minor updates to CSS Scroll Snap

---

features-json/webp.json

Note only applies to 18, as 79 is now Chromium-based.

Add version note to "Known Issues" for Edge

---

features-json/css-image-orientation.json

Chome is enabling this feature by default in v81
https://www.chromestatus.com/feature/6313474512650240

Add Chrome support for CSS3 image-orientation

---

features-json/sharedarraybuffer.json

See https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes
I tested it on Linux with current Firefox Nightly 74, and it seems to work with the demo on MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
Firefox Beta 73 does not have it enabled by default, even though Nightly 73 apparently had it,
so it's Nightly only for now. Thus I only put the footnote for 74 since Nightly 73 is no longer available.

SharedArrayBuffer enabled on Firefox Nightly 73+

---

features-json/border-radius.json

Border-radius does not work on iframe elements in Safari

border-radius bug

---

features-json/img-naturalwidth-naturalheight.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1328124

Link to firefox svg naturalWidth bug

---

features-json/webusb.json

Helpful in the light of eg: https://news.ycombinator.com/item?id=22228879

Point out Mozilla's position on WebUSB spec

---

features-json/meta-theme-color.json

Add note about vivaldi's support for the `theme-color` meta tag

Add note about Vivaldi support for `theme-color `

---

features-json/css-resize.json

This is a shameless plug but I got a lot of positive feedback on this [resize none on textarea is bad for UX](https://catalin.red/css-resize-none-is-bad-for-ux/) article lately and I'm happy to see that people unanimously agree with the fact that `resize: none;` for `textarea` is not a good idea:
- > Removing the default resizeability of a `<textarea>` is generally user-hurting vanity. Even if the resized textarea "breaks" the site layout, too bad, the user is trying to do something very important on this site right now and you should not let anything get in the way of that. 
[source](https://css-tricks.com/resize-none-on-textareas-is-bad-ux/)
- > yup, let the users resize if they want to, it's better to have your nice design break a little than to frustrate users who can't fill the form …

Add new resource

---

features-json/link-icon-svg.json

Just a quick iteration now that Edge is also supporting this, and I noticed the Safari note wasn't updated either.

Update notes on SVG favicons to include newer browsers

---

features-json/webvr.json

<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/73>:
> The deprecated [WebVR API](https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API)---which has been supplanted by [WebXR](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API), which supports both [augmented](https://en.wikipedia.org/wiki/Augmented_reality) and [virtual reality](https://en.wikipedia.org/wiki/Virtual_reality) applications---now [requires a secure context](https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API#API_availability) using the [HTTPS](https://developer.mozilla.org/en-US/docs/Glossary/HTTPS) protocol to operate. This is due to the availability of sensitive input sources that may include private information ([bug 1381645](https://bugzilla.mozilla.org/show_bug.cgi?id=138164 …

Firefox 73: WebVR requires a secure context

---

features-json/css-has.json

Hi!
I found the chrome bug tracker url for this long wanted feature and it only has 12 stars.
Perhaps, to be on caniuse links will help its visibility.
Cheers,
Thomas.

Add chrome bug tracker url for css-has selector

---

features-json/web-animation.json

The latest releases of Safari (13.1 on macOS and for iOS 13.4) now support the full Web Animations API, going beyond simply `Element.animate()`, and exposing CSS Animations and CSS Transitions as Web Animations objects using `Document.getAnimations()` and `Element.getAnimations()`. Previous versions only supported Web Animations as an experimental feature.
This is my first PR for caniuse.com, so I hope it is useful. I wasn't sure whether the level of support in Safari, which is the entire API save for one feature – [effect composition](https://drafts.csswg.org/web-animations-1/#effect-composition) – warranted an `a` or `y` level of support. I went with `y` in an optimistic manner, but please advise if maintainers of this repository think that is incorrect.

Update Web Animations data for Safari

---

features-json/shadowdomv1.json

I tested selectors like `:host > .foo` in several versions of Safari, including 10.0 and they all worked. I'm not sure where this comment originated from, but without automated tests or a bug reference to back up the note, it appears to be wrong.
Here are screenshots of a simple selector test working in Safari 10 on Sauce:

Remove inaccurate note and Safari support for ShadowDOM

---

features-json/av1.json
features-json/avif.json

For convenience:
- AV1: https://bugs.webkit.org/show_bug.cgi?id=207547
- AVIF: https://bugs.webkit.org/show_bug.cgi?id=207750

Add links to AV1 & AVIF for Safari support

---

features-json/tls1-1.json

A quick follow-up on #5350
Chrome 84+ is removing support. I have confirmed with a test. Also just removed the comment about support being removed in March.
Opera 67 is tested to still support TLS 1.1, meaning it's following Chromiums lead on postponing the removal.

Update Chrome removal of TLS 1.1

---

features-json/loading-lazy-attr.json

`<img loading="lazy">` support can be enabled in Settings under the Safari > Advanced > Experimental Features menu since iOS safari 13.4. and is disabled by default.
https://bugs.webkit.org/show_bug.cgi?id=200764 was the ticket to track the implementation.
https://bugs.webkit.org/show_bug.cgi?id=208094 tracks when it moves from experimental to default.

iOS Safari 13.4 adds experimental support for loading lazy

---

features-json/extended-system-fonts.json

Add Firefox support bug URLs for extended-system-fonts

---

features-json/font-variant-alternates.json

`font-variant-alternates` was dropped from the CSS Fonts Module Level 3 spec, so https://www.w3.org/TR/css-fonts-3/#propdef-font-variant-alternates no longer works.
`font-variant-alternates` is now just in the CSS Fonts Module Level 4 spec, https://drafts.csswg.org/css-fonts-4/#propdef-font-variant-alternates

Update font-variant-alternates spec URL

---

features-json/css-cross-fade.json

`cross-fade()` was dropped from the CSS Images Module Level 3 spec, so https://drafts.csswg.org/css-images-3/#cross-fade-function no longer works.
`cross-fade()` is now just in the CSS Images Module Level 4 spec, https://drafts.csswg.org/css-images-4/#cross-fade-function

Update CSS cross-fade() spec URL

---

features-json/css-marker-pseudo.json

The `::marker` pseudo-element is now defined in the CSS Pseudo-Elements Module Level 4 spec at https://drafts.csswg.org/css-pseudo-4/#marker-pseudo.
https://drafts.csswg.org/css-lists-3/#marker-pseudo-element no longer works.

Update '::marker' pseudo-element spec URL

---

features-json/keyboardevent-charcode.json
features-json/keyboardevent-code.json
features-json/keyboardevent-getmodifierstate.json
features-json/keyboardevent-location.json
features-json/keyboardevent-which.json

In general, spec URLs with fragment IDs starting with `#widl-` no longer work in current specs. They need to be updated to equivalent URLs that instead start with `#dom-` and that are all-lowercase.
This change updates the URLs for features related to `KeyboardEvent`.

Fix KeyboardEvent spec URLs

---

features-json/getrandomvalues.json

https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues is current; old URL https://www.w3.org/TR/WebCryptoAPI/#RandomSource-method-getRandomValues doesn’t work.

Update crypto.getRandomValues() spec URL

---

features-json/css-color-adjust.json

`color-adjust` was removed from the CSS Color Module spec https://drafts.csswg.org/css-color-4/#color-adjust and moved to https://drafts.csswg.org/css-color-adjust-1/#propdef-color-adjust in the CSS Color Adjustment Module spec.

Update CSS color-adjust spec URL

---

features-json/calc.json

https://www.w3.org/TR/css3-values/#calc no longer works (no anchor with that
ID), so update to https://www.w3.org/TR/css3-values/#calc-notation instead.

Update CSS calc() spec URL

---

features-json/css-image-orientation.json

https://www.w3.org/TR/css3-images/#image-orientation no longer works (no such anchor); https://www.w3.org/TR/css-images-3/#the-image-orientation works.

Update CSS image-orientation spec URL

---

features-json/array-flat.json

`Array.prototype.flat` and `Array.prototype.flatMap` are now part of the ECMAScript spec.

Update Array.p.flat/Array.p.flatMap spec URL

---

features-json/date-tolocaledatestring.json

https://tc39.github.io/ecma402/#sec-Date.prototype.toLocaleDateString no longer works (no such anchor). https://tc39.es/ecma402/#sup-date.prototype.tolocaledatestring works.

Update Date.prototype.toLocaleDateString spec URL

---

features-json/internationalization.json
features-json/intl-pluralrules.json
features-json/localecompare.json

Normalize ECMAScript Internationalization API (ECMA-402) features' `spec` and `categories`.
- Use https://ts39.es/ecma402/ for `spec` url
- Make `categories` be `[ "JS" ]` as they are JavaScript features
ECMA-402 supersedes several functions of ECMAScript (ECMA-262) so that it should be considered as JS core features.

Normalize ECMA-402 features' `spec` and `categories`

---

features-json/avif.json

It's disabled by default but Mozilla has added experimental AVIF image support that will be included in the release of Firefox 77 - it's already included in the Firefox nighties. It can be enabled via the `image.avif.enabled` flag in `about:config`
https://bugzilla.mozilla.org/show_bug.cgi?id=1625363

Add experimental support for AVIF as of firefox 77

---

features-json/css-appearance.json

Chrome is adding unprefixed support for CSS `appearance` in v84 - yay!
This is tested with the [Caniuse test](https://tests.caniuse.com/?feat=css-appearance) and is documented:
https://www.chromestatus.com/feature/4715298156445696
I also updated the spec link. The spec status was correct, but the link was to an older specification from before it was a working draft.

Update Chrome support for CSS appearance

---

features-json/input-event.json

...the radio inputs and checkbox inputs fire “click”, “input”, and “change” events in order when clicked:
* https://bugs.webkit.org/show_bug.cgi?id=190223
* https://trac.webkit.org/changeset/236779/webkit
Read https://webkit.org/blog/8419/release-notes-for-safari-technology-preview-67/
> "Fixed radio inputs and checkbox inputs to fire “click”, “input”, and “change” events in order when clicked"
Preview 67 was mentioned in the 12.1 blog post here (see bottom): https://webkit.org/blog/8718/new-webkit-features-in-safari-12-1/
...finally the file input fires an input event before the change event:
* https://bugs.webkit.org/show_bug.cgi?id=204292
* https://trac.webkit.org/changeset/252768/webkit
Read https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/
> "Changed the …

Safari fixed input events in 12.1 (radio/checkbox) and 13.1 (file)

---

features-json/css-appearance.json

In #5412 i completely failed to notice that Chromium is also adding support for the `auto` keyword in v83, making this a fully supported, unprefixed feature 🥳
I ran a manuel test to confirm it. Here is the reference:
https://www.chromestatus.com/feature/5913213940006912
They are also doing some other stuff with it, but nothing that i felt needed notes:
https://www.chromestatus.com/features#appearance (the first four entries)

Chrome adds full support for CSS appearance

---

features-json/transforms3d.json

Added <https://bugs.webkit.org/show_bug.cgi?id=170983> as well.
Safari TP 106:
Safari on iOS 13.4.1:

Reword & include Safari 13 in backface-visibility prefix requirement note

---

features-json/flexbox-gap.json

<https://bugs.chromium.org/p/chromium/issues/detail?id=762679#c41>
> [css-flexbox] Enable gaps by default
>
> Enabling for chrome 84 will be at least one more finch CL.
<https://www.chromestatus.com/feature/6031643502444544>
~Draft pull request because its not yet available without the flag.~
Chrome Canary 85.0.4153.0:
---
Chrome Beta is still at 83 unfortunately:

flexbox-gap: Chrome 84+ by default

---

features-json/serviceworkers.json

Most of the SW spec is now a candidate recommendation: https://www.w3.org/TR/service-workers/ 🥳
I also updated the link, since it's moved.

ServiceWorkers are now a Candidate Recommendation

---

features-json/link-rel-prefetch.json

I have tested this with the [Caniuse test](https://tests.caniuse.com/link-rel-prefetch). Please note that i only have access to Safari 12.1 and 13.1, as well as Safari IOS 13.5. Any data outside of those exact versions are just solid guesses.

Safari adds experimental support for Link Prefetch

---

features-json/link-rel-preload.json

Firefox is planning support by default for link preloading:
https://groups.google.com/forum/#!msg/mozilla.dev.platform/MShUZ4VTa6s/E4XFYfL5AQA
> ** Release plan **
> - I'm about to enable it in this cycle, Firefox 78, for all users of
> Nightly and then let it ride to Early Beta only.
> - After PI and PE is done with good results we plan to do a gradual
> release on Beta and Release using a study. 
This PR adds a note about it. I will also open a draft PR for the final changes when we know which exact version will be adding support.

Firefox will soon support Link Preload

---

features-json/css-image-orientation.json

In Chrome and Edge, the image’s aspect ratio is not maintained when
`object-fit: cover` and `image-orientation: from-image` are used
together:
https://bugs.chromium.org/p/chromium/issues/detail?id=1082669

Add Chrome/Edge support note for CSS "image-orientation"

---

features-json/mediasource.json

Some general updates to MSE:
- Spec is now a W3C Recommendation
- Removed broken links
- Removed old notes on partial support
- Added support in Samsung Internet 9+
I was able to test and confirm support in Samsung Internet all the way back to v9 ([test 1](https://tests.caniuse.com/mediasource), [test 2](https://html5test.com)).
#4406 shows no support up until v7.2, which means only v8 might be wrong 🤷‍♀️

General updates to Media Source Extensions

---

features-json/contentsecuritypolicy.json
features-json/contentsecuritypolicy2.json

This is a suggestion to remove the two references to `whitelist` that are currently in the database.
`blacklist`, `master`, `slave` and other unfortunate terms are not present (other than in links, which will have to be fixed externally)
This topic has been discussed a lot lately. I see this as an opportunity to move to a language that is more easily understood and more inclusive. I also want it to be a display of sympathy for all blacks. These specific changes don't do much, but in the larger picture, they are a systemic move for the better.
A few related links:
[9to5google - Chrome team moving away from the terms blacklist/whitelist](https://9to5google.com/2020/06/07/google-chrome-blacklist-blocklist-more-inclusive/)
[Twitter - Sean Metcalf reminding people to move away from old tech …

Remove references to 'whitelist'

---

features-json/webp.json

Now that Safari is adding support (🥳), i don't see any reason to link to a four year old speculative article.

Remove old note on Safari support for WebP

---

features-json/web-app-manifest.json

It just occured to me that Safari on iOS doesn't support A2HS in WebViews. In most browsers, that's not a big deal, but in Safari it means no third party browser can support the feature, leaving a large chunk of `saf_ios` traffic without support. I think it should be marked `Partial support` because of this.

Safari does not support A2HS in WebViews

---

features-json/prefers-reduced-motion.json

The newest versions of Firefox for Android and Samsung Browser supports the `prefers-reduced-motion` media query.
This is tested manually with the [caniuse test](https://tests.caniuse.com/prefers-reduced-motion), and it makes sense when you look at what engine version they're based on.
Also just removed a comment that isn't used and added the Chrome ID.

Firefox Android & Samsung Browser supports prefers-reduced-motion media query

---

features-json/webxr.json

A few additions to the WebXR table:
The Immersive Web sample pages are great for developers getting into WebXR.
Apple has opened a support bug for WebXR.
Enabling `dom.vr.webxr.enabled` in Firefox 77+ will now expose a fully functional WebXR API on all platforms (manually tested).
The flag has been here for a while, but hasn't done anything until now.
Firefox plans to add more functionality before enabling the feature by default.

Updates to WebXR

---

features-json/css-matches-pseudo.json

The css `:maches()` spec has been renamed to `:is()`, and `:maches()` has become a deprecated alias.
[Firefox 78](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#CSS) and [Safari 14](https://developer.apple.com/documentation/safari-release-notes/safari-14-beta-release-notes#CSS) are enabling `:is()` by default, and Chromium will probably follow suit in ~v87.
I have manually verified it all with [this quick test suite](https://codepen.io/atjn/full/MWKErBe).
I have made a million small tweaks - let me know if there are any specific changes you would like a comment on :)

Major update to CSS :matches() -> :is()

---

features-json/css-appearance.json

Firefox is actively working on unprefixed support to catch up to Chrome 🥳
Safari expects to implement unprefixed support at some point 🤷‍♂️
Thought it made sense to add links to the table :)
https://groups.google.com/forum/m/#!msg/mozilla.dev.platform/nlun5QV63Bo/xUXCmySGAgAJ

Add implementation bugs to CSS appearance

---

features-json/stream.json

getUserMedia support was introduced in Safari on iOS 11 but it was not
working in Safari driven UIWebView or WKWebView components in native
apps and also not in PWA mode, i.e. when a web page is added to the
home screen. For PWAs this has been fixed in iOS 13.4. Source:
https://bugs.webkit.org/show_bug.cgi?id=185448#c84
It's still not working in UIWebView/WKWebView though.

getUserMedia fixed in PWA mode on iOS 13.4+

---

features-json/tls1-3.json

Seems to have been added in https://github.com/Fyrd/caniuse/commit/c0b22864b9f445abeede6c45cad9c5bdb2b2d137#diff-630bd6be31934f3566bbec0c2d7c2e4aR386, not sure why tho.

Remove unused duplicate note in TLS 1.3

---

features-json/webm.json

See https://webkit.org/blog/10929/release-notes-for-safari-technology-preview-110/ for details (as included in the new note.)

Just-released Safari TP 110 now supports VP9 via WebRTC

---

features-json/tls1-1.json

I took the time to find a random website that only supported TLS 1.1/1.0 and check how all browsers respond to it. Turns out you can pretty quickly find one by looking through the [Qualys SSL Labs 'Recent Worst'](https://www.ssllabs.com/ssltest/#:~:text=Recent%20Worst) 😄
Changes for this PR:
Chrome and Firefox's new full-page warnings are hardly "unsupported" behaviour. The Chrome implementation is getting close, but Firefox's warning only shows on the very first TLS 1.1 load, and then never displays again. Furthermore, the "dismiss" button is directly accessible and highlighted, meaning most people will just click the button without reading the warning.
Because of this, i have decided to change `unsupported` versions to `partially supported`.
Chrome 84 (released last night) does not in …

Add notes on specific browser handling of TLS 1.1

---

features-json/css-appearance.json

Firefox has completed their implementation of CSS Appearance. According to both their [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1620467) and some manual testing by me, it is enabled by default in Firefox 80 🥳

Firefox fully supports unprefixed CSS Appearance

---

features-json/link-rel-preload.json

Changed the link from the old solved bug to the meta bug page. As Firefox is still working on this, and rendering to the meta bug page makes it clearer for the user what the status is of this feature.

Change rel=preload Firefox bug page to meta bug page

---

features-json/web-bluetooth.json

This pull request adds the Mozilla specification position link for Web Bluetooth, similar to [Web USB, URL Scroll-To-Text Fragment and more](https://github.com/Fyrd/caniuse/search?q=https%3A%2F%2Fmozilla.github.io%2Fstandards-positions&unscoped_q=https%3A%2F%2Fmozilla.github.io%2Fstandards-positions).

Web Bluetooth: Add Mozilla specification position link

---

features-json/focusoptions-preventscroll.json

This PR adds more information about focus options to prevent scrolling in Edge v17 and 18, and fixes a link to a broken MS Developer page.
Per [that link](https://web.archive.org/web/20190401133643/https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14314565/), support for `preventScrolling` was added in Edge v17. I’ve tested the test case, and everything does pass [the web platform test](wpt.live/html/interaction/focus/processing-model/preventScroll.html
) as expected.
But it doesn’t pass [the more recent test for inputs where you can type](wpt.live/html/interaction/focus/processing-model/preventScroll-textarea.html
), or textareas:
I’ve added that detail as a note.

Adds more information about focus options in Edge, fixes link

---

features-json/css-sticky.json

This implementation difference can cause incoherent behavior when dealing with elements that are sensitive to scroll position - for example, a sticky header that shrinks in height by 1px after the user scrolls down by 1px will cause the scrolling parent of the sticky header to scroll up by 1px in Chrome, resetting the sticky header to its former larger height as it is now at the top of its parent element.
Thanks to [Craig Brown](https://stackoverflow.com/users/3034366/craig-brown) for providing the SO question and test case.

CSS position:sticky - added a height/scroll height related issue due to different browser implementations

---

features-json/document-policy.json

There has been enough changes that i think it's time for an update on Document Policy.
Chrome, as usual, missed the real release version by a few points on chromestatus:
https://www.chromestatus.com/feature/5756689661820928
https://www.chromestatus.com/feature/5744681033924608
The header is already enabled by default in Chrome 84, but it has no policies, so it can only make console errors on malformed headers.
In Chrome 85+ i have tested and confirmed that setting `Document-Policy: force-load-at-top` will force the browser to ignore any text fragment in the URL, and just load the page at the top instead.

Updates to Document policy

---

features-json/native-filesystem-api.json

Chromium has landed support for the native filesystem API in v86, significantly closing the gap between native and web capabilities on the desktop 🥳
In trying not to fly too close to the sun, they have decided to only roll out some functionality, and then add to it in waves. Because of that, i have marked it as `partial` support, and will add more specifics as new functions come out.
This is the samme approach as [WebXR](https://caniuse.com/#feat=webxr), which is probably due for an update pretty soon :)
I have verified basic support in Chrome 86 with [the Caniuse test](https://tests.caniuse.com/native-filesystem-api) and [this cool demo](https://googlechromelabs.github.io/text-editor/). You can also check:
https://chromestatus.com/feature/6284708426022912 …

Chromium 86 supports Native Filesystem API

---

features-json/beacon.json

Fixed in chrome 81: https://bugs.chromium.org/p/chromium/issues/detail?id=720283

Navigator.sendBeacon is fixed in Chrome

---

features-json/css-not-sel-list.json

Add the fact that compound selector in `:not()` is not supported in Selectors level 3 spec (e.g `:not(.a.b)`).

Add missing information in selector list `:not()` description

---

features-json/css-scrollbar.json

No longer true, see https://github.com/w3c/csswg-drafts/issues/1958#issuecomment-685592633

Remove note: scrollbar-width property is at risk of being removed

---

features-json/css-content-visibility.json

I'm afraid it's in the news as well, but I don't think we can edit that code 0:-)

Fix missing "i" in CSS content-visibilty => visibility

---

features-json/css-math-functions.json

Gary Simons recently made a video on the new `clamp` property, where he [accidentally used the wrong support table](https://youtu.be/dg488RrpNTc?t=70). I think it's hard to blame him, since searching for `clamp` or `css clamp` first displays a non-standard property, and then shows 2-7 MDN tables before showing the thing that i believe most people will be searching for.
One of the MDN tables are actually also for the same property, so that should be removed, right?
You encounter similar issues when searching for `min` and `max`.
I don't actually know how the search engine works, but i have tried to add keywords that should help bring this support table to the top. By all means change them if you know something i don't :)
I have also tested Android Opera 59 to support this with the [caniuse …

Updates to CSS math functions

---

features-json/css-backdrop-filter.json

The backdrop filter also requires `gfx.webrender.all` (other than `layout.css.backdrop-filter.enabled`) to be true in Firefox which is false by default (checked in Firefox 81, currently latest on 05-10-2020). Updated this information in the notes section.
Reference : https://bugzilla.mozilla.org/show_bug.cgi?id=1591674#ct-3

Update Backdrop filter notes for firefox

---

features-json/input-datetime.json

Starting with Safari TP 115, released on Oct 22, 2020, UIs for `date`, `datetime-local` and `time` are finally supported on macOS. The `month` and `week` input type are still unsupported on macOS however.
There will be an entry in https://webkit.org/status/ soon: https://bugs.webkit.org/attachment.cgi?id=412182&action=diff
Also see https://bugs.webkit.org/show_bug.cgi?id=214946 and https://github.com/Fyrd/caniuse/pull/5646#issuecomment-715233820

Safari TP 115: Support for date, datetime-local, time inputs on macOS

---

features-json/web-share.json

Safari, prior to iOS 14, did not allow for a fetch call to happen between user trigger and when native share api is called.
Can see more details here -> https://stackoverflow.com/questions/56046434/how-to-use-webshareapi-preceded-by-an-ajax-call-in-safari
After filing a bug with the WebKit team it was fixed in iOS 14 + macOS 11
I think that should be noted for others reference.

Add note for old Safari implementation of webshare

---

features-json/referrer-policy.json

- Removed Note 3 from Chrome 84
- Note 3 applies to Chrome 85+ according to [the Chrome Platform Status.](http://chromestatus.com/feature/625188018533171)
- Changed Note 3 to reflect the revised Referrer Policy specification.
- See https://github.com/w3c/webappsec-referrer-policy/pull/142 for more information.
- Added Note 4 to explain Safari ITP's behavior.
- See [the WebKit blog post](https://webkit.org/blog/9661/preventing-tracking-prevention-tracking/) for more information.

Update notes on Referrer Policy

---

features-json/svg-filters.json

[http://electricbeach.org/?p=950](http://electricbeach.org/?p=950) is a dead link.

Remove dead link from svg-filters.json

---

features-json/http3.json

The Chromium team decided to stay in the h3-29 version for now.
https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html

data correction

---

features-json/css-filters.json

In Safari `filter` won't apply to child elements while they are animating. [WebKit Bug](https://bugs.webkit.org/show_bug.cgi?id=219729).

Add webkit bug to filter css property

---

features-json/offline-apps.json

<s>This change drops the spec URL for the "Offline web applications" feature — because that entire section has now been removed from the HTML standard.</s>
This change updates the spec URL for the "Offline web applications" feature. That entire section has now been removed from the HTML standard, so this change updates it to point to an older W3C copy.

Update the spec URL for Offline web applications

---

features-json/menu.json

It was put behind a flag in version 85.
https://bugzilla.mozilla.org/show_bug.cgi?id=1680596
Also, nested items on Firefox for android were fixed when they moved from Fennec to Fenix and are now properly supported.
Can't find a source for that one and maybe it was even fixed by mistake but "it works".

Firefox no longer supports menuitem by default

---

features-json/webm.json

- Separated the duplicate portion of note 4 from note 5.
- Added note 5 to iOS Safari 14.
- Added off-by-default clause to note 5.
- Added note 6 for [VP9 + WebM + MediaSource](https://bugs.webkit.org/show_bug.cgi?id=216652#c1) support on Safari 14 + Big Sur.
Fixes #5713 as YouTube uses MediaSource/MSE for 4K HDR support [on Big Sur.](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes)

Clarify VP8/VP9/WebM status on Safari

---

features-json/wasm.json

in MDN URL, it was leading to a 404.

Remove superfluous forward-slash

---

features-json/font-loading.json

Added a bug explaining the recent change in the spec: https://github.com/w3c/csswg-drafts/pull/5757.

Add a known issue on CSS Font Loading API

---

features-json/sharedarraybuffer.json

Chrome for Android 88 will enable SharedArrayBuffer but only for COOP/COEP-enabled pages.
* https://chromestatus.com/feature/5171863141482496
* http://web.dev/coop-coep/

Update Chrome for Android 88 on SharedArrayBuffer

---

features-json/webxr.json

Despite no public announcements, the WebKit team is [working on WebXR](https://webkit.org/status/#specification-webxr) so it can be moved to "in-development".
Other random sources:
* [WebKit commits](https://github.com/WebKit/WebKit/search?o=desc&q=webxr&s=committer-date&type=commits)
* [WebKit bug tracker](https://bugs.webkit.org/show_bug.cgi?id=208988) (already linked in references)

webxr: add webkit id, move to in development

---

features-json/web-share.json

Fixes #5768 for <https://caniuse.com/web-share>.
<https://tests.caniuse.com/web-share>:

Chrome 89: Web Share API for Windows and Chrome OS

---

features-json/css-matches-pseudo.json

Fixes an unfortunate typo - thanks to @Mouvedia for pointing it out :)

Fix typo in CSS Matches

---

features-json/same-site-cookie-attribute.json

As [Incrementally Better Cookies](https://tools.ietf.org/html/draft-west-cookie-incrementalism-01) has been adopted into rfc6265bis[-07](https://www.ietf.org/archive/id/draft-ietf-httpbis-rfc6265bis-07.html#name-draft-ietf-httpbis-rfc6265bis-07), this PR updates the related information accordingly. 
Related: https://github.com/httpwg/http-extensions/issues/1241.

Update SameSite spec to the latest

---

features-json/css-image-set.json

Following the public discussion, e.g. https://github.com/Fyrd/caniuse/issues/5785#issuecomment-787945061, [this tweet](https://twitter.com/pepelsbey_/status/1366343635437047812) by @pepelsbey made me aware that image-set is available behind a flag.
And indeed (https://tests.caniuse.com/css-image-set):

Firefox: image-set behind flag

---

features-json/css-hyphens.json

Fixes #5792.
<https://tests.caniuse.com/css-hyphens>:
macOS:
Android:
Edge for Android just wouldn't work in my emulator (Android Studio => AVD; Firefox and Chrome Canary are fine). My assumption is that the tests are completely green as well. But it would be really good if someone could test that before merging.
Win10 (EDIT: 89.0.774.45 is the same):
Haven't tested Linux though.
If we cant test Edge for Android I would change the PR so the previous state (`a #1`) is returned. Note 1 is a bit unfortunate because it only mentions Chrome. But at least that would be more accurate than `y`, because thats not true (see Win10).

Edge 88: CSS Hyphenation not yet on par with Chrome

---

features-json/css-dir-pseudo.json

<https://bugs.chromium.org/p/chromium/issues/detail?id=576815#c31>
> Flip CSSPseudoDir back to experimental
~~Haven't tested it yet, I suppose we have to wait for tomorrows build.~~
Yup: <https://tests.caniuse.com/css-dir-pseudo>
Also checked enabling the flag, which made it work again.

Chrome: :dir() CSS pseudo-class is back to experimental

---

features-json/template.json

Coming from <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template> I [searched for `<template>`](https://caniuse.com/?search=%3Ctemplate%3E) and found nothing, therefore add it to the keywords.
I found https://github.com/Fyrd/caniuse/blob/8f4d0acf750890359315e97829d8802e854fae12/features-json/html5semantic.json#L435 which made it look legit to add \<elements\> as keywords.

Add `<template>` to keywords of template

---

features-json/css-image-orientation.json

The bug where an image’s aspect ratio is not maintained when
`object-fit: cover` and `image-orientation: from-image` are used
together is fixed with Chrome version 89.
See:
https://bugs.chromium.org/p/chromium/issues/detail?id=1082669

Update note for CSS "image-orientation" bug

---

features-json/css-image-set.json

Title 0:-)
For convenience: <https://bugs.chromium.org/p/chromium/issues/detail?id=630597>

`image-set`: Add Chromium bug to unprefix `-webkit-image-set`

---

features-json/publickeypinning.json

There is a difference between Public Key Pinning and HTTP Public Key Pinning. Nearly all major browsers still support Public Key Pinning for pinning specific websites which are built into the browser.
Chrome's PKP list - https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.pins
Firefox's PKP list - https://searchfox.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json

Rename Public Key Pinning to HTTP Public Key Pinning

---

features-json/link-icon-svg.json

Coming from <https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs#safari-pinned-icon> I wanted to check Safari (thats why #5843 exists - as a side note, didn't really find a good replacement link) and searched quite a bit since surely there had to be an issue with WebKit.
There is <https://bugs.webkit.org/show_bug.cgi?id=136059>, but the TL;DR is
> So if you're looking for SVG favicon support in Safari, you'll need to file with Apple at developer.apple.com.
But I think it still has value to add that link to spare others the time to search.

SVG favicons: Add WebKit feature request bug

---

features-json/css-clip-path.json

- https://bugs.chromium.org/p/chromium/issues/detail?id=109212
- https://bugs.webkit.org/show_bug.cgi?id=104442

CSS `clip-path`: Add Chromium & WebKit bugs for shapes in external SVGs

---

features-json/jpegxl.json

This is a follow-up on #5846
Now that updated versions of Chrome 91 and 92 have been released, I tried to run them on Windows and Linux to check that they actually do support jxl decoding. Unfortunately, none of them expose the `enable-jxl` flag, which means the current note is wrong. I also tried to enable some other flags, like `enable-experimental-web-platform-features`, but nothing seems to enable jxl decoding.
I am far from an expert on building binaries, but I believe this is happening because Chrome needs to be built with the `ENABLE_JXL_DECODER` flag set before it is even possible to enable the flag in `chrome://flags`, and for whatever reason, the Chrome engineers decided not to turn that build flag on yet.
Building Chrome is a monumental task that requires a lot of technical …

Chrome does not support JPEG XL behind a runtime flag

---

features-json/jpegxl.json

Follow up #5850 per @EwoutH's [comment](https://github.com/Fyrd/caniuse/pull/5850#issuecomment-825921645).
CC @atjn

Chrome: JPEG XL back to being behind a flag

---

features-json/ogg-vorbis.json

Related to #5873, Safari 14.1+ on macOS 11.3+ added Vorbis audio format support, without the .ogg support. 
Tested with `<audio controls src="https://upload.wikimedia.org/wikipedia/commons/2/22/Volcano_Lava_Sample.webm"></audio>`.
* https://webkit.org/blog/11648/new-webkit-features-in-safari-14-1/

Update Safari Vorbis support

---

features-json/ogg-vorbis.json
features-json/transforms2d.json
features-json/urlsearchparams.json

Looks like a merge/rebase resulting in 59b9ecd12cef9c72e40fb08df365eeb2c0ae4983 went a bit sideways, i.a. returing old parts? 0:-)

Fix issues in 59b9ecd12cef9c72e40fb08df365eeb2c0ae4983

---

features-json/css-backdrop-filter.json

For convenience: <https://bugs.webkit.org/show_bug.cgi?id=224899>

CSS Backdrop Filter: Add WebKit bug to unprefix

---

features-json/eventsource.json

Firefox currently does not support [EventSource in service workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1681218)

Add Firefox EventSource service worker bug

---

features-json/intrinsic-width.json

Found the links by following what was already there, which are imho more precise.
<https://bugzilla.mozilla.org/show_bug.cgi?id=1055887#c9> at least confirms the links in note 3.
Actually I wanted to find the bug for WebKit in that note, but didn't mange to. Closest ones maybe:
- https://bugs.webkit.org/show_bug.cgi?id=221479
- https://bugs.webkit.org/show_bug.cgi?id=221481
- https://bugs.webkit.org/show_bug.cgi?id=116117
- https://bugs.webkit.org/show_bug.cgi?id=86154
- https://bugs.webkit.org/show_bug.cgi?id=221473

Updated links for Intrinsic & Extrinsic Sizing

---

features-json/web-bluetooth.json

Looks like [WebBluetoothCG/web-bluetooth](https://github.com/WebBluetoothCG/web-bluetooth) moved this out of the `gh-pages` branch.

Web Bluetooth: Update implementation status link

---

features-json/colr.json

- Safari 14 [isn't available for macOS 10.13 High Sierra](https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility), therefore note 1 isn't needed starting with that version
- Chrome => Chromium for note 3, since it's on Edge and Opera as well
CC @yisibl because #5915 of course - thanks for adding this! :)

Two tiny improvements to COLR

---

features-json/transforms3d.json

Adjust note 2 for Safari to include Safari 14 and future versions, to stop to have to adjust that with every new version.
Checked Safari 14, still the case:

CSS3 3D Transforms: Adjust note

---

features-json/canvas-text.json

Followed the redirect via http://web.archive.org/web/20190303013144/https://developer.mozilla.org/en-US/docs/Drawing_text_using_a_canvas

Update Mozilla link in canvas-text.json

---

features-json/custom-elementsv1.json

… since it seems like it will stay that way.
Links from on the way finding that bug, just for me:
- https://github.com/Fyrd/caniuse/issues/3164
- https://developers.google.com/web/fundamentals/web-components/customelements
- https://github.com/WICG/webcomponents/issues/509
- https://github.com/WICG/webcomponents/issues/662
- https://bugs.webkit.org/show_bug.cgi?id=154907
- https://wpt.fyi/results/custom-elements/builtin-coverage.html?run_id=478440003&run_id=484130003&run_id=461580002
- https://bugs.webkit.org/show_bug.cgi?id=182671

Custom Elements (V1): Add WebKit bug 182671 to note 1 regarding Safari partial support

---

features-json/jpegxl.json

Fixes #5880.
Tested it using <https://tests.caniuse.com/jpegxl>:
Haven't tested on macOS, but since [per comment](https://github.com/Fyrd/caniuse/issues/5880#issuecomment-832562501) Ubuntu is working I think it's likely that macOS works as well.

JPEG XL: Edge 91+ via runtime flag

---

features-json/css-font-rendering-controls.json

Fixes #5931.
Per discussion there first try renaming it here.
I thought the short "CSS `font-display`" title would be fitting for caniuse, mentioning `@font-face` just below that.
Feel free to suggest changes or make them yourself :)
CC @jensimmons

Rename font-rendering controls to font-display

---

features-json/css-focus-visible.json

The previous link's status was "RESOLVED DUPLICATE". Linked the active task.

Updating webkit ticket link

---

features-json/nav-timing.json

MDN Docs resource moved to https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API

Fix MDN Docs resource URL

---

features-json/prefers-reduced-motion.json

It is important to note that the option is set in the OS and that the OS may not support this feature, thus the browsers will not suppor.

Update to add note

---

features-json/native-filesystem-api.json

According to https://mozilla.github.io/standards-positions/#native-file-system, Firefox now has taken a stance against the File System Access API, but the caniuse page on it still says that Firefox has the defer position.
Since this is such a small edit, I was not sure whether I should make a PR for it, but I think it is important enough, and I thought a PR would be less work for the maintainers than opening an issue and getting another person to make the edit

Firefox's position on the File System Access API is harmful now

---

features-json/queryselector.json

https://cjihrig.com/ "is parked free, courtesy of GoDaddy.com."

queryselector: Remove blog link, deadurl

---

features-json/jpegxl.json

As expected, coming from Chromium, Opera now also has support for JPEG XL behind a flag.
I have tested and confirmed support with the [caniuse test](https://tests.caniuse.com/jpegxl).

Opera supports JPEG XL behind a flag

---

features-json/avif.json

Firefox has enabled AVIF by default for version 92: https://hg.mozilla.org/integration/autoland/rev/bb07fcce3567
They've already tried to do this ~5 other times, and then eventually backtracked because their implementation wasn't ready, but this time they've fixed all major issues _before_ enabling by default, so I am pretty confident that AVIF will in fact be enabled by default this time 🥳
At some point during development, support for sequence images was added (confirmed with [the caniuse test](https://tests.caniuse.com/avif)). I don't see any reason to keep a note about sequence support when it only applies to early development implementations that are hidden behind flags, so I have removed that note entirely.
I will be following this closely and will commit a new patch if they do end …

Firefox supports AVIF by default

---

features-json/svg-img.json

Hi!
Removing a bad example here because this blog links to a missing SVG, which is very misleading in this context! :D 
Page: https://caniuse.com/svg-img (Resources).

Removing a bad example from svg-img

---

features-json/css-container-queries.json

- Links to the actual draft specification
- Update description for clarity, removing mention of `contain` property from old syntax
- Note the change in syntax between Chrome 92 & 93

Update Container Query specification and syntax details

---

features-json/webgpu.json

Just keeping the table up to date:
- the spec is now a working draft
- WebKit has added an ID for the feature
- there is a new test site that could be interesting to check out
The only somewhat major news is that Chrome now also supports WebGPU behind a flag on Linux (confirmed with tests, and [on the official wiki](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status)), and that it has started an origin trial for testing WebGPU, which is pretty sweet :)
Closes #6019

Minor updates to WebGPU

---

features-json/css-cascade-layers.json

Experimental support landed in STP 133: https://developer.apple.com/safari/technology-preview/release-notes/#r133

Adding data on support for Cascade Layers in Safari Technology Preview

---

features-json/viewport-unit-variants.json

Stolen from <https://www.bram.us/2021/07/08/the-large-small-and-dynamic-viewports/#browser-support> 0:-)

Add support bugs to `viewport-unit-variants`

---

features-json/offscreencanvas.json

- https://bkardell.com/blog/OffscreenCanvas.html
- https://bugs.webkit.org/show_bug.cgi?id=183720
- https://bugzilla.mozilla.org/show_bug.cgi?id=1390089
---
Hype for `OffscreenCanvas` perf 🚀🚀🚀
0:-)

Add links to `OffscreenCanvas`

---

features-json/mathml.json

- MathML torture test: https://github.com/mdn/content/issues/6878
- <https://developer.mozilla.org/en/MathML/Element>: 404
- <https://www.mozilla.org/projects/mathml/demo/>: Doesn't seem to come back, [it's in the archive](https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/mathml_project)
<https://mathml.igalia.com/project/>
> As of September 2021, a significant amount of the work is upstreamed and already available in official Chromium builds under the *Experimental Web Platform Features* flag.
Pretty green ✅ 
<https://wpt.fyi/results/mathml?label=master&label=experimental&aligned&q=mathml> as well ✅ 
Even more than Firefox, which we currently have as `y`.
<https://tests.caniuse.com/mathml> with the flag enabled:

MathML: Links & Chrome 🎉 

---

features-json/css-focus-visible.json

<https://css-tricks.com/focus-visible-in-webkit/>
<https://blogs.igalia.com/mrego/2021/06/07/focus-visible-in-webkit-may-2021/>
> The high level summary is that the implementation in WebKit can be considered to be complete and all the `:focus-visible` patches have been included on the last [Safari Technology Preview 125](https://webkit.org/blog/11680/release-notes-for-safari-technology-preview-125/) as an experimental feature.
> You can test this feature in [Safari Technology Preview (since release 125)](https://developer.apple.com/safari/technology-preview/) by enabling the runtime flag in the menu (*Develop > Experimental Features > :focus-visible pseudo-class*).
I haven't tested Safari 15.0/15.1/TP nor Safari on iOS 15.0 (yet), but the flag is there in Safari on iOS 15.1 and given the …

Safari: `:focus-visible` behind flag (still 🎉)

---

features-json/push-api.json

Thanks @dfabulich :)
- https://twitter.com/dfabu/status/1454118365509783556
- https://bugs.webkit.org/show_bug.cgi?id=231008
<https://tests.caniuse.com/push-api>:
Checking the tests under <https://wpt.fyi/results/push-api?label=master&label=experimental&aligned&q=push> passing are now
- 51/51
- 10/84
- Error
- 41/42
so definitely improved (at least vs TP 125), but partial might be safer… what do you think?
EDIT: 
Yeah, leaning more towards partial… <https://twitter.com/schweinepriestr/status/1454167693330993163>
`"n d a #5"`, `"n a d #5"` or…? :)

Safari TP 134: Surprise off by default Push API (🎉)

---

features-json/sql-storage.json

ref https://blog.chromium.org/2021/11/chrome-97-webtransport-new-array-static.html

sql-storage: Not supported in third party contexts in chrome 97

---

features-json/sharedarraybuffer.json

Haven't tested down to Edge 91, but it's probably safe to assume it's been the same since.
The links are more precise this way, better than #6109, sry 0:-)

Shared Array Buffer: Align Edge to Chrome and more precise links

---

features-json/css-has.json

https://webkit.org/blog/12156/release-notes-for-safari-technology-preview-137/
> Enabled support for `:has()` pseudo-class by default ([r286495](https://trac.webkit.org/changeset/286495/webkit/), [r286135](https://trac.webkit.org/changeset/286135/webkit/), [r286302](https://trac.webkit.org/changeset/286302/webkit/), [r286180](https://trac.webkit.org/changeset/286180/webkit/), [r286226](https://trac.webkit.org/changeset/286226/webkit/), [r286494](https://trac.webkit.org/changeset/286494/webkit/), [r286433](https://trac.webkit.org/changeset/286433/webkit/), [r286188](https://trac.webkit.org/changeset/286188/webkit/), [r286169](https://trac.webkit.org/changeset/286169/webkit/), [r286365](https://trac.webkit.org/changeset/286365/webkit/))
Didn't test https://tests.caniuse.com/css-has though. …

Safari TP 137: `:has()` 🎉 

---

features-json/web-animation.json

There was an issue before: https://github.com/Fyrd/caniuse/issues/5969
But currently https://caniuse.com/?search=waapi leads to nothing:

Add WAAPI as keyword to Web Animations API

---

features-json/css-cascade-layers.json

Safari Technology Preview supports Cascade Layers by default. It's been that way for a while now.

STP supports Cascade Layers by default

---

features-json/wordwrap.json

Removed word-wrap link as it redirects to the overflow-wrap page, which is one of the remaining links.
{
"url":"https://developer.mozilla.org/En/CSS/Word-wrap",
"title":"MDN Web Docs - CSS word-wrap"
},

Remove redirecting link

---

features-json/colr-v1.json

[5897235770376192](https://chromestatus.com/feature/5897235770376192) was for v0 while [5638148514119680](https://chromestatus.com/feature/5638148514119680) is for v1 0:-)
Also link the other browsers mentioned there.
CC @yisibl and also thanks for adding this! :)

COLRv1 additions

---

features-json/loading-lazy-attr.json

Lazy image loading is supported by default in Safari 15.4 and Safari Technology Preview. Lazy iframe loading is available via an off-by-default Experimental Features option.

Update Safari 15.4 to partial support for lazy loading

---

features-json/loading-lazy-attr.json

The word experimental was misspelled.

fixing typo in note on Lazy Loading page for loading attribute 

---

features-json/loading-lazy-attr.json

I found a typo in the description. This PR fixes it.

fixing typo in description on Lazy Loading page for loading attribute 

---

features-json/viewport-unit-variants.json

Finally figured #6166 out - the units are simply behind the Experimental Web Platform features flag :P
<https://tests.caniuse.com/viewport-unit-variants>:

Chrome 100: Small/large/dynamic/logical viewport units behind flag 💡🎉

---

features-json/css-has.json

<https://bugs.chromium.org/p/chromium/issues/detail?id=669058#c47>:
> Enable both snapshot and live :has() pseudo class support behind
the experiemental web platform feature flag.
Though
> There are some functional limitations.
> - :has() doesn't work properly with pseudo elements in the
subselector.
> - :has() doesn't work properly with some logical combinations
(:is(), :where() and :has()) in the subselector.
which seems to show on <https://wpt.fyi/results/css/selectors?label=master&label=experimental&aligned&q=has>:
But since it's behind a flag away, literally saying experimental, I think it's not yet anything to denote on caniuse.
For the record, <https://tests.caniuse.com/css-has>:

Chrome 101: CSS `:has()` behind flag

---

features-json/flexbox-gap.json

**Safari** does not support `gap` with `column-reverse` `flex-direction`
```html
<main>
<section>A</section>
<section>B</section>
<section>C</section>
<section>D</section>
</main>
```
```css
main {
border: 1px solid blue;
display: flex;
gap: 16px;
flex-direction: column-reverse;
}
section {
border: 1px solid red;
}
```
`flex-direction: column;`
`flex-direction: column-reverse;`

Add safari gap bug

---

features-json/css-marker-pseudo.json

Added a second note about Safari, which more clearly explains what is and what is not supported. It's the same link as the one in the MDN browser compatibility  table.

Added more details about Safari support

---

features-json/css3-tabsize.json

tab size is relevant for 3 values of white space, but only two were listed. 
added `white-space: break-spaces` to the list.
example: https://codepen.io/estelle/pen/WNdpPPo

fix property list

---

features-json/native-filesystem-api.json

Clarify that it only covers the Origin Private File System part.

Clarify File System Access API support in Safari

---

features-json/createimagebitmap.json

Firefox note 5:
https://bugzilla.mozilla.org/show_bug.cgi?id=1335594#c19
> Looks the patches in [bug 1367251](https://bugzilla.mozilla.org/show_bug.cgi?id=1367251) is adding the options, so close as duplicate.
=> https://bugzilla.mozilla.org/show_bug.cgi?id=1367251#c35
> Status: NEW → RESOLVED
> Closed: 8 months ago
[status-firefox93](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox93&o1=isnotempty): --- → [fixed](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox93&o1=equals&v1=fixed)
Resolution: --- → FIXED
Target Milestone: --- → 93 Branch
Also matches <https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#browser_compatibility>:
Safari is more partial than presumed, see MDN and https://bugs.webkit.org/show_bug.cgi?id=182424#c0, which includes note …

Bring createImageBitmap up to date

---

features-json/webp.json

Clarifying partial support note #3 for WebP regarding support in Safari 14–15. 
We get a lot of questions about whether or not Safari supports WebP. Developers clearly have this question on their mind, since WebP is currently the number 3 most-looked up technology on Can I Use. 
Folks seem to think "partial support" means WebKit did not implement WebP correctly, or we haven't finished implementing the full specification. Neither of which is true. I'm hoping this revision to the note will explain exactly what partial support means in this case — especially to busy/fast-reading or non-fluent-in-English web developers. 
I say "Safari 14.0 – 15.x" intentionally, for the same reason Safari Technology Preview should be marked as full support.

Clarifying partial support note #3 for WebP

---

features-json/css-nth-child-of.json

Complex :nth-child  and :nth-last-child selectors are part of Selectors 4, which is in Working Draft. This is not an unofficial specification. 
https://www.w3.org/TR/selectors-4/#the-nth-child-pseudo

Complex :nth-child selectors are Working Draft

---

features-json/webp.json

A small, clarifying adjustment to the note about WebP in Safari 14.0–15.6.

Small adjustment to note 3 regarding Safari

---

features-json/webm.json

Similar to WebP, Safari 16 requires macOS Big Sur or later, so it's impossible for it to run on a version of macOS that doesn't have WebM support. I've also update this note so it's very clear to web developers when it works or not.

Safari 16 on macOS fully supports WebM

---

features-json/css-container-queries.json

Narrowing the scope of this page to be about Size Queries in the Container Queries spec. Updating description to reflect the maturity of the spec. As discussed in #6297.

Clarifying Container Queries page to be about Size

---

features-json/push-api.json

Source: https://twitter.com/dfabu/status/1534223355225575424 (see above as well)
I've been struggling with myself if that warrants partial support, but for now I came to the conclusion yes, because in the past we gave partial even for only support starting with a specific macOS version and here's more.

Changes to Push API regarding Safari

---

features-json/webp.json

WebP should be marked as "other", like JPEG XL https://caniuse.com/jpegxl and AVIF https://caniuse.com/avif, not "unofficial".

Mark WebP as "other"

---

features-json/variable-fonts.json

Fixes #6292.
Biggest struggle regarding the "or" between macOS and Windows - "/" didn't look good, but also I don't want to logically exclude Linux support ("[Linux OSes need the latest Linux Freetype version](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)"), but oh well.
https://en.wikipedia.org/wiki/Windows_10#Updates_and_support

Variable fonts - Update notes for Firefox

---

features-json/push-api.json

I had hoped this would work out as a link as it works in some markdown, [but nope](https://caniuse.com/push-api):
Sorry 0:-)

Fix for link fail I introduced in #6323 

---

features-json/avif.json

- https://twitter.com/jaffathecake/status/1540697894683942912
- https://github.com/WebKit/WebKit/pull/1717
Given it's early and not yet [test](https://tests.caniuse.com/avif)able, draft for now.
@jensimmons are you able to comment on this? :)
If you are, do you know or are able to find out about support for AVIF sequences?
See note 2, Firefox doesn't have them yet: https://caniuse.com/avif
Test here: https://tests.caniuse.com/avif

AVIF coming to Safari & Safari on iOS 16

---

features-json/midi.json

- https://bugs.webkit.org/show_bug.cgi?id=107250
- https://webkit.org/status/#specification-web-midi
Even though they are "Not Considering" they haven't closed the bug yet.
They only thing I could find as to why they are not considering was https://webkit.org/tracking-prevention/.

Web MIDI: Add WebKit support bug & update webkit_id

---

features-json/mathml.json

- Moved the note regarding Opera to a note with number to stick it to the old engine versions as the current general wording is soon about to become incorrect
- The "temporarily" for Chrome might be a bit cheeky, basically being 10 years, but this was a fast way to make it accurate again 0:-)

MathML: Update notes

---

features-json/css-container-queries.json

https://chromestatus.com/feature/6525308435955712
The source for note 3 is there as well:
> Note for M105: Table fragmentation in LayoutNG will not be shipped in M105, but expected to ship in M106. The consequence is that if an author combines table layout and size container queries inside a multicolumn layout, container queries will not work in that context in M105.
There doesn't seem to be a test on https://tests.caniuse.com/css-container-queries yet - I used 
```js
"container" in document.documentElement.style;
```
stolen from https://github.com/GoogleChromeLabs/container-query-polyfill:
Still `false` in 104 (currently Beta).

Size Container Queries starting to ship in Chrome 105 🎉

---

features-json/css3-attr.json

Following the mention on [Jake Archibalds recent post](https://jakearchibald.com/2022/img-aspect-ratio/#:~:text=But%20this%20isn%27t,change%20one%20day!) I went checking:
https://www.w3.org/TR/css-values-4/#changes-recent
> Deferred [toggle()](https://www.w3.org/TR/css-values-4/#funcdef-toggle) and [attr()](https://www.w3.org/TR/css-values-4/#funcdef-attr) to Level 5.
https://drafts.csswg.org/css-values-5 is currently [Editor’s Draft](https://www.w3.org/standards/types#ED), so back to `unoff`.
---
With the double space here
```markdown
on  **any**
```
I'm attempting to fix that there's no space rendered currently, despite one being there in the file:
Is it a bug in the renderer or somewhere, do you know a better fix?
---
Additionally: I guess the file should technically now be changed …

Updates to attr() function for all properties

---

features-json/css-media-resolution.json

Same as (part of) #6148, but for Safari 16 🎉
<https://tests.caniuse.com/css-media-resolution>:
---
I checked the Edge bug, when it was (re-)added(?) [here](https://github.com/Fyrd/caniuse/commit/78c2cefdecf520661fb3947768448c6f50ce33fd#diff-dcdffba17072ff6b3b2e889e170380806f90ec9a18f33243365148462633d1e6) the latest version was 18 using EdgeHTML and at least in the current version it's not around anymore:

Media Queries: resolution for Safari 16 as well + update Edge bug

---

features-json/wasm.json

- website moved
- link to https://webassembly.org/roadmap/
It's only one click away from the homepage, but I thought there's value in directly and clearly linking there.
I had this on my backlog because of the rolling definition of what wasm actually is, without meaningful version numbers (for now): https://github.com/WebAssembly/design/issues/1395

Updates to WebAssembly

---

features-json/asmjs.json

- the deprecation note is a rrremix of both wikipedia and MDN
- copied the webkit id from [the chrome entry](https://chromestatus.com/feature/5053365658583040) - it's not there anymore, but I'd said its better this way than currently showing "WebKit status: Supported" (because of the wasm entry) which was never true for asm.js
- changing only the first chrome in note 1 is intentional

Updates to asm.js: Basically deprecated, links and minor changes

---

features-json/offscreencanvas.json

https://webkit.org/status/#feature-offscreen-canvas

Add `webkit_id` `feature-offscreen-canvas`

---

features-json/mediasource.json

- unused notes 3 and 4 seem to have returned; ref #5470
- maybe just a fail on my side, but I spent way too long thinking about why note 2 is there if support starts with version 13 anyway - because the emphasis is on iPadOS, as in it's iPadOS only. hence here my attempt to make it subtly more clear; ref #4995

Updates to mediasource

---

features-json/u2f.json
features-json/webauthn.json

Following up what [you said here](https://github.com/Fyrd/caniuse/pull/6390#issuecomment-1193371304)
> [@Schweinepriester](https://github.com/Schweinepriester) Think we should change the status to `unoff`? The spec seems to have been a ["review draft"](https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html) so probably should already have been…
and I totally agree!
Additionally I'm trying to add the wrong `webauthm` tag again - you fixed the typo in #6390, but I intentionally wrote it with m, because that was one issue in #6217 :D
But if you understandably don't want tags-with-spelling-error (to increase findability), feel free to remove again :)

U2F => `unoff` & tag with typo again

---

features-json/avif.json

Add note 2 to iOS 16.
Add no support for noise synthesis as note 4 and attach to iOS 16.

Update iOS 16 support in avif.json

---

features-json/web-bluetooth.json

Fixed invalid link for Chrome implementation notes footnote

Update web-bluetooth.json to correct broken link

---

features-json/webvtt.json

https://bugzilla.mozilla.org/show_bug.cgi?id=992664#c12  
→ https://bugzilla.mozilla.org/show_bug.cgi?id=985915#c16
> [status-firefox50](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox50&o1=isnotempty): --- → [fixed](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox50&o1=equals&v1=fixed)
Resolution: --- → FIXED
Target Milestone: --- → mozilla50

Updates to WebVTT

---

features-json/css-has.json

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility) states:
> From version 103: this feature is behind the `layout.css.has-selector.enabled` preferences (needs to be set to `true`).
Tested on Windows with Firefox 103.0.2 and verified this is correct.

Update css-has.json - Firefox supports behind flag

---

features-json/http3.json

Changed description and spec link as HTTP/3 is now standardized.
The spec link now points to [rfc9114](https://datatracker.ietf.org/doc/rfc9114/) and the description has been updated to reflect the current state of the protocol as **Proposed Standard**.

Changed description and spec as HTTP/3 is now standardized

---

features-json/mathml.json

Chrome will not support MathML without a feature flag until version 108.
Source: https://chromestatus.com/feature/5240822173794304

Fix Chrome MathML Support Status

---

features-json/html-media-capture.json

Arrived here via https://austingil.com/html-capture-attribute/ 0:-)
Support on iOS seems to have improved, the `capture` attribute might even be supported, but I'm not fully convinced everything works 100 % after checking the [tests](https://tests.caniuse.com/html-media-capture), so I didn't touch it (yet?).

Tiny indirect typo improvement to HTML Media Capture

---

features-json/css-has.json

Currently the description for `:has()` says:
>Only select elements containing specified content. For example, `a:has(>img)` selects all `<a>` elements that contain an `<img>` child.
First, `a:has(>img)` doesn't select all `<a>` elements that contain an `<img>`. It will only select those that have an `<img>` as a direct child. Because it's `>img` instead of `img`. 
The easiest way to fix this without adding complexity is to simply remove the `>` and make it:  
>For example, `a:has(img)` selects all `<a>` elements that contain an `<img>` child.
Second, I think the first sentence could be a bit more clear. I propose:
> Select elements containing specific content. For example, `a:has(img)` selects all `<a>` elements that contain an `<img>` child.
In addition, I added a link to resources to …

Improve description of `:has()` + add a resource

---

features-json/css-display-contents.json

Here's a pull request with clearer details about what is and is not accessible when `display: contents` is applied to elements in Safari 16.0, Safari 16.1, and Safari Technology Preview.

Clarifications regarding accessibility and `display: contents` 

---

features-json/hevc.json

https://bitmovin.com/google-adds-hevc-support-chrome/
https://bugs.chromium.org/p/chromium/issues/detail?id=460703
Validated on Chrome (105) on windows. macOS and Android.

Update HEVC support page

---

features-json/colr-v1.json

- https://material.io/blog/color-fonts-are-here
- literally matching the MDN entry: https://caniuse.com/?search=colrv1 => https://caniuse.com/mdn-css_at-rules_font-face_opentype_colrv1
- the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1740530 plus changeset https://hg.mozilla.org/integration/autoland/rev/a5e90bc3b2e1
- looks like it might be coming by default in 107, but as there are no changes there yet I will update in the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1791558
- finally, tested using https://tests.caniuse.com/colr-v1 => https://codepen.io/drott_chrome/pen/ExvaYxm
- firefox [doesn't seem to support CBDT/CBLC](https://caniuse.com/mdn-css_at-rules_font-face_opentype_cbdt_cblc), so
>  Emoji on left should be vector versions of emoji on right
isn't true, but left …

COLRv1: Firefox 105+ flag & add link

---

features-json/css-dir-pseudo.json

<https://webkit.org/blog/13207/release-notes-for-safari-technology-preview-154/>:
> Enabled `:dir` by default ([254051@main](https://commits.webkit.org/254051@main), [254106@main](https://commits.webkit.org/254106@main), [253878@main](https://commits.webkit.org/253878@main), [253881@main](https://commits.webkit.org/253881@main), [253896@main](https://commits.webkit.org/253896@main))
<https://tests.caniuse.com/css-dir-pseudo>:
Also, WPT: https://wpt.fyi/results/?label=master&label=experimental&aligned=&view=subtest&q=dir+pseudo
🎉

Safari TP 154: `:dir()` by default

---

features-json/hevc.json

1. HEVC support will be enabled by default since M107 not M105(https://chromiumdash.appspot.com/commit/f46f3399d7ff1119f1f1b9026d31110d7e5b9d8a), the current page is incorrect. Some user who are using chrome below version 107 but greater than version 104 maybe able to use the feature by passing `--enable-features=PlatformHEVCDecoderSupport` switch argument or by randomly hited "finch experment", but in general, not everyone can use it now.
2. Update the correct os and version detail that chrome current supports and also update the link to its support detail.
3. Update `Microsoft Edge` need to install `HEVC video extension` and only on Windows can use the feature.
4. Android support should also be started from M107.

Fix: HEVC is officially supported since M107 not M105

---

features-json/hevc.json

Linux support will also be added since `108.0.5354.0`

Update Chrome HEVC Linux support status

---

features-json/opus.json

This update makes opus title similiar to other audio codecs like aac, flac, and vorbis.

Update "Opus" to "Opus audio format"

---

features-json/css-nesting.json

<https://bugs.chromium.org/p/chromium/issues/detail?id=1095675#c13>:
> Chromium now has basic CSS Nesting support behind the experimental flag.
And indeed, <https://tests.caniuse.com/css-nesting> with the flag turned on:
I thought about adding "basic" or "experimental" in the note as the spec is still shifting I believe, but I think you mentioned `d` implies experimental before anyway?

Chrome 109: CSS Nesting behind flag

---

features-json/css-color-function.json

@svgeesus in <https://bugzilla.mozilla.org/show_bug.cgi?id=1128204#c11>:
> Noting that this is now implemented in Chrome 108 under the experimental flag, in addition to having shipped in Safari.
>
> https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&view=subtest
And indeed, with the flag enabled <https://tests.caniuse.com/css-color-function> shows:
🎉

Chrome 108: CSS `color()` function behind flag 🎉 

---

features-json/requestanimationframe.json

As their forum url changed it broke the url.

Fix known issue link to greensock forum

---

features-json/intersectionobserver.json

<https://github.com/w3c/IntersectionObserver/tree/main/polyfill> is 404 now with no obvious way to get to the repo (you have to edit the URL), therefore directly link to <https://github.com/w3c/IntersectionObserver> :)

Fix IntersectionObserver Polyfill link

---

features-json/font-variant-alternates.json

Inspired by https://twitter.com/jensimmons/status/1590025285168074753 I looked at https://caniuse.com/font-variant-alternates and Chromium, found https://bugs.chromium.org/p/chromium/issues/detail?id=716567.

CSS font-variant-alternates: Add Chromium support bug & fix caniuse link

---

features-json/es6-module-dynamic-import.json

https://bugs.webkit.org/show_bug.cgi?id=201692
Description is an extraction from comments in the bug ([only dynamic imports](https://bugs.webkit.org/show_bug.cgi?id=201692#c1), [inlined modules](https://bugs.webkit.org/show_bug.cgi?id=201692#c3)).
Today I bumped into that problem myself

Safari: not honoring <base> in dynamic imports in inlined modules

---

features-json/hevc.json

1. Edge Mac support HEVC since version 107.
2. Chrome Android support HEVC since version 107.

Update HEVC support status

---

features-json/css-logical-props.json

Hi,
I realized during testing that iOS 14.5+ and Safari 14.1 does not support margin-inline/padding-inline/margin-block/padding-block shorthand when the value is set as a CSS property (fixed in Safari 15).
This can be reproduced it here: https://codepen.io/bakura10/pen/wvXzzVR

Update Safari usage for logical shorthand

---

features-json/viewport-unit-variants.json

> sv* units, lv* units, dv* units and the logical vi/vb units.
stolen from https://chromestatus.com/feature/5170718078140416.
> `sv*` units (`svb`, `svh`, `svi`, `svmax`, `svmin`, `svw`), `lv*` units (`lvb`, `lvh`, `lvi`, `lvmax`, `lvmin`, `lvw`), `dv*` units (`dvb`, `dvh`, `dvi`, `dvmax`, `dvmin`, `dvw`) and the logical `vi`/`vb` units
is a bit unwieldy, but I thought it would be good to have them all for search results? Or move the bulk to tags?
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/length
Random side note: https://trac.webkit.org/changeset/286458/webkit/
---
It would probably be nice to update https://tests.caniuse.com/viewport-unit-variants as well to cover more/all units :)

Updates to viewport units

---

features-json/mathml.json

https://bugs.chromium.org/p/chromium/issues/detail?id=6606#c319
> MathML is going to be released in Chrome 109.
https://chromestatus.com/feature/5240822173794304 also shows 109.
Current Chrome Beta 109 without the flag on https://tests.caniuse.com/mathml:
🎉

Chrome 109: MathML at last! 🎉 

---

features-json/css-nesting.json

- https://mastodon.social/@intenttoship@botsin.space/109720903039657818
- https://groups.google.com/a/chromium.org/g/blink-dev/c/eFCrkiLynfU/m/JLsh3zQuAAAJ
- https://chromestatus.com/feature/5800613594529792
> Estimated milestones
> DevTrial on desktop 109
> DevTrial on Android 109
> Shipping 112
Chrome Canary is still at 111 right now, so https://tests.caniuse.com/css-nesting isn't testable, but I don't think it's blocking this PR as I'm sure we'll adjust if needed.
(Esp. since the syntax is still in flux.)

Chrome 112: CSS Nesting

---

features-json/css-lch-lab.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1352757#c15
> [status-firefox111](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox111&o1=isnotempty): --- → [fixed](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox111&o1=equals&v1=fixed)
Resolution: --- → FIXED
Target Milestone: --- → 111 Branch
https://hg.mozilla.org/mozilla-central/diff/3fa8d29c7c448ff587e467ef82764024f53f0b26/modules/libpref/init/StaticPrefList.yaml
> layout.css.more_color_4.enabled
<https://tests.caniuse.com/css-lch-lab>:
There's back and forth in [the Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1333988), but even current Chrome beta 110.0.5481.38:

LCH and Lab are coming in Chrome & Firefox

---

features-json/u2f.json

<https://bugzilla.mozilla.org/show_bug.cgi?id=1809333>
> So we can set the default value of security.webauth.u2f to false in 111.
> [status-firefox111](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox111&o1=isnotempty): --- → [fixed](https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox111&o1=equals&v1=fixed)
Resolution: --- → FIXED
Target Milestone: --- → 111 Branch
<https://hg.mozilla.org/integration/autoland/rev/8e01a52267b3>

U2F API is being removed in Firefox

---

features-json/loading-lazy-attr.json

`loading=lazy` has [a memory leak in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1213045) that still hasn't been fixed.

Add a memory leak bug in Chrome for the lazy loading attribute

---

features-json/referrer-policy.json

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1720294
Also updated the Safari note to mention the other two header values that would allow a longer referrer but are ignored due to ITP.

Firefox 92+ ignores unsafe referrer policies

---

features-json/css-paint-api.json

CSS Painting API is the official name used by the [W3C Candidate Recommendation Draft][1]. Using the official name in a search on the caniuse.com website yields no results.
[1]: https://www.w3.org/TR/css-paint-api-1/

Rename: CSS Paint API -> CSS Painting API

---

features-json/decorators.json

Early on as the decorators proposal first got momentum, it was (wrongfully) assumed that decorators would make it into ES7. That is not the case and searches for "es7" on caniuse today will bring up decorators even though they're not part of ES7.

Remove es7 from decorators keywords

---

features-json/css-color-function.json

- https://github.com/mdn/content/blob/main/files/en-us/mozilla/firefox/releases/111/index.md#css
- https://github.com/mdn/content/issues/24395
- https://github.com/mdn/content/pull/25015
> CSS color functions `color()`, `lab()`, `lch()`, `oklab()`, and `oklch()` are now supported. These features are disabled by default and can be enabled by setting the preference `layout.css.more_color_4.enabled` to true. For more information, see the [CSS color value](https://github.com/mdn/content/blob/main/en-US/docs/Web/CSS/color_value) documentation ([Firefox bug 1352757](https://bugzil.la/1352757) and [Firefox bug 1128204](https://bugzil.la/1128204)).
(Don't know why it's not yet on <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/111>…) …

Firefox 111: CSS color() function as well

---

features-json/hevc.json

1. Actually macOS and Android also bundled a software decoder, on these platforms, as long as the system version meets the requirements, all devices will support it.
2. Linux and ChromeOS's support is very limited, since Chromium currently only support VAAPI for HEVC.

Updated HEVC support status to make it more accurate

---

features-json/web-app-manifest.json

Removing this part of the definition of A2HS:
>To enable this behaviour, a website must serve a valid Web App Manifest and load it's assets through a [Service Worker](https://caniuse.com/#feat=serviceworkers).
That is the definition in some browsers, but not others. A simpler definition is better — especially to reflect the variation between implementations. Safari has never required a Service Worker for Add to Home Screen.

Correcting definition of A2HS

---

features-json/web-bluetooth.json

Update two of the links to the implementation status page to use the `main` branch. (The link using the `master` branch was still working, but consistency is good)

Update Web Bluetooth implementation status links

---

features-json/declarative-shadow-dom.json

Hi, I want to add a link to the firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1712140

Declarative Shadow DOM: add Firefox bugzilla URL

---

features-json/datalist.json

Chromium browsers can only show the first 512 elements in the dropdown.

Add bug to <datalist> element

---

features-json/av1.json
features-json/heif.json
features-json/hevc.json

When I updated all image descriptions in #5523, I skipped `HEIF` because it was a bit unclear what exactly it was tracking. Now that Safari has restarted developer awareness of it, I wanted to give it a shot.
Main changes:
`HEIF` is a relatively simple container format that can be used for many things, for example to package `JPEG`- or `AV1`-encoded images. I do not think it makes sense to track support for that here, and thus I have tried to mention it as little as possible.
What people normally think of when they hear `HEIF`, is an `HEIF` container with `HEVC`-encoded content.  This is _theoretically_ what you get if you have an `HEIC` file. The support that @Schweinepriester just added in #6738 is also specifically referring to support for Apple's `HEIC` files with `HEVC`-encoded …

Update description of HEIF and HEVC formats

---

features-json/link-rel-preconnect.json

We fixed rel=preconnect in Fx 115
https://bugzilla.mozilla.org/show_bug.cgi?id=1543990

Update link-rel-preconnect.json for Firefox fix in 115

---

features-json/avif.json

It doesn't work in Edge 116 (Dev/Canary) on Windows 10 21H2.
It works in Edge 116 (Dev/Canary) on Windows 11 Moment 3 (22621.1848). 
To be confirmed if Moment 3 is the key factor here?
It doesn't work in Edge 114 (Stable) on Windows 11 Moment 3 (22621.1848). 
Need some help with the validation here too, since Edge Canary is not part of the data model yet.

Add partial support for AVIF in Edge Dev/Canary 

---

features-json/css-media-range-syntax.json

I noticed that some of the code was improperly placed in a inline code – [link](https://caniuse.com/css-media-range-syntax):

Fix typo for "Media Queries: Range Syntax"

---

features-json/fullscreen.json

Fullscreen API also includes the `:fullscreen` pseudo class.
https://fullscreen.spec.whatwg.org/#:fullscreen-pseudo-class

fullscreen: add CSS category

---

features-json/jpegxr.json

- (DE) https://www.gamestar.de/artikel/neues-update-fuer-windows-11-soll-euren-desktop-hintergrund-so-viel-besser-machen,3398929.html
- https://blogs.windows.com/windows-insider/2023/08/04/announcing-windows-11-insider-preview-build-25921/
> You can now set JXR files to be your desktop background and if you have an HDR display, they will render in full HDR.
- https://en.wikipedia.org/wiki/JPEG_XR
> JPEG XR (.JXR) format
If you search for "jxr" currently, [the entry for JPEG XR](https://caniuse.com/jpegxr) isn't found: https://caniuse.com/?search=jxr
Fixing that 🙃

Add "jxr" keyword to JPEG XR

---

features-json/opus.json

VBR CAF can be produced by ffmpeg and theoretically is spec-compliant, but Safari (and macOS Quicktime Player) will refuse to decode. Unfortunately Opus defaults to (constrained) VBR because it works better that way!

Opus/CAF: clarify that only CBR is supported

---

features-json/avif.json

https://www.neowin.net/news/microsoft-edge-is-finally-getting-avif-support-long-after-firefox-google-chrome-and-safari/
At one time Dev and Beta supported it, but I forget when they dropped it.

Edge Insider supports AVIF via runtime flag

---

features-json/css-relative-colors.json

https://bugs.chromium.org/p/chromium/issues/detail?id=1274133#c11
Tested [this codepen](https://codepen.io/argyleink/pen/VwrKRrY) chrome (118.0.5980.1) and edge (118.0.2071.0) canary

add relative color support in chrome canary

---

features-json/hevc.json

#6858
It uses the same API as Edge as of now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1853448
https://bugzilla.mozilla.org/show_bug.cgi?id=1859080
https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding#whats-the-tech-diff-compared-with-edge--safari

Firefox 120 Nightly has started to support HEVC via OS API

---

features-json/ogv.json

- https://groups.google.com/a/chromium.org/g/blink-dev/c/qqDdLkeyk7Y/m/ajHePzglAwAJ
- https://chromestatus.com/feature/5158654475239424
… and Firefox might follow suit: https://bugzilla.mozilla.org/show_bug.cgi?id=1860492

Chrome is deprecating and removing Theora support

---

features-json/wake-lock.json

on iOS it does not work in standalone (aka PWA) mode, only works in the actual browser. Tested on iOS 17. I think it is important to mention because it reduces possible use cases

iOS bug with Screen Wake Lock API

---

features-json/es5.json
features-json/es6.json

Apparently, the https://github.com/kangax/compat-table repo has been transferred to https://github.com/compat-table/compat-table. Although the URL https://kangax.github.io/compat-table/ is redirected to https://compat-table.github.io/compat-table/, links like https://kangax.github.io/compat-table/es6/ or https://kangax.github.io/compat-table/es5/ are actually broken, so we need to update them.

Fix broken links to kangax.github.io/compat-table/

---

features-json/jpegxl.json

Now jpegxl can be enabled in stable version of firefox also (not only in nightly) so the note should be updated.

Update firefox note in  jpegxl.json

---

features-json/decorators.json

Mozilla currently working on adding decorators [TC39/proposal decorators](https://github.com/tc39/proposal-decorators)
I didn't find any information about other vendors

Decorators: add link to Bugzilla

---

features-json/outline.json

The support for `-moz-outline-radius` properties [has been removed](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/88#css) in Firefox 88.

Remove -moz-outline-radius note

---

features-json/loading-lazy-attr.json

Updates for loading=lazy bugs
- Safari doesn't load lazy elements when you print
- Firefox requires the loading attribute to be defined before the src attribute
- The chrome mem leak got fixed

loading=lazy bugs

---

features-json/jpegxl.json

Reverts Fyrd/caniuse#6887
The flag `image.jxl.enabled` is ***still useless*** even in Firefox 120 stable.
No task to link libjxl even in stable builds is not linked to <https://bugzilla.mozilla.org/show_bug.cgi?id=1539075>.
This means that there have been no changes related to JPEG XL for stable builds.

Revert "Update firefox note in  jpegxl.json" (#6887) and mention pitfall that the flag has no effect in the other builds than Nightly

---

features-json/colr.json

Updated the status, and revised the footnote to be a bit more professional/objective.

COLR0 is fixed in STP 183 + Safari 17.2 (PR to replace 6888)

---

features-json/hevc.json

2nd phase of #6858 
I rolled back my Firefox to 120 once but could not play HEVC even with the flag.
10bit or higher colors are not supported.
https://bugzilla.mozilla.org/show_bug.cgi?id=1839107
https://codepen.io/danm8675123/pen/abNavqG

Firefox 121 stable can enable HEVC via flag

---

features-json/css-cascade-scope.json

It would also be great if a search for 'scope' would produce this as the top result, instead of the deprecated 2014 feature. Is that possible?

@scope rule is defined in an official working draft spec

---

features-json/push-api.json

- https://9to5mac.com/2024/03/01/apple-home-screen-web-apps-ios-17-eu/
- https://www.macrumors.com/2024/03/01/apple-walks-back-decision-to-disable-eu-web-apps/
https://developer.apple.com/support/dma-and-apps-in-the-eu/
> UPDATE: Previously, Apple announced plans to remove the Home Screen web apps capability in the EU as part of our efforts to comply with the DMA. The need to remove the capability was informed by the complex security and privacy concerns associated with web apps to support alternative browser engines that would require building a new integration architecture that does not currently exist in iOS.
>
> We have received requests to continue to offer support for Home Screen web apps in iOS, therefore we will continue to offer the existing Home Screen web apps capability in the …

Safari on iOS 17.4 doesn't drop Home Screen web apps after all 😌

---

features-json/wake-lock.json

- https://bugzilla.mozilla.org/show_bug.cgi?id=1589554#a138295037_725173
- https://bugzilla.mozilla.org/show_bug.cgi?id=1883724

Firefox is postponing shipping Screen Wake Lock API

---

features-json/zstd.json

Couldn't find an issue, so https://github.com/WebKit/standards-positions/issues/168 it is 0:-)

Add WebKit position link to zstd

---

features-json/jpegxl.json

You can check this with the following image using the Safari browser: [Link of animated JXL sample](https://jpegxl.info/test-page/anim-icos.jxl)
It should be animated like this <img width=50 src="https://jpegxl.info/test-page/anim-icos.webp"> but it won't.
- https://jpegxl.info/test-page/

jpegxl.json: macOS/iOS Safari does not support animated JXL yet

---

features-json/apng.json

PNG has been Candidate Recommendation since 21 September 2023
https://www.w3.org/TR/2023/CR-png-3-20230921/

PNG no longer a WD

---

features-json/webtransport.json

This bug makes it difficult to use WebTransport for p2p things in chromium browsers.

fix: known chromium issue with WebTransport

---

features-json/mpeg4.json

Source: I'm on the Firefox Media Team at Mozilla.

Firefox for Android supports h264 hw acceleration + fix linux note

---

features-json/font-smooth.json

- https://botsin.space/@intenttoship/112534747361273284
- https://groups.google.com/a/mozilla.org/g/dev-platform/c/zQ4bhw78uac/m/gM2GOY7kBQAJ
- https://bugzilla.mozilla.org/show_bug.cgi?id=1670993
- https://github.com/whatwg/compat/issues/115

Firefox 128 and later supports `-webkit-font-smoothing: antialiased`

---

features-json/opus.json

see docs and discussion at:
* https://stackoverflow.com/questions/70143421/webm-and-opus-in-safari
* https://github.com/Fyrd/caniuse/issues/6805#issuecomment-2102183335
* https://github.com/Fyrd/caniuse/issues/7056#issuecomment-2111259595
* https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#Media
* https://developer.apple.com/documentation/safari-release-notes/safari-17_5-release-notes#Media

update to webm opus support since Safari 17.4

---

features-json/webgpu.json

It shipped in Safari Technology Preview 190, in March 2024.

Safari Technology Preview supports WebGPU

---

features-json/link-rel-dns-prefetch.json

See the latest updates in https://bugzilla.mozilla.org/show_bug.cgi?id=1596935 or the Firefox 127 release notes: https://www.mozilla.org/en-US/firefox/127.0/releasenotes/

Firefox >= 127 supports rel="dns-prefetch" in HTTPS too

---

features-json/css-sticky.json

If the parent element has the properties position: absolute and overflow: visible, and the parent element's parent element has the property overflow: hidden, the relative position seems to become relative to the top-level window.
[Sticky test html.zip](https://github.com/Fyrd/caniuse/files/13988999/Sticky.test.html.zip)
Google Chrome 120.0.6099.225
Safari on iOS 17.2.1

Add description to css-stick

---

features-json/css-scrollbar.json

Fixes https://github.com/Fyrd/caniuse/issues/7112.
Basically a follow-up to https://github.com/Fyrd/caniuse/pull/6957 and also adds https://chromestatus.com/feature/5665308343795712.

Align CSS scrollbar styling for Chrome for Android

---

features-json/cookie-store-api.json

https://github.com/WebKit/standards-positions/issues/36
https://bugs.webkit.org/show_bug.cgi?id=258504

Update webkit links for cookie-store-api

---

features-json/webgpu.json

PR for #7124.
Adding the fact WebGPU is available in Safari 17.4+ on both macOS and iOS, after flipping the feature flag. 
Updated the footnote to not say "macOS" so it can be used now for both. Also, replacing "experimental feature" with "feature flag". The word "experimental" is used by Chrome, not Safari. We call it a "feature flag" — which comes in three flavors "testable", "preview", and "stable". (Testable = can be tested by flipping the feature flag. Preview = on in Safari Technology Preview. Stable = on by default for all users.)

WebGPU is supported in Safari 17.4+ behind a flag

---

features-json/web-share.json

Web Share API support has been added for macOS in Chrome. I could also test this locally on my machine running Chrome Beta 128.0.6613.18 on macOS.
This is in accordance to the Chrome Beta 128 release notes: https://developer.chrome.com/blog/chrome-128-beta#web_share_api_on_macos

Update Chrome support for Web Share API

---

features-json/web-share.json

Footnote 2 for the Web Share API ends on a 404 on Chrome developer documentation.
The current link is: https://developer.chrome.com/multidevice/android/intents
The correct link should be: https://developer.chrome.com/docs/android/intents
This fixes #7130

Fix Android intent link in Web Share API

---

features-json/webauthn.json

Removing `#4`, since using an authenticator with a PIN definitely is supported, see screenshot.
Also adding `#7` since firefox on mobile doesn't support direct attestations due to them having an extra privacy requirement, which they haven't implemented the UI for.
Firefox on mobile working fine with a FIDO 2 authenticator with PIN enabled:

chore: update status for webauthn on firefox mobile

---

features-json/cookie-store-api.json

- https://bugzilla.mozilla.org/show_bug.cgi?id=1475599#c28
- https://hg.mozilla.org/integration/autoland/diff/d55b6525d7b24d90ac7e1b092e4fef698cc244fe/modules/libpref/init/StaticPrefList.yaml
- https://wpt.fyi/results/cookie-store?label=master&label=experimental&aligned=
- https://tests.caniuse.com/cookie-store-api

Firefox 132 adds Cookie Store API behind flag

---

features-json/css-relative-colors.json

- https://chromestatus.com/feature/4755025804132352
- https://issues.chromium.org/issues/325309578
- https://bugzilla.mozilla.org/show_bug.cgi?id=1893966
Not entirely sure about the system color aspect, but seemingly those WPT tests are the only ones: https://wpt.fyi/results/css/css-color?label=experimental&label=master&aligned&view=interop&q=label%3Ainterop-2024-relative-color

Chrome 131 supports `currentcolor` in Relative Color & more

---

features-json/temporal.json

The linked bug was closed more than a year ago, and a new [META] one has been opened.
In my opinion the newly linked bug gives a better understanding of the status of the implementation efforts going forward in Firefox.

Update Temporal's Firefox implementation bug

---

features-json/wasm-simd.json

WASM  SIMD requires SSE 4.1 to run.  This PR adds a note to this effect.
see https://github.com/bytecodealliance/wasmtime/issues/3809

SSE 4.1 required note

---

features-json/mutation-events.json

Fixes https://github.com/Fyrd/caniuse/issues/7182.
A lot of context there^ already, but for completeness links I came across while digging:
- https://www.w3.org/standards/history/uievents/
- https://www.w3.org/TR/2024/WD-uievents-20240906/#legacy-mutationevent-events still in the spec
- https://www.w3.org/TR/2024/WD-uievents-20240907/ removed
- https://chromestatus.com/feature/5083947249172480
- https://github.com/mozilla/standards-positions/issues/807
- https://github.com/WebKit/standards-positions/issues/192

Updates to Mutation events in light of deprecation

---

features-json/css-boxdecorationbreak.json

Fixes #7193.
Best merge this before updating Android to 130 0:-)
Links along the way:
- https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break#browser_compatibility
- https://issues.chromium.org/issues/41295617
- https://chromestatus.com/feature/5162398704205824
- https://github.com/WebKit/standards-positions/issues/366
- https://bugs.webkit.org/show_bug.cgi?id=144249
- https://wpt.fyi/results/css/css-break?label=master&label=experimental&aligned=&q=box-decoration-break
- https://github.com/web-platform-tests/interop/issues/723

Chrome 130 supports box-decoration-break

---

features-json/input-datetime.json

As seen in the beta release notes, Safari 18.2 adds support for input type=week on iOS. 
https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes#Forms

input type=week in Safari 18.2

---

features-json/wasm-simd.json

WASM is just a specification. Nothing in it requires any features from the host CPU; you can always emulate complex WASM features using simpler CPU instructions.
The PR that originally added this note (#7167) referenced a discussion in Wasmtime: bytecodealliance/wasmtime#3809. However, nothing in that issue means that it's impossible to implement WASM SIMD without SSE 4.1. It just means that _Wasmtime_ specifically didn't want to at the time, because it's harder. In fact, according to bytecodealliance/wasmtime#3810 they do now support SIMD instructions on CPUs without any optional extensions.
I haven't investigated whether any browsers or runtimes other than Wasmtime impose CPU requirements to use WASM SIMD. But if they do, such notes should probably go on the browser and not on the …

Remove note stating SSE 4.1 is required for WASM SIMD

---

features-json/temporal.json

Firefox 135 Nightly now supports Temporals behind the `javascript.options.experimental.temporal` flag.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1912757
- https://www.mozilla.org/en-US/firefox/135.0a1/releasenotes/

Firefox 135 Nightly supports Temporal behind a flag

---

features-json/css3-attr.json

- https://issues.chromium.org/issues/40320391
- https://chromium-review.googlesource.com/c/chromium/src/+/6091991
- https://groups.google.com/a/chromium.org/g/blink-dev/c/2dNLhQN9SNs
- https://wpt.fyi/results/css/css-values?label=master&label=experimental&aligned&q=attr
- https://chromestatus.com/feature/4680129030651904?gate=5932337540366336

Chrome 133 supports CSS attr() function for all properties

---

features-json/css-content-visibility.json

[Safari has a bug](https://bugs.webkit.org/show_bug.cgi?id=283846) where content skipped using `content-visibility: auto` is not findable using the find-in-page feature as [it’s spec’d to](https://drafts.csswg.org/css-contain/#valdef-content-visibility-auto) ([a _MUST_ requirement](https://datatracker.ietf.org/doc/html/rfc2119#section-1)). This PR adds a known issue for the `content-visibility` feature at-large which both links to the bug report and includes a concise description of it.
I’ve already highlighted the issue in the browser-compat-data (https://github.com/mdn/browser-compat-data/pull/25781), so that it shows the implementation as partial for `content-visibility: auto` specifically.

Add known bug for `content-visibility` in Safari

---

features-json/css-line-clamp.json

The MDN article for CSS line-clamp was missing, so I added it.

CSS line-clamp edited to include link to MDN article

---

features-json/css-backgroundblendmode.json

The MDN web docs article was missing from the CSS background-blend-mode, so I added it.

Edited CSS background-blend-mode to add link to MDN.

---

features-json/webgpu.json

I noticed the page for WebGPU says "All major browser engines are working on implementing this spec. All major browser engines are working on implementing this spec."
Hm. The same sentence twice? I came here to fix it. But in JSON, it's only there once. Interesting. Well, this note isn't needed at all in Feb 2025, since seeing feature flags for both WebKit and Gecko browsers tells the same story. So I'm deleting it, expecting that will fix the bug as well.

Removing redundant note from WebGPU

---

features-json/hevc.json

- all via https://github.com/mdn/content/commit/4f6e436684338f9e1256108b456d28b28c9726b0
- didn't bother to unfurl the details below 137
- does note 8 strike the balance of usefulness and vagueness?
- thought better link to their docs instead of maintaining them here as well…
- once this part https://github.com/mdn/content/commit/4f6e436684338f9e1256108b456d28b28c9726b0#diff-f5860e33aa3a50f159eb13611e4d750e9b7995d8eaf398bd15816afe1c60f964 is live on https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Video_codecs#hevc_h.265, I'd try to more precisely text-link there
<https://tests.caniuse.com/hevc> looks good for one case at least

Firefox enables more HEVC

---

features-json/webgpu.json

Fixes #7390, all details there. Didn't test myself, but because of the webkit bug little doubt is left, imho.

WebGPU only being enabled by default on macOS 26 Tahoe or later

---

features-json/css-anchor-positioning.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1988224#c11

Firefox 145 is enabling CSS Anchor Positioning by default in Nightly
